### ISSUE TITLE
Support for NVIDIA Jetson Xavier NX

### ISSUE THREAD

**Issue by jung-youjin** [Picovoice/picovoice#102]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour

I followed the [installation document](https://picovoice.ai/docs/quick-start/picovoice-jetson/) as I thought this would be also working on **Jetson Xavier NX**. I am using Xavier instead of Nano right now. Is this why I can't execute the following command?
``` bash
picovoice_demo_mic \
--keyword_path resources/porcupine/resources/keyword_files/jetson/picovoice_jetson.ppn \
--context_path resources/rhino/resources/contexts/jetson/smart_lighting_jetson.rhn
```

If it is due to my hardware, I would like to know how I could get this resolved!
Thank you!

### Actual behaviour

``` bash
ss@ss-desktop:~/picovoice/picovoice$ picovoice_demo_mic \
> --keyword_path resources/porcupine/resources/keyword_files/jetson/picovoice_jetson.ppn \
> --context_path resources/rhino/resources/contexts/jetson/smart_lighting_jetson.rhn
WARNING: Please be advised that this device (CPU part = 0x004) is not officially supported by Picovoice. Falling back to the armv6-based library. This is not tested nor optimal.
Traceback (most recent call last):
  File "/usr/local/bin/picovoice_demo_mic", line 5, in <module>
    from picovoicedemo.picovoice_demo_mic import main
  File "/usr/local/lib/python3.6/dist-packages/picovoicedemo/picovoice_demo_mic.py", line 21, in <module>
    from picovoice import Picovoice
  File "/usr/local/lib/python3.6/dist-packages/picovoice/__init__.py", line 12, in <module>
    from .picovoice import Picovoice
  File "/usr/local/lib/python3.6/dist-packages/picovoice/picovoice.py", line 14, in <module>
    import pvporcupine
  File "/usr/local/lib/python3.6/dist-packages/pvporcupine/__init__.py", line 15, in <module>
    LIBRARY_PATH = pv_library_path('')
  File "/usr/local/lib/python3.6/dist-packages/pvporcupine/util.py", line 94, in pv_library_path
    raise NotImplementedError('Unsupported platform.')
NotImplementedError: Unsupported platform.
```

### Steps to reproduce the behaviour

Followed the documentation procedure without errors until the last line.

(Include enough details so that the issue can be reproduced independently.)

**Comment by jung-youjin** [comment]
I'm sorry that I have labeled as a `bug` instead of `feature request` 😿

**Comment by dbartle** [comment]
Yes, we only officially support the Jetson _Nano_. We can keep this issue open to track if there is interest from others and use that to determine if adding such support is a business priority.

**Comment by kenarsa** [comment]
We didn't get much traction here. closing for now
