### ISSUE TITLE
How to train wake-up words on Android

### ISSUE THREAD

**Issue by Star3513** [Picovoice/picovoice#104]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour

Train wake-up words on the Android platform

### Actual behaviour

Train wake-up words only for Linx, MacOS and Windows platforms

### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced independently.)

I can only choose to train the wake-up words on Linux platform. Can I use them on Android platform

**Comment by Star3513** [comment]
@laves

**Comment by dbartle** [comment]
Custom wake words are not available with personal accounts outside of Linux, Mac, and Windows.
