### ISSUE TITLE
[Flutter] Picovoice package - function to start listening without wake word

### ISSUE THREAD

**Issue by AlexHartford** [Picovoice/picovoice#106]
Hi there, I am wondering if there would be a way to expose the start method from rhino on the picovoice flutter package. 

Currently, if you are using https://pub.dev/packages/picovoice, the porcupine wake word is the only way to start recognizing speech with rhino.

If you have a button and a wake word to start listening, like most voice assistants, this means I'd also have to use the rhino package with a separate callback to handle speech recognition from a button press.

I would be happy to implement this but it appears your flutter package is closed source.

**Comment by dbartle** [comment]
The source for the flutter package is here: https://github.com/Picovoice/picovoice/tree/master/sdk/flutter. Pull requests of this nature are very much welcome.

**Comment by kenarsa** [comment]
At this point, we decided to not go after this feature. The rationale is that one can create this feature using `Rhino` (and possibly `Porcupine`) as needed.

**Comment by AlexHartford** [comment]
It could be helpful to future readers if you elaborated on that possibility with a concrete example
