### ISSUE TITLE
[Flutter SDK] Show current speech from user

### ISSUE THREAD

**Issue by AlexHartford** [Picovoice/picovoice#113]
I have seen in some of your demos that you are able to display the words being spoken on other platforms. This is something I'd like to add to my Flutter app.

I plan to start looking into how to accomplish this but wanted an issue to track if anyone else had ideas, etc.

After further investigation, I have no idea how to accomplish this. I would love to help if someone is willing to guide me.

**Comment by laves** [comment]
@AlexHartford, the Picovoice SDK does not transcribe speech and thus there is no way to show the words being spoken. The Rhino Speech-to-Intent engine performs recognition solely in the acoustic domain. To achieve the effect you are looking for, you would have to use a Speech-to-Text engine.

**Comment by AlexHartford** [comment]
Okay, thanks!
