### ISSUE TITLE
Is ARM Cortex-A supported?

### ISSUE THREAD

**Issue by varmaricha** [Picovoice/picovoice#115]
I have an [ARM Cortex-A8 board](https://www.phytec.com/product/phycore-am335x/), and at some point read in the Picovoice documentation that A-series is supported (can no longer find that page). However, the MCU demos only include Cortex-M4 and M7. Is it possible to run the models on Cortex-A8? Any pointers would be appreciated.

**Comment by kenarsa** [comment]
Raspberry Pi, Beagle Bone, and Jetson Nano (these are supported platforms) are all Cortex-A MPUs. We don't have support for the board you are mentioning. Beagle Bone is Cortex-A8 so you might be able to use that but we can't guarantee. If you have a board that is not supported you can open an issue asking for it and we keep it open for a while to track traction from the community to make a decision if we want to support it or not.
