### ISSUE TITLE
Add support for SensorTile Box- STM32MKSBOX1V1

### ISSUE THREAD

**Issue by shivashankarivr** [Picovoice/picovoice#117]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kenarsa** [comment]
this is a lot of work. we don't have immediate plans for it. but lets keep it open to measure traction and maybe we put it on our roadmap.

**Comment by kenarsa** [comment]
We didn't get much traction for this platform and hence closing for now.
