### ISSUE TITLE
Picovoice Documentation Issue

### ISSUE THREAD

**Issue by llvllch** [Picovoice/picovoice#118]
### What is the URL of the doc?

https://picovoice.ai/docs/quick-start/picovoice-raspberrypi/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)

The documentation doesn't explicitly state that Raspberry Pi is a restricted platform, ie Custom Wake words cannot be set on a personal account

**Comment by kenarsa** [comment]
did you read the docs? https://picovoice.ai/docs/quick-start/console-signup/
it clearly says we don't provide porcupine with personal accounts. x86_64 is still being provided for legacy reasons.

**Comment by llvllch** [comment]
My point wasn't that it is not stated in within the docs, just that:
```
Create Custom Wake Words & Contexts

You can create custom Porcupine wake word and Rhino context models using Picovoice Console.```

May be another place that would benefit from including the message.
