### ISSUE TITLE
Picovoice Issue: Soundlevel always 0 on STM32F411E-DISCO

### ISSUE THREAD

**Issue by Jokymon** [Picovoice/picovoice#119]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
After connecting my STM32F411E-DISCO using `pvshepherd` I would expect to be able to record some audio - even some ambient noise - and see samples != 0 in the recorded output.

### Actual behaviour
Everytime I record audio, the amplitude always stays 0. 
![Output-After-Recording](https://user-images.githubusercontent.com/1139000/128379649-22f79228-a3c7-4542-806a-c85e8d66aaca.png)

This is also reflected in the fact, that no voice recognition is working at all.

### Steps to reproduce the behaviour

I used an STM32F411 Discovery Kit out of the box, connected both USB cables and used a fairly recent `pvshepherd`-version 0.9.9 that I installed via pip.

**Comment by mrrostam** [comment]
Just to make sure that there is nothing wrong with the onboard mic, can you please try the `BSP` example inside STM32CUBEIDE and verify that the mic is working correctly for that project?

![image](https://user-images.githubusercontent.com/42750891/128526023-78ee75dd-b907-4084-b8cf-2952a4a9ba10.png)

**Comment by Jokymon** [comment]
Thanks for your support. It turns out, the problem is indeed a defective microphone. I could try on a different board and got it working flawlessly.
