### ISSUE TITLE
Ziggy pronunciation 

### ISSUE THREAD

**Issue by builderjer** [Picovoice/picovoice#140]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
Allow 'Ziggy' to be used as a wake work

### Actual behaviour
Throws an error `Missing pronunciations for words: [“ziggy”].`

### Steps to reproduce the behaviour
Try to create wake word with the word 'Ziggy'

(Include enough details so that the issue can be reproduced independently.)

Pronunciation definition available [here](https://www.wordsense.eu/Ziggy/)

**Comment by kenarsa** [comment]
Will be added in the next release.

**Comment by builderjer** [comment]
Any word on getting this added?

**Comment by kenarsa** [comment]
You can create your model using this workaround `zig e`. This is too short, so you need to prepend it with something like `hey` >>> `hey zig e`.

**Comment by builderjer** [comment]
Awesome!! Thank you
