### ISSUE TITLE
Picovoice Documentation Issue (/docs/tutorials/using-picovoice-engines-with-react/)

### ISSUE THREAD

**Issue by dereklowlind** [Picovoice/picovoice#142]
### What is the URL of the doc?
https://picovoice.ai/docs/tutorials/using-picovoice-engines-with-react/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
The links in 2.1 Bindings all go to a 404 not found page. Could someone point me to the new files so I can update this tutorial to work with the latest version?

**Comment by kenarsa** [comment]
@dereklowlind Thank you! This is definitely outdatd. I will put it in our queue. In the meantime, you can use the quick start for react SDK instead.

**Comment by laves** [comment]
This tutorial is no longer relevant, so we've removed it and redirected it to a more current resource.
