### ISSUE TITLE
Can you add support for STM32WB5MM-DK

### ISSUE THREAD

**Issue by vadymsodolevsky** [Picovoice/picovoice#143]
**Is your feature request related to a problem? Please describe.**
https://www.st.com/en/evaluation-tools/stm32wb5mm-dk.html 
Discovery kit with STM32WB5MMG only has microphone and no speaker.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vadymsodolevsky** [comment]
Hello dear support. 
Can I implement porting for STM32WB5 itself? 
Will I have trouble with UUID of microcontroller that used in creation of Default Models?
Thanks.

**Comment by mrrostam** [comment]
I appreciate your enthusiasm; however, you could not port Picovoice to STM32WB5 by yourself as it requires some work from our side to modify and optimize the core engine for this new platform. The lib files would not perform as is on STM32WB5. 

If you want this for an industrial application, please shoot an [email](hello@picovoice.ai) to my co-workers and describe it. We'll find a solution for you.

**Comment by kenarsa** [comment]
We didn't get much traction for this platform. closing for now
