### ISSUE TITLE
Picovoice Console Issue: Multilingual support

### ISSUE THREAD

**Issue by shilovav3** [Picovoice/picovoice#146]
Dear Sir/Madam,

You have announced on your blog a possibility to select languages:
               https://picovoice.ai/blog/picovoice-goes-multilingual/
We need to perform something like that on a microprocessor (BeagleBone),
that is:
	select language
	recognize few command

Could you, please advice how it can be done?
Which package (GitHub) can be used for that?
How a model with multilingual selection can be created?
“English” (en)
“Deutsch” (de)
“Español” (es)
“Français” (fr) 

Thank you!

Best regards,
               Alex.

Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced independently.)

**Comment by kenarsa** [comment]
You should read the docs in this repo! You can use either C or Python SDK.
