### ISSUE TITLE
Picovoice Multilingual support

### ISSUE THREAD

**Issue by shilovav3** [Picovoice/picovoice#147]
Dear Sir/Madam,

This issue are related to issue:
    Picovoice Console Issue: Multilingual support #146
that was close prematurely.

I need to select language. For that one model should recognized words
in different languages (this is the words that a user should say to select a language):
“English” 
“Deutsch” 
“Español” 
“Français” 

Picovoice console cannot create one model with words of different languages.
Could you, please explain how your demonstration was made?
                https://picovoice.ai/blog/picovoice-goes-multilingual/

Having an example of the code would be very helpful!

Your representative claimed in issue #146 that reply is in the documentation.
Could you, please specify where in the documentation is written about creation of a model having words of different languages?

Thank you!

Best regards,
    Alex.

**Comment by kenarsa** [comment]
You can run multiple models (one per language) simultaneously and then select the language based on the wake word triggere. hope it helps.
