### ISSUE TITLE
Need support on Mediatek 8516 (ARM Cortex-A 35

### ISSUE THREAD

**Issue by sasi4289** [Picovoice/picovoice#15]
Dear Piocvoice Team ,

I started to understand the  Pico Voice SDK  for Basic voice  recognition . I tried a  basic  porcupine wake word example with python (linux86_64).  It is a great working example . currently i have few basic query about Pico Voice SDK (porcupine) 

1. I want to port the porcupine to Mediatek 8516 (ARM Cortex-A 35). Is this ARM Cortex-A 35 supported Pico Voice SDK   ?

2. I want to build  custom wake words of non-phonetic words  like (VVDN) . is this possible?

Thank you for your support .

**Comment by kenarsa** [comment]
This is not a bug! If you are going to set a label to your issue please make sure you use the correct one.

If this is for a personal project you can use either RPI or BeagleBone as we don't have support for your CPU at this time. If this is a commercial project you can send a formal request of engagement  and we might be able to help https://picovoice.ai/contact/sales/
