### ISSUE TITLE
Code size vs. model size on MCUs

### ISSUE THREAD

**Issue by Jokymon** [Picovoice/picovoice#150]
The Rhino and Porcupine models for our use case turned out really small (~500 bytes for wake word and ~3’000 bytes for commands) which makes the solution very attractive for our targeted devices. However the software running these models comes to 330 kBytes of flash memory (from GitHub I could see that the ELF-file for picovoice library alone uses 349kB (https://github.com/Picovoice/picovoice/blob/master/sdk/mcu/lib/stm32f411/libpicovoice.a)). Compared to other solutions we found, this seems rather big. Could you shed some light on where these 330k of code come from? Is there some form of compression involved in these models? Is it a smart way of factoring out common model data? Or asking from a different direction, do you think it might be possible to reduce the size of this code (or the libpicovoice) for a commercial product?

**Comment by kenarsa** [comment]
If you have a question regarding commercialization [contact sales](https://picovoice.ai/contact/sales/)
