### ISSUE TITLE
Picovoice Issue: Automatically closes services while running 

### ISSUE THREAD

**Issue by Kiru3014** [Picovoice/picovoice#152]
Hi
I am Using Picovoice as a service on my android device it auto-stop/closes services while listening. 

SDK
https://github.com/Picovoice/picovoice/tree/master/demo/android/Service

errop log:
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void ai.picovoice.picovoice.PicovoiceManager.stop()' 
 on a null object reference at ai.picovoice.picovoicedemoservice.VoiceService.onDestroy(VoiceService.java:226)

**Comment by Kiru3014** [comment]
yes its happning in service example of github 
https://github.com/Picovoice/picovoice/tree/master/demo/android/Service

**Comment by Kiru3014** [comment]
Log : 
Unable to stop service ai.picovoice.picovoicedemoservice.PicovoiceService@75433: java.lang.NullPointerException: Attempt to invoke virtual method 'void ai.picovoice.picovoice.PicovoiceManager.stop()' on a null object reference

     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void ai.picovoice.picovoice.PicovoiceManager.stop()' on a null object reference

**Comment by laves** [comment]
Can you provide steps to reproduce this error? Under normal usage, I can't reproduce this issue. That call to `stop()` is in a try/catch so it should not cause a crash.

**Comment by Kiru3014** [comment]
Step 1: import the Following Picovice service code in android studio 
https://github.com/Picovoice/picovoice/tree/master/demo/android/Service

Step 2: Replace the .rhn file with the following the file can change file to new in MainActivity.java under **startService()** method
https://ufile.io/36b7080p (test_demo.rhn)
Step 3 : In PicovoiceService.java in **onStartCommand** method under  **.setInferenceCallback** 
              replace isunderstood code with following snipt
   if (inference.getIsUnderstood()) {
                                    final Map<String, String> slots = inference.getSlots();
                                    if (inference.getIntent().equalsIgnoreCase("Open")) {
                                        if (slots.size() > 0) {
                                            for (String key : slots.keySet()) {
                                                if (slots.get(key).equalsIgnoreCase("Settings")) {
                                                    Intent settings = new Intent(Settings.ACTION_SETTINGS);
                                                    startActivity(settings);
                                                        builder.append("Settings");

                                                } else if (slots.get(key).equalsIgnoreCase("Camera")) {
                                                    Intent camera = new Intent(Settings.ACTION_SETTINGS);
                                                    startActivity(camera);
                                                        builder.append("Camera");

                                                }
                                            }
                                        }
                                    }
                                }

Step 4: Run the application on Android OS 10 and say **porcupine Open Settings** or **porcupine  Open Camera** Application will Crash.


let me know if any steps are unclear i will share a video

**Comment by laves** [comment]
It seems you're trying to start a new activity from a background thread on a background service. There are a host of [restrictions](https://developer.android.com/guide/components/activities/background-starts) on this action. I was able to get it to work with the Picovoice Service Demo using:
```java
Intent settings = new Intent(Settings.ACTION_SETTINGS);
settings.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
startActivity(settings);
```
This is not a bug with one of our products or demos. In the future, please be sure to narrow down the problem to our software before opening a GitHub issue.
