### ISSUE TITLE
Picovoice Issue: Always getting Didn't understand the command. 

### ISSUE THREAD

**Issue by Kiru3014** [Picovoice/picovoice#154]
Hi Team I am trying to implement Pico voice in my application when ere i say sentence  it will deduct wakeup words later it give 
"Didn't understand the command." message every time example in 10 trial 8 trial it give same message How to resolve this ?

**Comment by kenarsa** [comment]
I'm closing this issue as it does not provide enough information to reproduce. If you want our team to look into this you need to provide all the information needed for us to reproduce the issue.

**Comment by Kiru3014** [comment]
Hi @kenarsa 
Please refer following steps to import sample code 

https://github.com/Picovoice/picovoice/issues/152#issuecomment-956502796

After importing the above steps run the application on android 10 and Say the following Phrases **porcupine Open Settings** or **porcupine Open Camera**

issue: whenever I say the above Expressions in the  following condition, it always reaches to **inference.getIsUnderstood()** as false in my trial 

        if (inference.getIsUnderstood()){
          //intent condition
        }else{
           builder.append("Didn't understand the command.");
       }

  For example: if I try from 5 times by saying above "Expressions" 3 times I will reach as  false in  **inference.getIsUnderstood()** condition 

**Requires solution:** What is the best way to get less number of false conditions on **inference.getIsUnderstood()**

  Note: I have tested using google translator as well as normal users same both give the same results.
