### ISSUE TITLE
Picovoice Documentation Issue: Limitations of Personal Accounts

### ISSUE THREAD

**Issue by trakevital** [Picovoice/picovoice#155]
### What is the URL of the doc?

https://picovoice.ai/pricing/
https://github.com/Picovoice/rhino/issues/65

### What's the nature of the issue? 

I have a non-commercial project in which I am tasked with creating a working product which will be used by individuals. The product I'm tasked to create is a mechanical hand using a raspberry pi that will open and close once someone says "open" or "close". Before the speech command there should be a 'wake word' whose task is to trigger the speech recognition process, this is needed in order to reduce the amount of false positives and reduce the CPU usage which will reduce battery consumption. Thus, your software was great for my needs. Nevertheless, the personal license which is for non-commercial purposes has a few limitation which I wasn't aware of only after spending a day of work on making your product work:

1. Apparently, you only have a 30 day expiration date on rihno and porcupine files generated via the console.
2. The porcupine only allows for popular operating systems such as, linux, mac and windows but is restricted for less common operating systems such as that of the raspberry pi.

These limitations (and there might be others I'm not aware of), disallow me to use your software for my project to my sorrow. If you could provide much more clarity on this topic upfront it would waste much less time and energy, and hopefully remove these restrictions for non-commercial usages.

**Comment by kenarsa** [comment]
The 30-day expiry is covered in the docs, [here](https://picovoice.ai/docs/quick-start/console-signup/). That being said, we are making changes to make the platform more useful for projects such as yours before the end of the year.
