### ISSUE TITLE
Picovoice Issue: Always getting Didn't understand the command. #154

### ISSUE THREAD

**Issue by Kiru3014** [Picovoice/picovoice#156]
Hi @kenarsa 
Please refer following steps to import sample code 

https://github.com/Picovoice/picovoice/issues/152#issuecomment-956502796

After importing the above steps run the application on android 10 and Say the following Phrases **porcupine Open Settings** or **porcupine Open Camera**

issue: whenever I say the above Expressions in the  following condition, it always reaches to **inference.getIsUnderstood()** as false in my trial 

        if (inference.getIsUnderstood()){
          //intent condition
        }else{
           builder.append("Didn't understand the command.");
       }

  For example: if I try from 5 times by saying above "Expressions" 3 times I will reach as  false in  **inference.getIsUnderstood()** condition 

**Requires solution:** What is the best way to get less number of false conditions on **inference.getIsUnderstood()**

  Note: I have tested using google translator as well as normal users same both give the same results.

_Originally posted by @Kiru3014 in https://github.com/Picovoice/picovoice/issues/154#issuecomment-956512628_

**Comment by kenarsa** [comment]
@Kiru3014 happy to look into this if you can reproduce using the demo without any code modifications. I do need the PPN and RHN files as well.

**Comment by Kiru3014** [comment]
Hi @kenarsa I am using the same PPN file which is there is a demo example but below is the 
RHN file I have changed 
https://ufile.io/36b7080p (this is RHN file)

**Comment by kenarsa** [comment]
We could not re-create the issue using the context provided and hence cannot help.
