### ISSUE TITLE
Picovoice Documentation Issue (/docs/quick-start/console-signup/)

### ISSUE THREAD

**Issue by shivashankarivr** [Picovoice/picovoice#159]
### What is the URL of the doc?
https://console.picovoice.ai/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
Hi, am trying to signup using Enterprise Console, but am not receiving confirmation code mail. I did checked in junked mail folder but didn't receive. Please check.

Thanks

**Comment by kenarsa** [comment]
most probably you entered the wrong email address (a typo). I suggest trying again and seeing if the issue persists. if yes,  send an email to help@picovoice.ai with the email address you used and we look into it.
