### ISSUE TITLE
PC Microphone Interfacing

### ISSUE THREAD

**Issue by tanhejiang** [Picovoice/picovoice#16]
Hi PV!

I was reading up on how I can use the Picovoice SDK and realised that there are no example codes on how I can get the audio from the PC microphone (developing on dotnet C#). That portion is just commented in the documentation. I believe that this can be done using NAudio. Can I check if an example code can be given so that it the SDK can be easily implemented? Keen to try the non-demo codes on PC but couldn't.

**Comment by laves** [comment]
If you check out the [Picovoice demo for dotnet](/demo/dotnet) you can see how we do audio capture in .NET Core. We use OpenAL because it allows desktop cross-platform audio capture. If you prefer NAudio, you can use that too, but it will limit audio capture to Windows-only.
