### ISSUE TITLE
Picovoice Console Issue: Typo after email confirmation: "commerical" -> "commercial"

### ISSUE THREAD

**Issue by samueldg** [Picovoice/picovoice#183]
`s/commerical/commercial/`

<img width="1214" alt="picovoice-typo" src="https://user-images.githubusercontent.com/4542383/142715073-47a23fcd-5bb1-42dd-962d-6fa7d74155d2.png">

**Comment by kenarsa** [comment]
After `v2` release there is only one account type! :)
