### ISSUE TITLE
Picovoice Issue: Custom wakeup word not deducted

### ISSUE THREAD

**Issue by Kiru3014** [Picovoice/picovoice#199]
Hi team I am using the custom wakeup word "Hey Mic" for voice assist in the console is is able to detect the voice but in the android application wakeup word is not detected also I have an update "Hey mic" .ppn file asset and code as below 

![image](https://user-images.githubusercontent.com/36956488/143182838-ed2e52f9-3e43-4e66-ae39-8f44d1d51a37.png)

**Comment by kenarsa** [comment]
please follow the [docs](https://picovoice.ai/docs/quick-start/porcupine-android/#custom-keywords). If the issue is not resolved after you followed the docs step-by-step feel free to re-open.
