### ISSUE TITLE
Why is an access key required if the library can work offline?

### ISSUE THREAD

**Issue by josegonzalez** [Picovoice/picovoice#222]
### What is the URL of the doc?

https://github.com/Picovoice/picovoice/blob/master/README.md

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)

It's not super clear why all the examples show usage of a license key if the library can work in offline mode. Can the docs clarify what the key is for in that case?

**Comment by Jonas2OO3** [comment]
A follow-up question to this: the documentation states that via the Picovoice console, "You can also see your limits and monitor your current usage in real-time."

How can that be, if the library runs offline?

**Comment by Jonas2OO3** [comment]
Ah, see https://picovoice.ai/pricing Question 4.

> We track the number of users via access keys that are used to activate our products. Once in a while, access keys are validated by our servers to stay active. (There is no voice data or anything other information is sent to our cloud. The voice data is processed offline. It’s your data, you own and control it.)

Still, "real time" implies more frequently than "once in a while"?

I cannot find any information about the way the usage in seconds of access keys is counted? Is it seconds processing the intents?

**Comment by kenarsa** [comment]
We count the number of devices you deploy our SDK into using `AccessKey`.

Realtime does not mean constant or instantaneous in this context. In the link to the pricing page provided by @Jonas2OO3, you see that we want to count the number of active devices/user per month. A check every couple of weeks would suffice to provide the latest snapshot (real-time) count. Hope it helps.
