### ISSUE TITLE
Picovoice Issue: 

### ISSUE THREAD

**Issue by raiv-toulouse** [Picovoice/picovoice#224]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour

Run picovoice_demo_mic with french files.

picovoice_demo_mic --access_key XXXXXXX --keyword_path bonjour-machine_fr_linux_v2_0_0.ppn --context_path test_fr_linux_v2_0_0.rhn

### Actual behaviour

[ERROR] Keyword files (.PPN) and model file (.PV) should belong to the same language. Keyword files belongs to 'fr' while model file belongs to 'en'.

### Steps to reproduce the behaviour

I'm sure to have selected 'french' when I've generated the test model so the test_fr_linux_v2_0_0.rhn file should be french, not english.

![test](https://user-images.githubusercontent.com/50733895/145110070-f212d48e-5fef-41c0-b3a0-945086eec783.png)

**Comment by kenarsa** [comment]
You need to pick the correct `.PV` file. It is documented [here](https://picovoice.ai/docs/quick-start/picovoice-python/#non-english-languages).
