### ISSUE TITLE
Picovoice Console: export intents for voice interface documentation

### ISSUE THREAD

**Issue by cmcinroy** [Picovoice/picovoice#23]
**Is your feature request related to a problem? Please describe.**
I have found myself wanting to reference the expressions list (for the intents of a context) outside of the Console browser window, whether it is in conversation with others or potentially in documentation for the voice interface being developed.

**Describe the solution you'd like**
The ability to export/download the intents defined in a context, prefereably in a text format (markdown?).

**Describe alternatives you've considered**
Hmm... screenshot of the Console? Copy-paste?

**Additional context**
N/A

**Comment by kenarsa** [comment]
Thank you for this. Indeed we've been thinking about this as well. We can possibly enable exporting the context in a standard format such as YAML. Adding the product owner to the issue.

**Comment by dbartle** [comment]
Thanks, this is helpful feedback. We've added a new feature to Rhino that lets you import and export in YAML format. The new buttons are on the bottom-right corner of the Rhino editor.

**Comment by cmcinroy** [comment]
Wow, fantastic! That's perfect, thank you!
