### ISSUE TITLE
access key limitation at dev phase for mobile (Android & iOS)

### ISSUE THREAD

**Issue by sohrabq** [Picovoice/picovoice#232]
**Everytime I re-install in my simulator, the Picovoice console treats me as a new device**
this is really annoying while having a Picovoice access key which is meant to work only for 3 devices, but the most important problem is that every install in the same devices is treated as new device.

**Developer key should not expires!**
since the name clarify that it is a developer access key, then why should it get expires. and if it expires then I am thinking if you would apply a policy that your system keeps track of the only devices no matter how many times it's getting installed on that specific device.
hopefully a more systematic solution is given to this problem. cause as a developer someone would really be in trouble while debugging and re-installing new versions.

**Comment by laves** [comment]
@sohrabq - we've addressed this issue with the release of v2.1. Simulator deployments and development builds of your application should no longer be counted multiple times.

**Comment by sohrabq** [comment]
hay @laves that's perfect news.
