### ISSUE TITLE
Picovoice Documentation IssueSupport for NVIDIA Jetson Xavier NX?

### ISSUE THREAD

**Issue by Tim-Chen-code** [Picovoice/picovoice#234]
### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
Support for NVIDIA Jetson Xavier NX now?

**Comment by kenarsa** [comment]
We only support `NVIDIA Jetson Nano` at the moment.

**Comment by Tim-Chen-code** [comment]
thank you



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | Alireza ***@***.***> |
| 日期 | 2021年12月15日 23:29 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [Picovoice/picovoice] Picovoice Documentation IssueSupport for NVIDIA Jetson Xavier NX? (Issue #234) |

Closed #234.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
