### ISSUE TITLE
Console - footer blocks submit button on mobile

### ISSUE THREAD

**Issue by reryro** [Picovoice/picovoice#235]
The "Complete Picovoice Console sign-up" screen provides no visible Submit button or any other apparent means to submit the sign up form. (Am using Chrome browser on Android OS). Also tried Firefox -- same result.

**Comment by kenarsa** [comment]
I just signed up for a new account on Console (using Chrome) and it worked fine. These are the steps:

1- enter email/pass
2- enter verification code
3- enter additional information and check the boxes and then press the `Continue to Console` button.

I guess you are saying the `Continue to Console` button doesn't show up for you?

**Comment by reryro** [comment]
That's correct -- there are no buttons on my screen. But I'm also
apparently seeing a different screen -- I'm presented with a form that asks
for first & last names, company, company website, job title, and industry,
along with checkboxes for receive newsletter and agree to terms. And no,
entering values in each field doesn't trigger any button to appear.

**Comment by kenarsa** [comment]
Can you send a screenshot along with the email you used to `hello@picovoice.ai`? (so that your info remains private). Once we can debug further we continue the conversation here.

**Comment by kenarsa** [comment]
Ok. I did take a look and I think this is the problem we have on mobile (small screens). Can you please try this on a larger screen?   Something like a laptop .. this should solve the problem for now. I keep the issue and we work on a fix in the coming days.

**Comment by reryro** [comment]
Yeah, well, I'm on my phone because my PC is down with a crashed drive & my
son took my tablet to college with him, so...as soon as I replace that
drive...

**Comment by ksyeo1010** [comment]
The issue has been resolved.

**Comment by reryro** [comment]
Yes, I can confirm. Thank you, and sorry I couldn't respond before... been
dealing with Covid. (Isn't everyone? :-(
