### ISSUE TITLE
Picovoice Documentation Issue

### ISSUE THREAD

**Issue by cmcinroy** [Picovoice/picovoice#24]
### What is the URL of the doc?
https://picovoice.ai/use-cases/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
Just a question, really, related to the Use Cases listed:
Enterprise Assistants and Smart Home are listed as possibilities... do you have suggestions for a STT engine to incorporate audio feedback in those scenarios? It would be interesting to learn of any details related to efforts (e.g. case studiy) to include Picovoice in a conversational interface.

**Comment by kenarsa** [comment]
Thanks for the feedback. Just to clarifiy, do you mean TTS? (text to speech). Happy to provide more details afterwards.

**Comment by cmcinroy** [comment]
Yes, precisely! i.e. a way to provide audio feedback, either to augment the visual interface or for situations where visual is secondary (or unavailable).

**Comment by kenarsa** [comment]
It really depends on your use case. If the number (combination) of audio feedback(s) is limited, I strongly suggest using pre-recorded audio. It gives better quality and more stability. If this is not the case then you need a TTS in place.

**Comment by cmcinroy** [comment]
Ok, great. Thanks for your feedback. 👍
