### ISSUE TITLE
TypeError: create() got an unexpected keyword argument 'access_key'

### ISSUE THREAD

**Issue by printmanpro** [Picovoice/picovoice#242]
import pvporcupine

access_key = "my access key" 

handle = pvporcupine.create(access_key=access_key, keywords=['picovoice'])

When I run this python code , or any of the python demos i get this error

TypeError: create() got an unexpected keyword argument 'access_key'

I have checked and key-check the access key is correct..
Any help?

**Comment by kenarsa** [comment]
@printmanpro you need to provide more information. What is the OS? What is the version of `pvporcupine` and `pvporcupinedemo`?

**Comment by printmanpro** [comment]
Hi..
OS is Raspbian Bullseye
Not sure how to check for versions of porcupine and demo ( maybe you can help?)

**Comment by printmanpro** [comment]
Another update..
This command " picovoice_demo_mic --show_audio_devices " fails with an error because it requires an access key.
If I include the access key I can view the audio devices..

**Comment by kenarsa** [comment]
I just tried the demo on a Raspberry Pi 3 and it worked fine for me. Can you please provide the command you are entering and I try it just like that (exclude your ACCESS_KEY argument)

**Comment by printmanpro** [comment]
I am using a Raspberry Pi 4
As mentioned at the beginning have tried with this code in python3

import pvporcupine
access_key = "my access key"
handle = pvporcupine.create(access_key=access_key, keywords=['picovoice'])

Or if I try a demo "copied from github"
code -- porcupine_demo_mic --access_key my_access_key --keywords picovoice -- end code

So are you saying that I do not need an access key?

**Comment by kenarsa** [comment]
You do need an `AccessKey`. You need to create one on `Picovoice Console` and use it when running the engine. I just updated `pvporcupinedemo` to `2.0.4` to give more detailed error messages. If you upgrade and send me the exception again I can potentially help more.

**Comment by printmanpro** [comment]
Hi.. and thanks for trying to help me through this problem. I installed pvporcupinedemo 2.04 and the problem seems to have disappeared.
Thanks for your help
