### ISSUE TITLE
Initialization failed

### ISSUE THREAD

**Issue by RezaS** [Picovoice/picovoice#245]
Hi,

I would like to use Picovoice in Android as a service. For now, I am using ai.picovoice:picovoice-android:2.0.1.

I am using the same code from the demo but with the following changes:

``` java
picovoiceManager = new PicovoiceManager.Builder()
        .setAccessKey(ACCESS_KEY)
        .setPorcupineModelPath("porcupine_params_de.pv")
        .setRhinoModelPath("porcupine_params_de.pv")
        .setKeywordPath(keywordFilePath)
        .setPorcupineSensitivity(0.7f)
        .setWakeWordCallback(picovoiceWakeWordCallback)
        .setContextPath(contextPath)
        .setRhinoSensitivity(0.25f)
        .setInferenceCallback(picovoiceInferenceCallback)
        .setProcessErrorCallback(picovoiceManagerErrorCallback)
        .build(getBaseContext());
picovoiceManager.start();
```
I get the exception _Initialization failed_ but I don't see why.

![screenshot](https://user-images.githubusercontent.com/4928297/147409205-b70c364d-25a6-4cd0-b51a-7bafaaed2e57.png)

My AccessKey is the same as on https://console.picovoice.ai/access_key and it's getting used on 1 device only.

**Comment by kenarsa** [comment]
what do you see in the Logcat?

**Comment by RezaS** [comment]
@kenarsa when I start the service, this is what I get:


> - I/PICOVOICE:  [INFO] Porcupine model path : '/data/user/0/ch.yourclick.kitt/files/porcupine_params_de.pv'
> - I/PICOVOICE:  [INFO] Porcupine keyword path [0] : '/data/user/0/ch.yourclick.kitt/files/my_file_de_android_v2_0_0.ppn'
> - I/PICOVOICE:  [INFO] Porcupine sensitivity [0] : 0.70
> - W/.yourclick.kit: Accessing hidden method Landroid/app/ActivityThread;->currentActivityThread()Landroid/app/ActivityThread; (greylist, JNI, allowed)
> - W/.yourclick.kit: Accessing hidden method Landroid/app/ActivityThread;->getApplication()Landroid/app/Application; (greylist, JNI, allowed)
> - I/PICOVOICE:  [INFO] Rhino model path : '/data/user/0/ch.yourclick.kitt/files/porcupine_params_de.pv'
> - I/PICOVOICE:  [INFO] Rhino context path : '/data/user/0/ch.yourclick.kitt/files/my_file_de_android_v2_0_0.rhn'
> - I/Choreographer: Skipped 90 frames!  The application may be doing too much work on its main thread.
> - I/OpenGLRenderer: Davey! duration=1510ms; Flags=0, IntendedVsync=62662102620378, Vsync=62663602620318, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=62663605016860, AnimationStart=62663605058860, PerformTraversalsStart=62663607477060, DrawStart=62663607712060, SyncQueued=62663607818660, SyncStart=62663609214860, IssueDrawCommandsStart=62663609342160, SwapBuffers=62663611264160, FrameCompleted=62663614179260, DequeueBufferDuration=666300, QueueBufferDuration=1033400, GpuCompleted=0,

**Comment by kenarsa** [comment]
OK. I see it in your image now. Your rhino model is incorrect ... it should be `rhino_params_de.pv` not `porcupine_params_de.pv`

**Comment by RezaS** [comment]
Yes! Absolutely correct. Thank you!!
