### ISSUE TITLE
Picovoice Console Issue: Missing pronunciations for words: [“zoe”]

### ISSUE THREAD

**Issue by BP-Kurii** [Picovoice/picovoice#246]
Missing pronunciations for words: [“zoe”]
Language: German
Common alias: Zoé, Zoë und Zoey
Pronouncing in german: "So ii" (Same as in english, "So-E")
Links for Pronounciation:
https://www.google.com/search?q=Zoe+aussprache&sxsrf=AOaemvLsy7q7XwQbxOfc-BmwyutEsOqANA%3A1640621895246&source=hp&ei=R-fJYcbSC6uIxc8PmuCyqAs&iflsig=ALs-wAMAAAAAYcn1V6_39fz24Gdo6DaFSilMUqcPlnNJ&ved=0ahUKEwiGkpjqsIT1AhUrRPEDHRqwDLUQ4dUDCAk&uact=5&oq=Zoe+aussprache&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEMgUIABCABDIFCAAQgAQyBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMggIABAWEAoQHjoECCMQJzoRCC4QgAQQsQMQgwEQxwEQ0QM6EQguEIAEELEDEIMBEMcBEKMCOgsIABCABBCxAxCDAToLCC4QgAQQsQMQgwE6DgguEIAEELEDEMcBENEDOhEILhCABBCxAxCDARDHARCvAToICAAQgAQQsQM6CAguEIAEELEDOg4ILhCxAxCDARDHARCvAToNCAAQgAQQsQMQgwEQCjoFCC4QgAQ6BwgAEIAEEApQAFjyJGCXJmgAcAB4AIABjQGIAekJkgEDOS41mAEAoAEB&sclient=gws-wiz

The name stands for "Live", "Living", "Humanity" and would be perfect fitting for AI

### Actual behaviour
Missing pronunciations for words: [“zoe”]. If these words are present in a respected German dictionary, please provide a link to the word and its pronunciation via a GitHub issue . Custom pronunciations and branded words can be created for commercial customers; contact Picovoice for more information.

### Steps to reproduce the behaviour
Create a new Wake Word for "German". Use "Zoe", "Zoey" as Wake Word

**Comment by kenarsa** [comment]
our `fr` and `en` models do have the word. it seems like we only included it in those languages as this is more popular within those languages. with the proper names, it is impossible to have full coverage. please use one of those languages for your wake work.
