### ISSUE TITLE
AccessKey used on an unknown device

### ISSUE THREAD

**Issue by RezaS** [Picovoice/picovoice#247]
Hi, 

console.picovoice.ai was showing me that I am using the AccessKey on 3 devices. First, I thought that it's because I am using it on multiple applications (demos and my own app). So I deleted my account and created a new one. Now it's showing that I am using the AccessKey on 2 of 3 devices, which is not true. This time I have used it on 1 application (i.e. 1 emulator) only. Nothing else.

Is that a bug or is that something that I don't understand?

**Comment by kenarsa** [comment]
We are tracking this issue [here](https://github.com/Picovoice/picovoice/issues/232) and working on a fix. The workaround right now is to develop on a device (not an emulator) and don't delete the app.
