### ISSUE TITLE
Listen to whatever the user says

### ISSUE THREAD

**Issue by RezaS** [Picovoice/picovoice#249]
This is my expression:

> Are you fast(er than)

User says ...
_Are you fast_ - OK
_Are you faster than_ - OK
_Are you faster than a rocket_ - Fail

Is there a way I could set a wildcard? For instance like: _Are you fast(er than) *_

**Comment by kenarsa** [comment]
there is NO wildcard expression in rhino.

**Comment by RezaS** [comment]
Is it planned to implement this in future?

**Comment by kenarsa** [comment]
no plans at the moment.
