### ISSUE TITLE
Picovoice Documentation Issue (/docs/)

### ISSUE THREAD

**Issue by jax200** [Picovoice/picovoice#25]
### What is the URL of the doc?

https://picovoice.ai/docs/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)

It is unclear how to sign-up for a personal account.  I am interested in trying out for speed-to-text on a raspberry pi.

**Comment by dbartle** [comment]
The instructions for signup is here (it's the second page of the docs): https://picovoice.ai/docs/quick-start/console-signup/
The actual sign-up / auth page is here: https://console.picovoice.ai/

If you are interested in using Speech-to-_Intent_ on a Raspberry Pi, a personal account will allow that via Rhino. However, we do not presently have a Speech-to-Text offering available on console for Raspberry Pi.
