### ISSUE TITLE
Picovoice Documentation Issue (/docs/quick-start/picovoice-python/)

### ISSUE THREAD

**Issue by francesco7752** [Picovoice/picovoice#253]
### What is the URL of the doc?
https://picovoice.ai/docs/quick-start/picovoice-python/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
I can't figure out if I need to replace the terms:
$ {ACCESS_KEY}
$ {KEYWORD_FILE_PATH}
$ {CONTEXT_FILE_PATH}
or are they environment variables that must be defined (in this case how)?
In case you need to replace the terms where I find the KEYWORD_FILE_PATH and the CONTEXT_FILE_PATH
I am working on a Raspberry Pi4 with Python 3.7 and s.o. Buster

**Comment by kenarsa** [comment]
You do need to replace them. the doc explains them and you can also use the [GitHub doc](https://github.com/Picovoice/picovoice/tree/master/demo/python) as well.
