### ISSUE TITLE
Picovoice Documentation Issue (/docs/quick-start/picovoice-python/)

### ISSUE THREAD

**Issue by francesco7752** [Picovoice/picovoice#256]
### What is the URL of the doc?
https://picovoice.ai/docs/quick-start/picovoice-python/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
On the basis of what is indicated in this doc I wrote the following program where I replaced the variables with my data and my system:

#!/usr/bin/python3
# -*- coding: utf-8 -*-
#preso da https://picovoice.ai/docs/quick-start/picovoice-python/
from picovoice import Picovoice

def wake_word_callback():
    print (" wake word callback")
    pass
def inference_callback(inference):
   if inference.is_understood:
      intent = inference.intent
      slots = inference.slots
      print (" inference callback")
      # take action based on intent and slot values
   else:
      # unsupported command
      print("unsupport inference callback")
      pass

handle = Picovoice(
     access_key='xxxxxxmykey',
     keyword_path='/home/pi/.local/lib/python3.7/site-packages/pvporcupine/resources/keyword_files/raspberry-pi',
     wake_word_callback=wake_word_callback,
     context_path='/home/pi/rhino/resources/contexts',
     inference_callback=inference_callback)
print ('aaaa')
def get_next_audio_frame():
    pass

while True:
    audio_frame = get_next_audio_frame()
    handle.process(audio_frame)

handle.delete()
 

*********    
The result is:

[ERROR] loading keyword file at '/home/pi/.local/lib/python3.7/site-packages/pvporcupine/resources/keyword_files/raspberry-pi' failed with 'IO_ERROR'
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/picovoice/picovoice.py", line 190, in __init__
    sensitivities=[porcupine_sensitivity])
  File "/home/pi/.local/lib/python3.7/site-packages/pvporcupine/__init__.py", line 82, in create
    sensitivities=sensitivities)
  File "/home/pi/.local/lib/python3.7/site-packages/pvporcupine/porcupine.py", line 158, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine.porcupine.PorcupineIOError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/porcupine_mio/picovoice_prova0.py", line 30, in <module>
    inference_callback=inference_callback)
  File "/home/pi/.local/lib/python3.7/site-packages/picovoice/picovoice.py", line 192, in __init__
    raise _PPN_RHN_ERROR_TO_PICOVOICE_ERROR[type(e)] from e
picovoice.picovoice.PicovoiceIOError

I

**Comment by kenarsa** [comment]
`keyword_path='/home/pi/.local/lib/python3.7/site-packages/pvporcupine/resources/keyword_files/raspberry-pi'` this is a folder. you need the path to a keyword file (a file with `.ppn` suffix). You either generate these from Console and grab one from GitHub repo.

**Comment by francesco7752** [comment]
OK, Tanks

**Comment by francesco7752** [comment]
Ok thanks
