### ISSUE TITLE
How to diagnose "Didn't understand the command" in picovoice_demo_mic?

### ISSUE THREAD

**Issue by cmcinroy** [Picovoice/picovoice#26]
### What is the URL of the doc?
Demo: https://picovoice.ai/docs/api/rhino-python/
Rhino API (Python): https://picovoice.ai/docs/api/rhino-python/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
With Rhino, in the case where the `process` function returns is_finalize, but the resulting inference was not understood, is there any way to get more information about what was interpreted? or about the sound levels of the sample?

Specifically, I would like to be able to distinguish between background noise and a verbal command that did not match any intents.

When using the microphone demo, if I speak the wake word then say nothing, I consistently get "Didn't understand the command". I am wondering whether that results from background noise? or is the demo (Rhino?) simply timing out? I tried decreasing the sensitivity, but that didn't seem to have any bearing.

**Comment by kenarsa** [comment]
You are correct. In both cases (timeout and command it cannot understand) it returns is_understood = false. The API does not provide more information. What's the use case you are trying to address?

**Comment by cmcinroy** [comment]
Thanks for the info!

My use case is a conversational context. If the wake word starts the conversation, there is an opportunity to process successive speech samples, to act on a series of discrete intents.
I recognize that Rhino needs a timeout... in this case, it would be beneficial to distinguish between that possibility and failing to match speech sample to intent.
Otherwise:

> kenarsa: Craig, could you pass the salt?
> cmcinroy: Sure, here you are.
> (pause)
> cmcinroy: Wha'd you say?
> 

🙂

**Comment by kenarsa** [comment]
got it. Thanks for the feedback. It seems like you need a VAD module. It should add the extra information you need. Hope it helps.

**Comment by cmcinroy** [comment]
Thank you for the suggestion.
