### ISSUE TITLE
Emulator is not the same as console.picovoice.ai

### ISSUE THREAD

**Issue by RezaS** [Picovoice/picovoice#264]
I am testing the same expression on https://console.picovoice.ai and on my Android emulator. 

I try to speak exactly the same way and with the same volume. Most of the time the expression will be known on console.picovoice.ai but on my emulator, almost every time the expression is unknown. 

What could be the issue?

**Comment by kenarsa** [comment]
there is no difference from the engine. it is most probably the mic setup in your emulator.
