### ISSUE TITLE
Picovoice Console Issue: Rhino Module File Spanish

### ISSUE THREAD

**Issue by Christianhg10** [Picovoice/picovoice#286]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour

I expected my app work with rhino spanish version 2.1.0. 

### Actual behaviour
Error: context file belongs to 'es' while model files belong to 'en'. Although I am using the last rhino_params_es.pv version (2.1.0)

![image](https://user-images.githubusercontent.com/58950154/150536520-003620a5-cdd8-4486-89b5-e8a04ac0b500.png)

### Steps to reproduce the behaviour

I am only set a new Object with the neccesary params.

const pvInstance = new Picovoice(
  accessKey,
  keywordArgument,
  porcupineCallback,
  contextPath,
  inferenceCallback,
  0.5,
  0.5,
  true,
  porcupineEs,
  rhinoEs
);

**Comment by kenarsa** [comment]
please take a look at [this](https://picovoice.ai/docs/quick-start/picovoice-nodejs/#non-english-languages)

**Comment by Christianhg10** [comment]
> I think I have followed the instructions. What is wrong? I share more detail of my code.

const Picovoice = require("@picovoice/picovoice-node");
const { COMPUTER } = require("@picovoice/porcupine-node/builtin_keywords");
const recorder = require("node-record-lpcm16");

const contextPath = "../Comprar-cafe.rhn";
const accessKey = "M############################";
const porcupineEs = "../picovoice_languages/porcupine_params_es.pv";
const rhinoEs = "../picovoice_languages/rhino_params_es.pv";
const keywordPath = "../oye-Ejuan-es.ppn";

const keywordCallback = keyword => {
  console.log(`Detectado'`);
  console.log(`¿Que bebida te gustaría?`);
  
}

const rhinoCallback = inference => {
  console.log("Inference:")
  console.log(inference)
  console.log()
  console.log()
  console.log(`Listening for 'EJUAN'...`);
}
const inferenceCallback = function (inference) {
  console.log("Inference:");
  console.log(JSON.stringify(inference, null, 4));
};

const pvInstance = new Picovoice(
  accessKey,
  keywordPath,
  keywordCallback,
  contextPath,
  inferenceCallback,
  0.5,
  0.5,
  true,
  porcupineEs,
  rhinoEs
);

**Comment by laves** [comment]
@Christianhg10, I tried your code with a Spanish keyword and context that I trained on Picovoice Console, in combination with the param files from GitHub and was unable to reproduce your error:
```javascript
const keywordPath = "/home/ian/Downloads/hola-hola_es_linux_v2_1_0.ppn";
const contextPath = "/home/ian/Downloads/cafe_es_linux_v2_1_0.rhn";
const accessKey = "#################################";
const porcupineEs = "/home/ian/work/github/picovoice/resources/porcupine/lib/common/porcupine_params_es.pv";
const rhinoEs = "/home/ian/work/github/picovoice/resources/rhino/lib/common/rhino_params_es.pv";

const pvInstance = new Picovoice(
    accessKey,
    keywordPath,
    keywordCallback,
    contextPath,
    inferenceCallback,
    0.5,
    0.5,
    true,
    porcupineEs,
    rhinoEs
);
```

Are you sure all your packages are 2.1.0 and that your param files are the ones off GitHub?

**Comment by Christianhg10** [comment]
Your are right. The problem was the version. The reason was because since yesterday I only could download the 2.0.0 rhino model version.  Now I can download in 2.1.0 version. Thanks for the support.
