### ISSUE TITLE
Picovoice Issue: TypeError: --init--() got an unexpected keyword argument 'access_key' - original issue (#287) is closed.

### ISSUE THREAD

**Issue by Hermesfrank** [Picovoice/picovoice#289]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Actual behaviour
See original issue...now I get an error saying it cannot find the .ppn file...I see now that the resources folders have added "@blah.blah" to their names - do I need to include that in my command, or are those just references?

### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced independently.)

**Comment by ksyeo1010** [comment]
I suggest you try to get the pip demo package instead:
```python
pip3 install pvrespeakerdemo
picovoice_respeaker_demo --access_key ${your_access_key}
```

if you would really like to run it via the github repository, please follow the following instructions:

1. in `/demo/respeaker` directory run:
```python
python3 setup.py sdist bdist_wheel
```
2. open `/demo/respeaker/pvrespeakerdemo/picovoice_demo.py` and in line 22 change `from .apa102 import APA102` to `from apa102 import APA102` without the dot.
3. now in the directory `/demo/respeaker/pvrespeakerdemo`, run:
```python
python3 picovoice_demo.py --access_key ${your_access_key}
```

**Comment by Hermesfrank** [comment]
Kwangsoo,
    
    Yes, I had already run successfully the pip demo package following
    the guide on the Respeaker site...
    
    With using the github repo I was just trying to become more
    practiced/familiar with the process/protocol before attempting my
    own simple sketch...I think I will just plunge...
    
    Thanks, Frank
    
    On 1/21/2022 1:38 PM, Kwangsoo Yeo
      wrote:
    
    
      
      I suggest you try to get the pip demo package
        instead:
      
        pip3 install pvrespeakerdemo
picovoice_respeaker_demo --access_key ${your_access_key}
      
      if you would really like to run it via the github
        repository, please follow the following instructions:
      
        in /demo/respeaker directory run:
      
      
        python3 setup.py sdist bdist_wheel
      
      
        open /demo/respeaker/pvrespeakerdemo/picovoice_demo.py
          and in line 22 change from .apa102 import APA102
          to from apa102 import APA102 without the dot.
        now in the directory /demo/respeaker/pvrespeakerdemo,
          run:
      
      
        python3 picovoice_demo.py --access_key ${your_access_key}
      
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Picovoice/picovoice/issues/289#issuecomment-1018883120",
"url": "https://github.com/Picovoice/picovoice/issues/289#issuecomment-1018883120",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
