### ISSUE TITLE
Syntax errors in handle of simple test sketch...

### ISSUE THREAD

**Issue by Hermesfrank** [Picovoice/picovoice#290]
### What is the URL of the doc?
https://github.com/Picovoice/picovoice#python-demos

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
I created the following based upon the documentation just as a preliminary test of my understanding of the Picovoice requirements...

from picovoice import Picovoice

def wake_word_callback():
    print ("wake word callback")
    pass

def inference_callback(inference):
    if inference.is_understood:
        intent = inference.intent
        slots = inference.slots
        
        # take action based on intent and slot values
        print ("inference callback")
        
    else:
        # unsupported command
        print("unsupport inference callback")
        pass

handle = Picovoice(
    access_key=XkufTA/RMMGkOPPPPPPjCTeQBvSRGcS9jY7Ci+hoyv9N4lWSisQpbQ==,
    keyword_path=resources/porcupine/resources/keyword_files/raspberry-pi/porcupine_raspberry-pi.ppn,
    wake_word_callback=wake_word_callback,
    context_path=resources/rhino/resources/contexts/raspberry-pi/smart_lighting_raspberry-pi.rhn,
    inference_callback=inference_callback)
    
def get_next_audio_frame():
    pass

while True:
    audio_frame = get_next_audio_frame()
    handle.process(audio_frame)

handle.delete()

************
When I run the script, I get snytax errors...initially I got a caret at the ending comma of the access_key line - I assume is is because of the ending == signs that are a part of my access key (I changed some of the characters in the key for security)...
When I put quotes around the key, the error goes away, but I suspect that I will get an access key error if I ever get it running...I tried to get a different access key, but the console would only allow one, and I cannot find how to delete existing one and create another...
Without that error, the next error that comes up is one telling me that I cannot use the = expression in the keyword_path line - it suggests I might want to try == ...
Can you look at code and suggest fix(es)?
Thanks, Frank

**Comment by kenarsa** [comment]
You do need to use `''` or `""` around string literals in Python. You can either wrap AccessKey. If you are new to the language I do suggest a quick tutorial or syntax cheat sheet.

**Comment by Hermesfrank** [comment]
Sorry for my ignorance...working on it...thanks for your input...
    
    On 1/22/2022 9:02 AM, Alireza Kenarsari
      wrote:
    
    
      
      You do need to use '' or ""
        around string literals in Python. You can either wrap AccessKey.
        If you are new to the language I do suggest a quick tutorial or
        syntax cheat sheet.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Picovoice/picovoice/issues/290#issuecomment-1019309644",
"url": "https://github.com/Picovoice/picovoice/issues/290#issuecomment-1019309644",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
