### ISSUE TITLE
Rhino Console Error Message

### ISSUE THREAD

**Issue by rickmini** [Picovoice/picovoice#291]
I am on a 3rd iteration of my .rhn context using the Rhino Console. I was able to save,train,export and use in my code on previous iterations.
After adding a few more changes, it now will not create the context.
It saves the file ok but now it tells me "Error training context" with no other message or information as to why
I tried to remove some slots etc, in case there was some sort of limit
Are there limits? Why would it save without errors? Why doesnt it tell my why it cant train?

update:
i started deleting the last intents that i added, until it worked. so it works now, but the issue remains, how do i know my error. The intents i deleted were 'Avatar' and changed stop from [stop,cancel]  to 2 seperate expressions: stop and cancel

**Comment by kenarsa** [comment]
Can you please share the context that doesn't work? You can export it as YAML. We can look into it and see if there is something obvious. I don't think it's a limit but rather a bug or lack of frontend check before letting you submit it.

**Comment by rickmini** [comment]
Thanks for the quick response. I removed a lot of my additions but not all,
and got it to work, unfortunately i dont have the yaml to the one that
didnt work.  I will try to add some of what i did slowly, and see if i can
get the error and then send you the yaml, but it wont be for a week or so.

I am amazed at how well your system performs. Im using it to control an AI
robot which is taxing an intel i7, and i have your system running in a
thread, that doesnt miss a beat.

I do have one more bit of feedback. Today when i got a version to work, it
threw an exception in my code. Telling me that i had an error with my
version. It took me a few hours to figure this out. It turns out that
the console named my rhino file with a 2_1 in the filename:
Robot_en_windows_v2_1_0, and i guess my pico library was 2.0, but that
wasnt clear. I use pycharm so i updated picovoice in my virtual environment
and it worked again. I have no problem with updates,but just a
suggestion,that you could have a popup that explained the new version and
advised accordingly

Thank you
Rick Minicucci

**Comment by kenarsa** [comment]
awesome. thanks for the kind words. agreed with the version mismatch. I keep this issue open and await your YAML context that breaks the console. it will help us make a better product for you. thanks!

**Comment by rickmini** [comment]
i have added back the other intents and slots that previously caused the error, but now everything works without the blank error message. You can close the issue, and if I encounter the error again, as i will be adding more intents, I will save the yaml and post a new issue. Thanks
