### ISSUE TITLE
'NoneType' has no len()...

### ISSUE THREAD

**Issue by Hermesfrank** [Picovoice/picovoice#292]
### What is the URL of the doc?
https://github.com/Picovoice/picovoice#python-demos

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
When I run this code based upon the doc, I get error following...
`from picovoice import Picovoice

access_key="XkufTA/RMMGkOLmN......eQBvSRGcS9jY7Ci+hoyv9N4lWSisQpbQ=="
keyword_path="resources/porcupine/resources/keyword_files/raspberry-pi/porcupine_raspberry-pi.ppn"

def wake_word_callback():
    pass

context_path="resources/rhino/resources/contexts/raspberry-pi/smart_lighting_raspberry-pi.rhn"

def inference_callback(inference):
    print(inference.is_understood)
    print(inference.intent)
    print(inference.slots)
        
    # take action based on intent and slot values

handle = Picovoice(
    access_key=access_key,
    keyword_path=keyword_path,
    wake_word_callback=wake_word_callback,
    context_path=context_path,
    inference_callback=inference_callback)
    
def get_next_audio_frame():
    pass

while True:
    handle.process(get_next_audio_frame())

handle.delete()`

Error:
Traceback (most recent call last):
  File "/home/pi/picovoice/bioloid_motions_initial_1.py", line 30, in <module>
    handle.process(get_next_audio_frame())
  File "/home/pi/.local/lib/python3.9/site-packages/picovoice/picovoice.py", line 233, in process
    if len(pcm) != self.frame_length:
TypeError: object of type 'NoneType' has no len()

**Comment by kenarsa** [comment]
in Python, `pass` essentially means this is a stub and you need to implement the function.
