### ISSUE TITLE
Picovoice Porcupine: unable to find base64 file for trained custom wake word

### ISSUE THREAD

**Issue by thiyaga05** [Picovoice/picovoice#299]
### What is the URL of the doc?
https://www.npmjs.com/package/@picovoice/porcupine-web-angular

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
The downloaded zip file from picovoice console has only ppn file for trained custom wakeword. The documentation below mentioned that it will also have a _b64.txt file, but it is missing. Please let me know where we can get the base64 file for the trained custom wakeword. 

![image](https://user-images.githubusercontent.com/95863958/152297084-f0687d99-03f1-46ff-be28-259058c65f54.png)

**Comment by kenarsa** [comment]
what is the `platform` you are setting? Can you provide the list of file names in the `zip` please?

**Comment by thiyaga05** [comment]
Hi Kenarsa, thanks for the reply.

We are using browser based web application built in Angular. Please find the screenshot of content of the zip file. 

 There are 2 files  : 1) .PPN file  and 2) LICENSE.txt file. 

We are looking for the base64 file.

![image (1)](https://user-images.githubusercontent.com/95863958/152725991-b26e637d-2780-4016-b1e4-079e59c993f3.png)

**Comment by kenarsa** [comment]
got it! You are picking `Windows` as the platform which is incorrect as you want to build for the web. You should pick `WebAssembly`
