### ISSUE TITLE
32F746GDISCOVERY support

### ISSUE THREAD

**Issue by strogg1987** [Picovoice/picovoice#303]
**Is your feature request related to a problem?**
32F746GDISCOVERY is a popular and inexpensive board that has two MEMS microphones and audio codec, as well as network support. Using this board and your platform will allow you to quickly build inexpensive devices

**Describe the solution you'd like**
Supporting 32F746GDISCOVERY

**Comment by kenarsa** [comment]
Thanks for bringing this up. Let's keep it open to see if we get significant traction on it. ST produces a large number of MCUs and it is also not the only player in the MCU market. It is impossible to support all of them.

**Comment by kenarsa** [comment]
doesn't seem like many people are asking for this after keeping the issue open for 2 weeks. if this is a commercial application reach out to Picovoice sales team and they might be able to help via commercial engagement.
