### ISSUE TITLE
Picovoice Issue:  Cant't use mic device in container

### ISSUE THREAD

**Issue by m986883511** [Picovoice/picovoice#308]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.
yes

`
root@58b2fddf55cf:/wake/python# python3 porcupine_demo_mic.py --access_key  'D0kBJXPA5OiyJuQPRTM########Dvfyi1HT6jOBaQ5K0w==' --keyword_paths /wake/Hey-Adam_en_linux_v2_1_0.ppn --audio_device_index 1
ALSA lib pcm_dsnoop.c:641:(snd_pcm_dsnoop_open) unable to open slave
Traceback (most recent call last):
  File "porcupine_demo_mic.py", line 230, in <module>
    main()
  File "porcupine_demo_mic.py", line 219, in main
    PorcupineDemo(
  File "porcupine_demo_mic.py", line 90, in run
    recorder = PvRecorder(device_index=self._input_device_index, frame_length=porcupine.frame_length)
  File "/usr/local/lib/python3.8/dist-packages/pvrecorder/pvrecorder.py", line 78, in __init__
    raise self._PVRECORDER_STATUS_TO_EXCEPTION[status]("Failed to initialize pv_recorder.")
RuntimeError: Failed to initialize pv_recorder.
root@58b2fddf55cf:/wake/python# python3 porcupine_demo_mic.py --access_key  'D0kBJXPA5OiyJuQPR#########yi1HT6jOBaQ5K0w==' --show_audio_devices
index: 0, device name: Discard all samples (playback) or generate zero samples (capture)
index: 1, device name: HD Pro Webcam C920, USB Audio
root@58b2fddf55cf:/wake/python# 
`

### Expected behaviour
USB Audio devices should work

### Actual behaviour
But have a exception=(RuntimeError: Failed to initialize pv_recorder.)

### Steps to reproduce the behaviour
my dockerfile:
`
FROM ubuntu:20.04

COPY docker/ubuntu20.04-sources.list /etc/apt/sources.list
RUN apt update
RUN apt install wget file curl vim procps python3 python3-pip -y
RUN apt install alsa-base alsa-utils -y

RUN pip3 install numpy -i https://pypi.tuna.tsinghua.edu.cn/simple/
RUN pip3 install picovoice -i https://pypi.tuna.tsinghua.edu.cn/simple/
RUN pip3 install picovoicedemo -i https://pypi.tuna.tsinghua.edu.cn/simple/
`

(Include enough details so that the issue can be reproduced independently.)

**Comment by kenarsa** [comment]
@m986883511 you just copied your `AccessKey` here and hence everyone can now use it. You are supposed to keep this private! The issue is out of the scope of Picovoice. You need to get your microphone working from within docker and once you do if there are remaining issues we can look into it.
