### ISSUE TITLE
Picovoice Documentation Issue (/docs/quick-start/picovoice-python/)

### ISSUE THREAD

**Issue by rrzadzki** [Picovoice/picovoice#309]
### What is the URL of the doc?

https://picovoice.ai/docs/quick-start/picovoice-python/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)

`import picovoce` should be `import picovoice`

**Comment by mrrostam** [comment]
Thanks for reporting this. It's fixed now
