### ISSUE TITLE
Picovoice Documentation Issue (/docs/quick-start/leopard-nodejs/)

### ISSUE THREAD

**Issue by ristew** [Picovoice/picovoice#315]
### What is the URL of the doc?
https://picovoice.ai/docs/quick-start/leopard-nodejs/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
Instead of `leopard_demo_file`, the node executable should be `leopard-file-demo` or `leopard-mic-demo`

**Comment by ErisMik** [comment]
Fixed, thank you for the report!
