### ISSUE TITLE
Picovoice Console Issue: Picovoice goes multilingual demo Page

### ISSUE THREAD

**Issue by JDHH83** [Picovoice/picovoice#32]
### Expected behaviour

If I want German Language the keyword should be "Deutsch"

### Actual behaviour

Currently it's listening for "Deutsche" which is not correct in this context.

<img width="362" alt="Screenshot 2021-02-09 at 15 11 25" src="https://user-images.githubusercontent.com/18344789/107375727-58857e80-6ae9-11eb-813d-b5c71b4131ac.png">

### Steps to reproduce the behaviour

Go to https://picovoice.ai/blog/picovoice-goes-multilingual/

enable mic access, see possible commands (As screenshotted above). It's not only a typo on the page it's actually only listening for "Deutsche" and not "Deutsch"

(Include enough details so that the issue can be reproduced independently.)

**Comment by kenarsa** [comment]
You are absolutely right! Thank you. Fixed. If you refresh the page it should be correct now.
