### ISSUE TITLE
Errors when trying android:2.1.0

### ISSUE THREAD

**Issue by RezaS** [Picovoice/picovoice#320]
I have now switched from Android version 2.0.1 to 2.1.0:

```
implementation 'ai.picovoice:porcupine-android:2.1.0'
implementation 'ai.picovoice:picovoice-android:2.1.0'
```
I now get these errors:

> I/PICOVOICE: [ERROR] keyword file belongs to a different version of the library. keyword file is '2.0.0' while the library is '2.1.0'.
> I/PICOVOICE: [ERROR] loading keyword file at '/data/user/0/ch.yourclick.ki/files/Ki_de_android_v2_0_0.ppn' failed with 'INVALID_ARGUMENT'

What is a "keyword file"? Is that the file for the "wake word"?
And what is wrong with the second error?

**Comment by kenarsa** [comment]
Please make an effort to find the solution via docs in the future. I think this should have been solvable via docs. Nevertheless, the keyword file is the file with the `PPN` extension. You either use one of the existing ones in the repo or generate one via Console. The engine and this file should be the same version. You need to update your keyword file to V2.1 as well. I hope it helps.
