### ISSUE TITLE
Picovoice Console Issue: Duplicate when changing letter to upper-/lower-case

### ISSUE THREAD

**Issue by SoPrecht** [Picovoice/picovoice#322]
When I change a letter from lower to upper case or vice versa the console says it is a duplicate.

### Expected behaviour
Changing a letter should make no difference for the expression

### Actual behaviour
Throws an Error that the expression is a duplicate of itself.

### Steps to reproduce the behaviour
Change a letter to upper/lower-case

![BugReport](https://user-images.githubusercontent.com/102176275/159761126-c9804c25-ed6d-41ce-87f9-cfc5e56658e9.PNG)
![BugReport1](https://user-images.githubusercontent.com/102176275/159761139-2f80563c-9a16-49fa-991f-075f623855e6.PNG)

**Comment by laves** [comment]
@SoPrecht - thanks for the report. This should be fixed now.
