### ISSUE TITLE
Picovoice Console Enhancement: Rearrange Intents

### ISSUE THREAD

**Issue by SoPrecht** [Picovoice/picovoice#323]
**Is your feature request related to a problem? Please describe.**
Quality of Life improvement. It would be nice to be able to rearrangeintents by drag and drop or a different way. Especially for bigger Projects where you use name prefixes to keep it organised, it would be nice to have this if you forgot an intent and put in in later.

**Describe the solution you'd like**
Beeing able to rearrangeIntents, Slots and Makros with drag and drop or with arrows.

**Describe alternatives you've considered**
It is possible by exporting it as a YAML, rearrange it there and reimport this file. But it would be a nice Quality of Life change.
A other approych could be sorting intents by name.

**Comment by kenarsa** [comment]
can you elaborate a bit more with examples? I am interested to learn more

**Comment by SoPrecht** [comment]
![PicovoiceElaborate](https://user-images.githubusercontent.com/102176275/159959157-4fd74572-502f-4c2b-86d6-a503f6847b8a.PNG)

This is a part of my current Project. I use a Prefix to group them and get an overview what it is for. My Project is a Game i will use for a research study. The Speech to Intent is used for the dialogues and some intents are only availible when certain quests are active.
Marked in red you can see an intent with the prefix GP(general phrase) i use in more than one context. After creating that i created more with prefix DS and I would like move the GP to the bottom, so all DS's are together.
As I said I can achieve it by a YAML File but would be a nice quality of life thing.

Hope this makes it more clear and I appreciate your quick responses and work.

**Comment by kenarsa** [comment]
thanks. it does clarify the request. good idea. not something I can commit to right away. a quick workaround is to export in YAML and then re-order and import again and that should do it.
