### ISSUE TITLE
Picovoice Console Issue: 

### ISSUE THREAD

**Issue by carisbrookes** [Picovoice/picovoice#330]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### pvporcupine licence has stopped updating on my raspberry pi4 despite working over last 2 months:
in order to report the issue I have paired back to the demo code from (https://pypi.org/project/pvporcupine/)

import pvporcupine
access_key = "my_access_key" # AccessKey obtained from Picovoice Console (https://console.picovoice.ai/)
handle = pvporcupine.create(access_key=access_key, keywords=['picovoice'])

### Actual behaviour
 [WARN] License is nearing expiry. Requesting renewal from activation server...
 [WARN] Unable to renew license.
-------programme stops at this point-----------

similar code has been working extremely well in my 'home virtuall assistant' project over the past few months and I thought the licence was updating.
The rpi is connected to the internet and the connection works fine with my other apps and code.
I have reinstalled rpi os  a number of times recently using an ssd in place of an sd card to improve speed. 
I wonder if the updated os and drive are seen as a different device thus appearing to breach the limit?  

console shows:
Device Limits 3 of 3
Devices used for Porcupine, Rhino, Cobra past 30 days  
Usage Limits 393 of 360000
Seconds used for Cheetah, Leopard and Octopus past 30 days

I only tried cheetah to see if it would be a better bet but it seems too complicated for my use.

### Steps to reproduce the behaviour
above simple demo code clearly confirms the same behaviour as my project code.

(Include enough details so that the issue can be reproduced independently.

**Comment by laves** [comment]
@carisbrookes - unfortunately, as you've guessed, reinstalling the OS would cause our licensing system to detect it as a new active user of the software. You'll have to wait until one of your license slots opens up again (30 days after first registration) before your device can be registered again. We are considering changing this behaviour for smaller, Linux-based devices, but can't commit to a timeline on it.

**Comment by drinkspiller** [comment]
Dang. Same issue — had to reinstall the OS on my rpi and now I am unable to use my access token. It would be nice to have a mechanism to "deactivate all registered devices" for an AccessKey.
