### ISSUE TITLE
Picovoice Console Issue: Adding new macro for a German context

### ISSUE THREAD

**Issue by dnknth** [Picovoice/picovoice#334]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour

* Ability to Add a new macro in the console and add words to it

### Actual behaviour

* Can enter the macro name, but cannot reach the word list

### Steps to reproduce the behaviour

* Create a new context for German 
* Add a new intent X
* Add a new macro Y

(Include enough details so that the issue can be reproduced independently.)

**Comment by ErisMik** [comment]
Thanks for the report, we've reproduced the issue and we are working to resolve it.

**Comment by ErisMik** [comment]
Issue has been resolved :) Please feel free to open another issue if you run into any additional problems.
