### ISSUE TITLE
Picovoice Console Issue: Email validation pattern is wrong

### ISSUE THREAD

**Issue by s-ol** [Picovoice/picovoice#335]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
Using the `+` symbol in emails is allowed as per the email standards.

### Actual behaviour
The `+` symbol is not allowed in emails. There are probably other symbols that are wrongly blacklisted also.

### Steps to reproduce the behaviour
Attempt to sign up with an email address that includes the `+` symbol.

**Comment by kenarsa** [comment]
anything after `+` is essentially ignored and passed to the same inbox. what's the concern/use case here?

**Comment by s-ol** [comment]
@kenarsa No, that is a specific implementation of the gmail mail server. Also, the point of that feature in Gmail is exavtly that that string **should be preserved** by services, so that the user can tell where an email came from.

**Comment by kenarsa** [comment]
does your original email address have `+` in it? are you trying to add `+` to it to route it?

**Comment by kenarsa** [comment]
OK. This makes sense. We will work on this and get this fixed in the next couple of weeks
