### ISSUE TITLE
Picovoice Console Issue: Create account 

### ISSUE THREAD

**Issue by yash-chouhanSys** [Picovoice/picovoice#337]
i didn't get any confirmation code on my gmail account after so many tries

**Comment by kenarsa** [comment]
have you looked into spam/promotion/etc folders? Are you sure there was no typo when you entered your email address?

**Comment by yash-chouhanSys** [comment]
> have you looked into spam/promotion/etc folders? Are you sure there was no typo when you entered your email address?


yes , i checked , there was not any otp message
