### ISSUE TITLE
Picovoice Documentation Issue (/docs/api/rhino-python/)

### ISSUE THREAD

**Issue by dnknth** [Picovoice/picovoice#338]
### What is the URL of the doc?

[Rhino - Python API](https://picovoice.ai/docs/api/rhino-python/)

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)

> [pvrhino.Rhino.frame_length](https://github.com/Picovoice/rhino/blob/master/binding/python/rhino.py)
> `self.frame_length: int`
> The number of audio samples per frame that Rhino accepts.

As per docs, Rhino accepts single channel audio with 16 bit sample with and 16k samples per second. On Mac OS (Intel), `pvrhino.Rhino.frame_length == 512`. However, if passing in 512 frames as the docs suggest, I get the error:

    ValueError: Invalid frame length. expected 512 but received 1024

It does work when using 256 frames, which is the `frame_rate` divided by the audio frame width in bytes.
So it seems that `pvrhino.Rhino.frame_length` is the expected number of *bytes*, and not the expected number of *frames*.
Maybe the docs should state this?

**Comment by kenarsa** [comment]
Rhino does need `512` audio samples and hence `1024` bytes. A good place to look into is the unit test for sample usage or the file demo.

**Comment by dnknth** [comment]
Kindly elaborate how this fits together with the error that I get when feeding in 512 samples and the fact that it works when using 256 samples.

**Comment by kenarsa** [comment]
no idea. if you post a sample code here I might be able to help

**Comment by dnknth** [comment]
Sure. Sample code attached (with `.txt` suffix for GitHub). Line 23 is where I got confused. According to the docs, `rhino.frame_length` should work, but here it is `rhino.frame_length // AUDIO_PARAMS.sampwidth`.

[action-sr-pv.py.txt](https://github.com/Picovoice/picovoice/files/8500598/action-sr-pv.py.txt)

**Comment by kenarsa** [comment]
can you try to use stadnard [wave](https://docs.python.org/3/library/wave.html) package? then I can help. I don't know the libraries you are using

**Comment by dnknth** [comment]
tomorrow, too late over here. Happy Easter, by the way.

**Comment by dnknth** [comment]
Test code using only standard libs: [action-sr-pv-wav.py](https://github.com/Picovoice/picovoice/files/8501574/action-sr-pv-wav.py.txt)

Behaviour is identical, if line 22 is changed to match the docs, I get:

> ValueError: Invalid frame length. expected 512 but received 1024

**Comment by kenarsa** [comment]
the reason is you are returning `bytes` but the API expects an array of integers (e.g. `np.array` or `List`). does it make sense?

**Comment by dnknth** [comment]
Yes, feeding in an `array` of 16 bit samples works as expected. Thank you for the clarification!
