### ISSUE TITLE
ai.picovoice.rhino.RhinoActivationException: Initialization failed. with Java SDK

### ISSUE THREAD

**Issue by MineKing9534** [Picovoice/picovoice#339]
I'm using the Java SDK on a Linux Fedora 34 system. With my own project as well with the MicDemo I'm only getting
`ai.picovoice.rhino.RhinoActivationException: Initialization failed.` on start and with the demo also 
```
[INFO] Porcupine model path : '/tmp/porcupine-mic-demo/porcupine/lib/common/porcupine_params.pv'
 [INFO] Porcupine keyword path [0] : '/tmp/porcupine-mic-demo/porcupine/resources/keyword_files/linux/porcupine_linux.ppn'
 [INFO] Porcupine sensitivity [0] : 0,50
```

**Comment by kenarsa** [comment]
do you have internet connectivity?

**Comment by MineKing9534** [comment]
Yes, I'm running this locally on my laptop where I'm also writing this comment on

**Comment by kenarsa** [comment]
OK. is there anything special about your system? e.g. is this a  VM? are you behind a firewall? is your home folder available and do you have read/write permission?

**Comment by MineKing9534** [comment]
My system is pretty normal, it's a default fedora 34 installation (already tried on a different machine with fedora 35). I also tried to run it with root but still with the same behavior

**Comment by kenarsa** [comment]
Is there a way for you to try it out on Ubuntu? I just tried to reproduce on Ubuntu and couldn't. If you can give it a try I can help faster.

**Comment by MineKing9534** [comment]
I only have a ubuntu server where i don't have a valid ssh key for on my laptop :/

**Comment by MineKing9534** [comment]
But I think i tested it earlier like two week or so ago and it didn't work

**Comment by kenarsa** [comment]
OK. I will ask another dev to also try it on their machine. We do need to be able to recreate this in order to help as the first step.

**Comment by MineKing9534** [comment]
OK, thank you :)
Later I'm comming back home and can try it on my ubuntu server but as already mentioned i already tried it there a few weeks ago and it didn't work.

**Comment by ogluisg** [comment]
I am also having this issue with the react native SDK, it was working perfectly fine and then next day I am receiving this error.

I am well within my device & usage limits.

`PorcupineInvalidArgumentError: Porcupine init failed`

**Comment by kenarsa** [comment]
@ogluisg this is a totally different error! if you need help open a new issue with full instructions on how to recreate

**Comment by MineKing9534** [comment]
Tested on my ubuntu server again - didn't work, same error as on fedora machine

**Comment by ogluisg** [comment]
@kenarsa Can you provide me an email to reach out to support? I can't find anything within the picovoice console.

**Comment by kenarsa** [comment]
@ogluisg if you are an enterprise customer you should have an email for your account manager and they are your point of contact. aside from that, you can open a github issue we don't have email support for community users.

**Comment by ksyeo1010** [comment]
@MineKing9534 I tried reproducing it on my linux machine as well and it works fine. Can you provide the full command you used to test?

**Comment by MineKing9534** [comment]
`java -jar rhino-mic-demo.jar -a <key> -context context.rhn`
This is what i tried on ubuntu and fedora with the demo. But it also doesn't work with my own java project

**Comment by ksyeo1010** [comment]
In the directory: `demo/java/builds/libs` can you try running `java -jar rhino-mic-demo.jar -a <key> -context ../../../../resources/contexts/linux/smart_lighting_linux.rhn` and see if this works. Also appreciate if you can copy paste your output including the error.

**Comment by MineKing9534** [comment]
Same problem with buit-in context
```
 [INFO] Rhino model path : '/tmp/rhino-mic-demo/rhino/lib/common/rhino_params.pv'
 [INFO] Rhino context path : '../../../../resources/contexts/linux/smart_lighting_linux.rhn'
ai.picovoice.rhino.RhinoActivationException: Initialization failed.
```

**Comment by ksyeo1010** [comment]
Can you email me your access key at `kyeo@picovoice.ai` so that I can take a look at your issue on our side. thanks.

**Comment by ksyeo1010** [comment]
Our logs show your access key is working fine. Can you tell me/try the following:
1. What version of rhino are you using? Can you make sure you are in latest?
2. Do you have a `~/.pv/` or `/${HOME_DIRECTORY}/.pv/` directory with files in it?

**Comment by MineKing9534** [comment]
My Picovoice Version is 
```xml
<dependency>
	<groupId>ai.picovoice</groupId>
	<artifactId>picovoice-java</artifactId>
	<version>2.1.1</version>
</dependency>
```
And my home directory contains `.pv` but this folder is empty (On my fedora workstation as well as on my ubuntu server)

**Comment by MineKing9534** [comment]
When i delete this directory its getting recreated when i run picovoice but still without any files in it

**Comment by ksyeo1010** [comment]
Are you running on a 64bit os?

**Comment by MineKing9534** [comment]
yes

**Comment by MineKing9534** [comment]
I'm sure that i have a 64bit CPU and that I'm running a 64bit System, but how can I get the EfI version?
```
$ uname -m
x86_64
```

**Comment by MineKing9534** [comment]
Command output
```
$ cat /sys/firmware/efi/fw_platform_size
64
```

**Comment by ksyeo1010** [comment]
I sent you an email just now, can you try it out and give us the output you are getting? Thanks.

**Comment by MineKing9534** [comment]
Same problem with this lib
```
$ java -jar rhino-mic-demo.jar -a <key> -c context.rhn -l /home/<username>/Downloads/libpv_rhino_jni.so
 [INFO] Rhino model path : '/tmp/rhino-mic-demo/rhino/lib/common/rhino_params.pv'
 [INFO] Rhino context path : 'context.rhn'
ai.picovoice.rhino.RhinoActivationException: Initialization failed.
```
Also thanks for giving so much effort in helping me :)

**Comment by ksyeo1010** [comment]
I sent you a new once, can you try again? thanks!

**Comment by MineKing9534** [comment]
```
 [INFO] Rhino model path : '/tmp/rhino-mic-demo/rhino/lib/common/rhino_params.pv'
 [INFO] Rhino context path : '../../../../resources/contexts/linux/smart_lighting_linux.rhn'
[ERROR] Failed to deserialize: ACTIVATION_ERROR

ai.picovoice.rhino.RhinoActivationException: Initialization failed.
```

**Comment by ksyeo1010** [comment]
Thanks, I sent you a new build which I believe will help us pinpoint your issue.

**Comment by MineKing9534** [comment]
The result contains a lot of ids so i sent you the result via email

**Comment by ksyeo1010** [comment]
I sent you a new email and would like to keep discussing over email.

**Comment by ksyeo1010** [comment]
Issue resolved via email.
