### ISSUE TITLE
Picovoice Documentation Issue

### ISSUE THREAD

**Issue by francis-idada-biz** [Picovoice/picovoice#340]
### What is the URL of the doc?

Sorry I might just be slow but from the main page of picovoice.ai, there is no link to a document.

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)

I wonder what the pronunciation key is used ? Is it IPA ? if it is I see some IPA symbols are missing like : [ə](https://en.wiktionary.org/wiki/%C9%99), [ɐ](https://en.wiktionary.org/wiki/%C9%90).

Thank you.

**Comment by kenarsa** [comment]
Are you referring to custom pronunciations for Cheetah/Leopard?

**Comment by francis-idada-biz** [comment]
yes, using the IPA table one can get the pronunciation but using wikitionary there are characters not in cheetah/Leopard.

For instance: sterile, ipa pronunciation -> stɛɹəl, but the second character before the last is absent.

i will attach screen shots for your reference.

![image](https://user-images.githubusercontent.com/95387002/166147956-1ab26a9d-c1be-4680-b752-92a3f0809679.png)

this charts shows all the ipa symbols, but the ones listed are only:

<img width="1266" alt="Screen Shot 2022-05-01 at 7 20 09 AM" src="https://user-images.githubusercontent.com/95387002/166148023-28c53a27-ae7b-4910-8134-2929efda20f4.png">

i wonder if you have an abbreviated usage.

**Comment by kenarsa** [comment]
Your guess is correct. We use an abbreviated version of IPA for English.

**Comment by francis-idada-biz** [comment]
thank you, i will close now.
