### ISSUE TITLE
Picovoice Issue: Accuracy and how models are trained ... pv cheetah

### ISSUE THREAD

**Issue by francis-idada-biz** [Picovoice/picovoice#343]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour

when i list custom words the accuracy should improve.

### Actual behaviour

accuracy declines :

**Original text:**

The lesion was circumscribed in an ellipse and the
subcutaneous tissue was taken down with cautery to expose the anterior fascia.
With the anterior fascia exposed, the fistulous tract was identified and
mobilized free from the fascia.  It was then stapled free and sent off the table. This was
done with a GIA 55. The anterior fascia was then closed with interrupted 2-0
Vicryl sutures. Prior to doing this, the staple line was also oversewn with 2-
0 Vicryl sutures. The wound was irrigated with normal saline. The subcutaneous
tissue was loosely closed with 3-0 Vicryl suture. The skin was loosely closed
with 4-0 Monocryl suture. Sterile dressings were applied.

The child did appear to have drink something prior to being intubated and did
have a significant episode of clear emesis. We will be watching her overnight
to make sure there is no problem with aspiration. In addition, we will watch
her overnight and keep her n.p.o. while she was doing well, we will start a
diet on her tomorrow.

**transcription without custom words :**

THE ALEUTIAN WAS CIRCUMSCRIBED IN AN ELLIPSE AND THE SUBCUTANEOUS TISSUE WAS TAKING DOWN WITH CONTRARY TO EXPOSE THE INTERIOR FAR SHEER NEW LINE WITH THE ANTERIOR FASHION EXPOSED CALMER THE FACELESS TRACK WAS IDENTIFIED AND MOBILIZED FREE FROM THE FASHION PERIOD IT WAS THEN STABLED FREE AND SCENT OF THE TABLE PERIOD THIS WAS DONE WITH A GUY A FIFTY FIVE PERIOD THE ANTERIOR FACIAL WAS THEN CLOSED WITH INTERRUPTED TO VIRAL SUITORS PERIOD PROUD TO DO IN THIS THE STABLE LINE WAS ALSO OVERSEWN WITH TO OR VEHICLE SUITORS PERIOD THE WOUND WAS IRRIGATED WITH NORMAL SELLING THE SUBCUTANEOUS TISSUE WAS LOOSELY CLOSED WITH THREE OVER CROW SUITORS PERIOD THE SKIN WAS LOOSELY GLOWED WITH FOR ALL WHEN A GROSS SUITORS PERIOD STARE ARE DRESSES WERE APPLIED PERIOD NEW PARAGRAPH THE CHILD DID APPEAR TO HAVE DARUG SOMETHING PRIOR TO BEEN INTUBATED AND DID HAVE A SIGNIFICANT EPISODE OF CLAIM AS ITS PERIOD WE WILL BE WATCHING HER OVERNIGHT TO MAKE SURE THERE IS NO PROBLEM WITH ASPIRATION PERIOD IN ADDITION CALMER WE WILL WATCH HER OVERNIGHT AND KEEP HER NYPL WHILE SHE IS DOING WELL COMER BUT WILL START A DIET OF HER TOMORROW PERIOD

**transcription with custom words:**
THE RELATION WAS THE CONSCRIBED HER LIPS AND THE SUCCESSIVITY SHE WAS TAKING DOWN THE CONTRARY TO EXPOSE THE INTERIOR BISHOP WITH THE AND SERIOUSLY SHAPED STONE THE KRISTELLER STRIKE WAS IDENTIFIED AND MOBILIZED FREE FROM THE SESSION IT WAS THEN STABLE FREE AND SENT ON THE TABLE IT THIS WAS DONE WITH A TO BUY A SEED THE SIDE THE UNTIL THE FISHER WAS THEN CLOSED TO IN INTERRUPT AND PEOPLE LIKE RESEARCHERS BRIAN TO DOING THIS THE STATE OF LIFE WAS ALSO A MUSCLE WITH TO HIM MICHAEL SUITORS THE WOUND WAS IRRITATED WITH MARBLE SAILING THE SUB PIGEON OF TISSUE WAS LOOSELY CLOSED WITH GREAT AND BAIKAL CERTAIN THE SKIN WAS MAINLY CLOSES FOR MORE VICRYL AN OPEN SECRET STERILE DRESSES WERE APPLIED THE CHILD SLID UP INTO A HOT DRINK SOMETHING FIRE TO BEEN INTEGRATED AND THEY HAVE A SIGNATURE AND EPISODE OF THEIR AMISES WE WILL BE WATCHING OUT OF THE NIGHT TO MAKE SURE THERE IS NO PROBLEM WITH ASPIRATION IN ADDITION WE WILL WORK OUT OF THE MIGHT HAVE MAKE HALF AND PEOPLE WHILE SHE IS DOING WELL WE WILL START TO THE GUISE OF ANTINOUS

copy of yml file of custom words:

new:
  npo:
    - n p oʊ
  emesis:
    - ɛ m ɪ s ɪ s
  sterile:
    - s t ɛ ɹ ɑ ɪ l
    - s t ɛ ɹ e l
  monocryl:
    - m oʊ n oʊ K  ɹ i l
  four oh:
    - f oʊ ɹ oʊ
  three oh:
    - θ ɹ i oʊ
  saline:
    - s ɑ l i n
  wound:
    - w u n d
  sutures:
    - s u t ʃ ɝ
  vicryl:
    - v aɪ K  ɹ i l
  two oh:
    - t ʊ oʊ
  staple:
    - s t ɔ p l
  fistulous:
    - f i s t ʊ l oʊ s
  fascia:
    - f æ ʃ aɪ
  cautery:
    - K  ɔ t e ɹ i
  lesion:
    - l ɪ ʃ ɔ n
boost:
  - period
  - comma
  
### Steps to reproduce the behaviour

All transcriptions were from the web console on a mac book pro 2.6ghz 6 core intel 6 i7 running big sur

The first was using the built in microphone at home with minimal ambient noise and the second was using airpods in a starbucks cafe with about moderate noise level.

**QUESTIONS**

I have read through the documentation and other questions on this github forum. The docs say we don't need voice data to train models and only typing the text trains the models. My basic test for using in a medical environment does not seem to work. I had also raised an issue with the abbreviated IPA not representing all the sounds to create custom words. 

IS THERE ANY OTHER WAY TO TRAIN CUSTOM WORDS TO INCREASE ACCURACY. 

HOW DOES PICOVOICE DEAL WITH ABBREVIATIONS LIKE GIA IN THE MODEL WITHOUT TRANSCRIBING THEM AS WORDS.

HOW DOES CHEETAH DEAL WITH NUMBERS

I don't mind joining the starter tier to resolve this, but as the payment is for the whole year (about $12,000, price for enterprise not listed), I want to be sure it is possible and ensure the accuracy is acceptable for production within the predicted noise environments it would be deployed before committing that amount. 

I also have a similar issue with rhino but would open a new issue for that.

Thank you for your help.

(Include enough details so that the issue can be reproduced independently.)

**Comment by kenarsa** [comment]
This is great. Thank you. Do you think you can share the audio file with us as well so we can look into it? You can email it to `hello@picovoice.ai ` if you don't want to share it here.

I had a quick look at the pronunciations and I think there are a few mistakes. The first one I caught was:

```text
npo:
- n p oʊ
 ```

which prob should be:

```text
npo:
- ɛ n p i oʊ
 ```

Does it make sense? If I get the audio and listen I can help a bit more and give tips for custom pronunciations. I understand that our interface is lacking here and this is great feedback for us to improve UX there.

**Comment by francis-idada-biz** [comment]
Unfortunately I used the web console and didn't record the audio for the transcription for any of them.

I will rerecord it using my mac to produce a wav file recorded in 16kh and send that by email.

Thank you for your help.

**Comment by kenarsa** [comment]
Great. I keep an eye on that. A file would be much better for debugging as it allows us to reproduce and seek the rootcause. thanks.

**Comment by francis-idada-biz** [comment]
having difficulty recording an audio sample, quicktime audio records in 44k, tried stackoverflowing a python script to record using pyaudio but what appears to work for others doesn't work for me, dont know if you have every come across this answer on stackoverflow - 

https://stackoverflow.com/questions/62520952/how-to-record-audio-each-time-user-presses-a-key/62629132#62629132

any tips on recording to a mac, would be helpful.

**Comment by kenarsa** [comment]
You can use Audacity if you like. Alternatively, any of the demos on [PVRecorder](https://github.com/Picovoice/pvrecorder) would work as well.

**Comment by francis-idada-biz** [comment]
sent the audio file. thanks again.

**Comment by kenarsa** [comment]
Thank you. I did spend a bit of time on the audio. It is a medical-specific use case that heavily relies on custom vocab. Here are a few tips that I think help and I am also attaching what I started doing to serve as an example (it is not complete but you can use it as a starting point).

1- Start by adding custom vocab that you know the user will utter often to the boost list.
2- If the word does not exist, then add it to custom vocab and also boost it after.
3- You don't need to enter pronunciations for new words but if you do it will help. That being said they need to be correct. See NPO below.
4- To get the best accuracy you really need to train an LM from scratch for this use case. Nuance and Amazon have medical-specific ASRs. We can do it but then need to first understand the business opportunity first property (sales form on picovoice website would be the right channel for that).

Hope it helps.

```yaml
new:
  vicryl: []
  NPO:
    - ɛ n p i oʊ
  GIA:
    - dʒ i aɪ e
    - dʒ i aɪ ɛ
boost:
  - stapled
  - staple
  - ANTERIOR
  - fistulous
  - cautery
  - GIA
  - fascia
  - subcutaneous
  - circumscribe
  - circumscribed
  - lesion
  - period
  - comma
```
