### ISSUE TITLE
Picovoice Documentation Issue (/docs/api/porcupine-java/)

### ISSUE THREAD

**Issue by PrincipalScudwort** [Picovoice/picovoice#346]
### What is the URL of the doc?
https://picovoice.ai/docs/api/porcupine-java/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
I created a PPN file for my wakeup command and attempt to point to it using the .setKeywordPaths build method. I've tried placing the file through android studio or directly through the file explorer and I still can not initialize the Porcupine object with this file without throwing the java.io.FileNotFoundException. I used the absolute file path as directed in the docs, and tried every possible way to reference the file but it still won't be found. I copied the entire absolute path from my computer's C drive, and tried every single possible file name by shortening a single directory at at time until I reach the PPN file's name and every single time I still receive the File Not Found error. I tried every single time with and without including the .ppn extension at the end. I am not sure how to properly reference the path of the PPN file I wish to include for an android studio project. Thank you

**Comment by kenarsa** [comment]
closing as you found the solution.
