### ISSUE TITLE
Picovoice Console Issue: Cannot create aacount or reset password at website

### ISSUE THREAD

**Issue by Aephir** [Picovoice/picovoice#348]
### Expected behaviour
That I can either create account (if no account with the given email exists) or send an email reset code (if an account with the given email address does exist).

### Actual behaviour
If trying to create account, it says (making sure to copy/paste the email address to avoid any possibility of typos)
```
An account with the given email already exists.
```
<img width="330" alt="Screenshot 2022-05-12 at 20 34 06" src="https://user-images.githubusercontent.com/20152788/168145625-be6418a8-e363-46e9-8260-6c968d852aab.png">

if I try to reset password, it says:

```
Error requesting reset code: Cannot reset password for the user as there is no registered/verified email or phone_number
```

<img width="395" alt="Screenshot 2022-05-12 at 20 33 00" src="https://user-images.githubusercontent.com/20152788/168145643-eae2bb4d-56e9-4ef7-8cc0-d31e8e0ba9f4.png">

### Steps to reproduce the behaviour

I can't say, since I don't know if I already have an account. If so, it was created long ago (before I had a password manager). It could be two different ways:

1. Navigate to "https://console.picovoice.ai/login", and try to create or reset password **__with__** an account already existing under the given email address.
2. Navigate to "https://console.picovoice.ai/login", and try to create or reset password **__without__** an account already existing under the given email address.

**Comment by ErisMik** [comment]
Could you please provide the email address that you are trying to login in with? If you are uncomfortable sharing it publicly here you can email it to `hello@picovoice.ai`

**Comment by Aephir** [comment]
Sure, I have sent the email with a link to this issue.

I can log in using github, but as stated in the email, I'd prefer not having to "link" different accounts if possible.

**Comment by ErisMik** [comment]
Thanks, received. I'll take a look at get back to you when I have an update.

**Comment by ErisMik** [comment]
@Aephir It looks like your Picovoice console account was originally create using the "github login". Could you try logging in with github and see if that gets you access to your account?

**Comment by Aephir** [comment]
OK, thank for clarifying.
