### ISSUE TITLE
Picovoice Issue: Copy assets fails, because the folders are empty

### ISSUE THREAD

**Issue by netlinx2** [Picovoice/picovoice#35]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
the script should copy the assets

### Actual behaviour
Copy assets fails, because the folders are empty

### Steps to reproduce the behaviour
this is the copy process:
michael@Michaels-MacBook-Pro flutter % sh copy_assets.sh 
Copying Android demo context...
cp: ../../resources/rhino/resources/contexts/android/smart_lighting_android.rhn: No such file or directory
Copying Android demo keyword file...
cp: ../../resources/porcupine/resources/keyword_files/android/picovoice_android.ppn: No such file or directory
Copying iOS demo context...
cp: ../../resources/rhino/resources/contexts/ios/smart_lighting_ios.rhn: No such file or directory
Copying iOS demo keyword file...
cp: ../../resources/porcupine/resources/keyword_files/ios/picovoice_ios.ppn: No such file or directory

**Comment by kenarsa** [comment]
did you clone the submodules? I think you didn't. Please clone according to the doc here: https://github.com/Picovoice/picovoice#demos

**Comment by netlinx2** [comment]
your are right. it works now. many thanks!
