### ISSUE TITLE
Picovoice Console Issue: 

### ISSUE THREAD

**Issue by simonbrtrnd** [Picovoice/picovoice#369]
Hi,

I use Rhino SDK in my React Native project.

1. I create a new Rhino Speech-to-Intent context in **French** in Picovoice Console
2. I train it for **Android**
3. I download and import it in my React Native project
4. I got this error message  `RhinoInvalidArgumentError: Initialization failed`

When I test my context on the web in the Picovoice Console everything seems to work fine.
I have the same exact issue with the **German** language (I haven't try in Spanish).

I am pretty sure that the issue doesn't come from my React Native project because everything works super nicely with an **English** context 🙏

**Comment by kenarsa** [comment]
did you change the model file (`.PV`) to your language?

**Comment by simonbrtrnd** [comment]
Hi @kenarsa ,
Thanks for the quick answer. 
Indeed, I completely missed this part from de docs 😅 Everything works fine now!
Sorry for the inconvenience, have a great day 👋

**Comment by Lord3n20** [comment]
@simonbrtrnd you can close the issue if it worked out.
