### ISSUE TITLE
ESP-32 Support

### ISSUE THREAD

**Issue by aalaei** [Picovoice/picovoice#38]
---
name: ESP32 Support
about: Picovoice SDK support ESP32
title: 'ESP32 Support'
labels: enhancement
assignees: ''

---

**Is your feature request related to a problem?**
I think espressif microcontrollers are great chips. size of memory available in these microcontrollers is much higher especially by considering the cost. Supporting these microcontrollers by this great platform will definitely result in powerful IOT voice recognizer devices. (especially when  internet access isn't available for a short time)

**Solution**
Supporting these great microcontrollers either its official `esp-IDF` platform or `Arduino`.

**Alternatives**
I believe Supporting more general platforms like `Arduino` or `Platform IO` will ease the process of supporting different boards.

**Comment by mrrostam** [comment]
Thank you for your suggestion; we are also interested in adding support for some boards from Arduino and ESP32. If you happen to know any popular ESP32 board that comes with a mic out of the box, please let us know here.

**Comment by aalaei** [comment]
ESP-EYE is one of the most popular boards which has an i2s digital microphone. (in addition to camera)

**Comment by radioman192** [comment]
I was also interested to see if the Teensy 4.0 board with its associated audio plug in board would be a candidate for this variant of Picovoice? It's also based on ARM Cortex-M7.   I'm a beginner to micros and wondered if the Teensy could be used "as is" or is there more to it than that?    Thanks - Don

**Comment by ayavilevich** [comment]
Thanks for making Picovoice Shepherd available for micro-controlers. Unfortunately the STM32 MCs have no built-in networking. It would be great to see the same offered to the ESP32 devices.

I am aware of at least one open source project that would benefit from this right now:
https://github.com/Romkabouter/ESP32-Rhasspy-Satellite
@Romkabouter fyi

ps. title should be changed to "ESP-32 support".

**Comment by Romkabouter** [comment]
> Thank you for your suggestion; we are also interested in adding support for some boards from Arduino and ESP32. If you happen to know any popular ESP32 board that comes with a mic out of the box, please let us know here.

This has a build-in mic as well:
https://m5stack-store.myshopify.com/products/atom-echo-smart-speaker-dev-kit

**Comment by Mark2013Toronto** [comment]
> Thank you for your suggestion; we are also interested in adding support for some boards from Arduino and ESP32. If you happen to know any popular ESP32 board that comes with a mic out of the box, please let us know here.

I'd suggest that this ESPRESSIF board is a great choice.   I bought two a year ago but ESPRESSIF has no really support for it.  

https://www.digikey.ca/en/products/detail/espressif-systems/ESP32-KORVO/12138980

**Comment by ayavilevich** [comment]
> 
> 
> Thank you for your suggestion; we are also interested in adding support for some boards from Arduino and ESP32. If you happen to know any popular ESP32 board that comes with a mic out of the box, please let us know here.

You don't really need a board that comes with a mic out of the box. You can take any ESP32 dev board and connect it to one or two I2S mics (i.e. INMP441). Just need wires.

For example see: https://www.youtube.com/watch?v=3g7l5bm7fZ8

**Comment by Mark2013Toronto** [comment]
> > Thank you for your suggestion; we are also interested in adding support for some boards from Arduino and ESP32. If you happen to know any popular ESP32 board that comes with a mic out of the box, please let us know here.
> 
> You don't really need a board that comes with a mic out of the box. You can take any ESP32 dev board and connect it to one or two I2S mics (i.e. INMP441). Just need wires.
> 
> For example see: https://www.youtube.com/watch?v=3g7l5bm7fZ8

Personally I'd find it much more convenient to use a board with microphones already on it, especially when it has 3 of them and costs around $50 CAD

https://www.espressif.com/en/news/ESP32-Korvo

**Comment by mrrostam** [comment]
@aalaei we recently released the [Picovoice Arduino library](https://picovoice.ai/arduino). it supports "Arduino Nano 33 BLE Sense" for now and we are working on other boards to add to this list.

**Comment by obones** [comment]
Espressif just released the ESP-Box project which has an ESP32-S3 board as its core and is aimed at demonstrating voice interaction. I has a microphone board with all the required noise cancellation and filtering required, and the firmware uses ESP-SR which has wake word detection, in a format that they call [WakeNet](https://github.com/espressif/esp-sr/blob/master/docs/wake_word_engine/README.md)
Maybe it could be possible to convert the picovoice models to that format.

**Comment by kenarsa** [comment]
closing for now as it didn't become a priority yet and not plausible to become one (not enough requests yet). I hope espressif can help out their users with their own software stack.
