### ISSUE TITLE
Picovoice Console Issue: 

### ISSUE THREAD

**Issue by ryanhollander** [Picovoice/picovoice#410]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
Wake word integration should initialize.

### Actual behaviour
Wake word fails to initialize on any of our "heyortho.com" domains. We get this error:
TypeError: Cannot create property 'error' on string 'Error: 'pv_porcupine_init' failed with status IO_ERROR'
    at w.error (app.51f5b825.js:1:106046)
    at Proxy.ppnErrorFn (431.60546cdf.js:1:45249)
    at vendor.3aa69d2a.js:116:2606756
    at c (vendor.3aa69d2a.js:116:2486292)
    at Generator._invoke (vendor.3aa69d2a.js:116:2487622)
    at Generator.throw (vendor.3aa69d2a.js:116:2486721)
    at a (vendor.3aa69d2a.js:116:2485389)
    at l (vendor.3aa69d2a.js:116:2485628)
u @ vendor.3aa69d2a.js:170

ADDITIONALLY: Our device limit used devices is INCREMENTED BY 1 with each load even on the same device!

Picovoice works fine on localhost, just not on our heyortho domains. This started a week ago.

### Steps to reproduce the behaviour

I'd have to give you access to our system, please contact us.

(Include enough details so that the issue can be reproduced independently.)

**Comment by laves** [comment]
Resolved via email.
