### ISSUE TITLE
multiple languages with picovoice

### ISSUE THREAD

**Issue by bmt1596** [Picovoice/picovoice#411]
Hi guys. 
Currently I am integrating Picovoice and Picovoice Cobra with C language on Cortex-A9 chip and using Picovoice configurator and libraries for Raspberry Pi. As far as I know, the Picovoice APIs only allow configuration with a File .rhn and .ppn in a fixed language. 

Is there a way to configure Picovoice for multiple languages? (e.g. English and German)

**Comment by kenarsa** [comment]
you can run multiple instances of the engine at the same time.
