### ISSUE TITLE
[ERROR] Endpoint duration should be >= 0.500000. Got 0.000000

### ISSUE THREAD

**Issue by mkjiang** [Picovoice/picovoice#413]
Hi, 

I'm trying to run the demo on my raspberry pi zero w with respeaker hat. After installing the respeaker voicecard driver I followed this readme (https://github.com/Picovoice/picovoice/tree/master/demo/respeaker-rpi0). However after executing this command

`./demo/respeaker-rpi0/picovoice_demo_mic \
-a $ACCESS_KEY \
-l sdk/c/lib/raspberry-pi/arm11/libpicovoice.so \
-p resources/porcupine/lib/common/porcupine_params.pv \
-k resources/porcupine/resources/keyword_files/raspberry-pi/picovoice_raspberry-pi.ppn \
0.65 \
-p resources/rhino/lib/common/rhino_params.pv \
-c demo/respeaker/pvrespeakerdemo/respeaker_raspberry-pi.rhn \
0.5 \
-i plughw:CARD=seeed2micvoicec,DEV=0`

I received the following error

`[ERROR] Endpoint duration should be >= 0.500000. Got 0.000000
'pv_picovoice_init' failed with 'INVALID_ARGUMENT'`

Can you help?

**Comment by kenarsa** [comment]
can you give it a try again? there was a mismatch there that we just solved.
