### ISSUE TITLE
Picovoice Console Issue: Can't login via github anymore

### ISSUE THREAD

**Issue by mikob** [Picovoice/picovoice#417]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
GH login works

### Actual behaviour
"The server encountered an unknown error while processing the previous request"

### Steps to reproduce the behaviour
1. Incognito window to make sure old cache isn't interfering
2. Click login with github
3. Put in credentials on the GH hosted page
4. put in 2 fac credentials
5. redirected to picovoices site where server error is seen (500 in the console)

(Include enough details so that the issue can be reproduced independently.)
![image](https://user-images.githubusercontent.com/492864/183130431-b7decba9-6e62-44dd-beaa-f0584a78daa1.png)

**Comment by ErisMik** [comment]
Thank you for the report! Issue has been reproduced and a patch has been pushed. Closing as fixed. Please feel free to open another issue if you continue to run into problems.
