### ISSUE TITLE
issue with Flutter on desktop - MissingPluginException

### ISSUE THREAD

**Issue by sean915213** [Picovoice/picovoice#438]
Attempting to use picovoice_flutter on macOS results in:
**MissingPluginException(No implementation found for method from_keyword_paths on channel porcupine)**

### Expected behaviour
PicovoiceManager works as expected- i.e. listens for wake words via Porcupine and determines intent via Rhino.

### Actual behaviour
Exception is thrown on start() method of PicovoiceManager.

### Steps to reproduce the behaviour
- picovoice_flutter version: 2.1.6
- macOS version: 12.6 (Monterey)
- flutter version: 3.3.2
- No particular steps for reproducing except boilerplate creation of PicovoiceManager and executing start().

**NOTE:** Same code works for iOS.

**Comment by mrrostam** [comment]
Hi @sean915213 

We don't have support for the flutter desktop at the moment, so it's expected to get `MissingPluginException` on macOS as there is no plugin for it. Picovoice SDK is avaiable for [C](https://picovoice.ai/docs/quick-start/picovoice-c/), [.NET](https://picovoice.ai/docs/quick-start/picovoice-dotnet/), [Go](https://picovoice.ai/docs/quick-start/picovoice-go/), [Java](https://picovoice.ai/docs/quick-start/picovoice-java/), [Node.js](https://picovoice.ai/docs/quick-start/picovoice-nodejs/), [Python](https://picovoice.ai/docs/quick-start/picovoice-python/), and [Rust](https://picovoice.ai/docs/quick-start/picovoice-rust/) on desktop though.

**Comment by sean915213** [comment]
Hey @mrrostam,

No support for macOS via Flutter is fair enough (though unfortunate). I'm curious (maybe this isn't the forum for this question)- but what is the reasoning behind not supporting, nor planning to support, macOS via Flutter when it is supported by other cross-platform frameworks? I assume implementation for macOS would be very similar to iOS using AVFoundation. But I haven't looked into the specifics.

**Comment by mrrostam** [comment]
Hey @sean915213 

Desktop application support for macOS is relatively new to Flutter and it was not around when we initially developed Picovoice's Flutter SDK, and it is not our priority at the moment. However, we are open to contributions and would be happy to review a PR if you are interested in adding support for it.
