### ISSUE TITLE
Picovoice Console Issue: Can't Sign in with Google

### ISSUE THREAD

**Issue by HabitWriter** [Picovoice/picovoice#439]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour

Login with Google Credentials

### Actual behaviour

Failed to fetch

![Screenshot 2022-09-28 113315](https://user-images.githubusercontent.com/104327600/192852073-69196d3f-255f-444f-9bea-da76a86d83e2.png)
![Screenshot 2022-09-28 114034](https://user-images.githubusercontent.com/104327600/192852075-40e2898a-c458-4772-892d-acd11d748660.png)

### Steps to reproduce the behaviour

I'm honestly a bit of a novice, so I'm not entirely sure. I was testing out uses of Leopard last night, running transcriptions and then manipulating the data. I was using the same audio file repeatedly, as a test, not sure if that might be related to the issue.

When I try to use it today I get back:

pvleopard.leopard.LeopardActivationError

So I assumed something changed with the activation key. But I'm unable to login and check.

Anyways, thanks for the awesome product! It is really going to speed up my video production speed.

(Include enough details so that the issue can be reproduced independently.)

**Comment by mrrostam** [comment]
Thanks for reposting this. 
We are aware of the issue and sorry for the inconvenience, but it's out of our control as it is caused by [AWS](https://health.aws.amazon.com/health/status). I'll update you once the problem is completely fixed and Picovoice Console returns to normal.

**Comment by HabitWriter** [comment]
Got it. Thanks for the update! It's helpful just to know what's going on. Here's hoping it's fixed soon.

**Comment by HabitWriter** [comment]
Looks like it is fixed. Thanks!

**Comment by mrrostam** [comment]
You are welcome; everything seems reasonably stable now.
