### ISSUE TITLE
Ask to have Shepard support stm32f7-discovery board

### ISSUE THREAD

**Issue by kfezer** [Picovoice/picovoice#44]
**Is your feature request related to a problem? Please describe.**
Just asking for another board to support. I have a few of these. Not sure how common they are over the other stm-disco boards

**Describe the solution you'd like**
If it's an easy lift, an extra board supported. 

**Describe alternatives you've considered**
Buying a new board.

**Comment by kenarsa** [comment]
We do support STM32H7 if you are looking for Cortex-M7 support on STM32. I keep this issue open to see how much traction we get and based on that we can make a call to whether put it on the roadmap.

**Comment by kfezer** [comment]
Sounds good!

**Comment by mrrostam** [comment]
Shepherd now supports STM32F7 discovery kit in its new version (0.9.5).

**Comment by Mark2013Toronto** [comment]
> Shepherd now supports the STM32F7 discovery kit in its new version (0.9.5).

Would it work with the STM32F746G-DISCO board?   I'm asking as I own one.   It has two microphones.

https://www.digikey.ca/en/products/detail/stmicroelectronics/STM32F746G-DISCO/5267791
