### ISSUE TITLE
Picovoice Console Issue: Unable to complete Picovoice Console sign-up

### ISSUE THREAD

**Issue by adrianwyatt** [Picovoice/picovoice#440]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
"Continue to Console" button continues to the console.

### Actual behaviour
A dialog pops up in the lower right corner: "Error updating user profile: The server encountered an unknown error while processing the previous request"

### Steps to reproduce the behaviour
Attempt to complete console sign-up.

(Include enough details so that the issue can be reproduced independently.)

**Comment by ksyeo1010** [comment]
Can you try again, we were updating the server.

**Comment by ksyeo1010** [comment]
Closed as the issue if fixed. Re-open if you encounter any issues.
