### ISSUE TITLE
Picovoice Console Issue: 

### ISSUE THREAD

**Issue by TemperedEnterprises** [Picovoice/picovoice#441]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
Generated Trigger files should trigger in Rhasspy.

### Actual behaviour
There is no way to get Rhasspy to trigger off the files created.

### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced independently.)

**Comment by kenarsa** [comment]
wrong repo. open the issue on Rhasspy.
