### ISSUE TITLE
The link for the unity package points to an old version

### ISSUE THREAD

**Issue by lpelicioli** [Picovoice/picovoice#447]
### The link for the unity package points to an old version
here: [https://github.com/Picovoice/picovoice#unity-demos](https://github.com/Picovoice/picovoice#unity-demos)
here: [https://github.com/Picovoice/picovoice#unity](https://github.com/Picovoice/picovoice#unity)
and here: [https://github.com/Picovoice/picovoice/tree/master/sdk/unity](https://github.com/Picovoice/picovoice/tree/master/sdk/unity)

**Comment by lpelicioli** [comment]
I would suggest putting the ```.unitypackage``` file in the release tab.
To simplify the search.
Thanks

**Comment by laves** [comment]
Thanks for the report @lpelicioli - docs have been fixed.
