### ISSUE TITLE
Picovoice Documentation Issue

### ISSUE THREAD

**Issue by DanilZherebtsov** [Picovoice/picovoice#448]
### What is the URL of the doc?
https://picovoice.ai/docs/quick-start/porcupine-python/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
The documents do not explicitly explain how to work with .wav files

I am using python API...
I have trained the model in the picovoice console, it works great with my microphone.

But when I try to feed in a .wav file, with the explicit keyword that the model was trained to recognise, it never recognises it. Keyword index is always -1
My file is about 1 second in length.

If I load up the whole 1 sec file, then try to predict on it with the model, I get a negative prediction :

```
import pvporcupine
import struct
import soundfile

ACCESS_KEY = 'my_access_key_hash'
THRESHOLD = 0.5

porcupine = pvporcupine.create(
  access_key=ACCESS_KEY,
  keyword_paths = ['My_model_en_mac_v2_1_0.ppn'],
  sensitivities = [THRESHOLD]
)

filepath = 'positive_class.wav'

dta, sr = soundfile.read(filepath)
pcm = struct.unpack_from("h" * porcupine.frame_length, dta)
porcupine.process(pcm)

# the result is -1, when the 1 second file includes only the keyword that the model was trained to recognise
```

I am not sure if I have to break the file into N frames of porcupine.frame_length objects. I've tried to process the file by overlapping windows with window size of porcupine.frame_length (512 in my case), and still didn't get any positive prediction:

```
start = 0
step = porcupine.frame_length
shift = 10
stop = start+step

dta, sr = soundfile.read(filepath)

for i in range(int(len(dta))):
    try:
        frame = dta[start:stop]
        pcm = struct.unpack_from("h" * porcupine.frame_length, frame)
        keyword_index = porcupine.process(pcm)
        print(keyword_index)
        if keyword_index >= 0:
            print(i)
            print(keyword_index)
            print('!!!!!!')
        start += shift
        stop = start + step
    except Exception as e:
        pass
```

**Comment by laves** [comment]
@DanilZherebtsov - check out the [Porcupine Python demos](https://github.com/Picovoice/porcupine/tree/master/demo/python) for an example of how to use Porcupine on a wav file. You can also pip install [pvporcupinedemo](https://pypi.org/project/pvporcupinedemo/) and use the demos directly to try your wav file.
