### ISSUE TITLE
Raspberry pi CM4 Overflow error

### ISSUE THREAD

**Issue by limitbit** [Picovoice/picovoice#449]
I try to make a quick test with raspberry pi CM4 with "ReSpeaker 2-Mics" and follow the [documents ](https://picovoice.ai/docs/quick-start/picovoice-c/) to build "picovoice_demo_mic" it is build with success unfortunately not working as expected. 

It returns  many "Overflow - reader is not reading fast enough" in a second until i break the app.

And this is the command: 

./demo/c/build/picovoice_demo_mic \
-a My Access Key \
-l sdk/c/lib/raspberry-pi/cortex-a72-aarch64/libpicovoice.so \
-p resources/porcupine/lib/common/porcupine_params.pv \
-k resources/porcupine/resources/keyword_files/raspberry-pi/picovoice_raspberry-pi.ppn \
-r resources/rhino/lib/common/rhino_params.pv \
-c resources/rhino/resources/contexts/raspberry-pi/smart_lighting_raspberry-pi.rhn \
-i 0

I tried all input options but no luck.

**Comment by laves** [comment]
@limitbit - this message is printed when your CPU is not processing audio as fast as it's being generated by the microphone. I would check your CPU usage before you run the demo to ensure you are not in a high CPU usage state.

**Comment by limitbit** [comment]
@laves nothing working cpu usage is %0-1, i tried your precompiled[ respeker demo](https://github.com/Picovoice/picovoice/tree/master/demo/respeaker) and it works well. Than i write simple test app based on pv_recorder with C++ and i realize pv_recorder had an issue. I play with pv_recorder init parameters but no luck. Now i use picovoice with asoundlib (previous versions capture style) to get pcm from mics and it works. I do not know what, something wrong with pv_recorder.

**Comment by laves** [comment]
Okay, thanks for checking. pv_recorder is used quite pervasively in our repos, so we're pretty sure there're no fundamental issues, but I wonder if it is how pv_recorder is interacting with your hardware. Can you open an issue on the [pvrecorder repo](https://github.com/Picovoice/pvrecorder) and we'll look into it?

**Comment by limitbit** [comment]
okay i open an issue to pv_recorder repository.
