### ISSUE TITLE
Picovoice C Documentation Issue

### ISSUE THREAD

**Issue by limitbit** [Picovoice/picovoice#450]
### What is the URL of the doc?
[https://picovoice.ai/docs/quick-start/picovoice-c/](https://picovoice.ai/docs/quick-start/picovoice-c/)

According to docs, usage of picovoice c SDK should be like;

const pv_status_t status = pv_picovoice_init(
            ACCESS_KEY,
            porcupine_model_path,
            keyword_path,
            porcupine_sensitivity,
            wake_word_callback,
            rhino_model_path,
            context_path,
            rhino_sensitivity,
            true,
            inference_callback,
            &picovoice);

But pv_picovoice_init() fuction requires "endpoint_duration_sec" parameters, as described in [https://picovoice.ai/docs/api/picovoice-c/#pv_picovoice_init](https://picovoice.ai/docs/api/picovoice-c/#pv_picovoice_init)

**Comment by laves** [comment]
@limitbit - thanks for the report. We've fixed the document and the change should be live in a few days.
