### ISSUE TITLE
Picovoice Console Issue: creating a wake word for "mama" 

### ISSUE THREAD

**Issue by aovestdipaperino** [Picovoice/picovoice#453]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
I tried to create a wake word via Picovoice Console: the ARM supported languages (EN, ES, DE, FR) all fail for the wake word being too small.
I created it for the Italian language, but when used with the Porcupine_EN library it fails.

**Comment by ErisMik** [comment]
Both of these behaviors are expected. Different languages have different pronunciations even for similar for words and therefore may prove longer or shorter. In addition, model files made for a specific language are only compatible with the library for that language for similar reasons as the first point. Closing this Issue.
