### ISSUE TITLE
Cortex-m library for Italian for PicoVoice

### ISSUE THREAD

**Issue by aovestdipaperino** [Picovoice/picovoice#459]
Right now there is only a subset of languages supported on ARM.
Would it be too complicated to recompile the Italian library for ARM?

**Comment by kenarsa** [comment]
Do you mean cortex-m? If yes, please update the title of the issue

**Comment by aovestdipaperino** [comment]
Done, thanks!

**Comment by kenarsa** [comment]
thank you! you are right. we are missing a few languages on Arduino. we will try to add these early next year but it will take time and I can't give a time estimate right now. I will circle back as we get closer.

**Comment by kenarsa** [comment]
We do have Italian support for Arm Cortex-M now!
