### ISSUE TITLE
Picovoice Console Issue: "Error retrieving Rhino model: Internal server error"

### ISSUE THREAD

**Issue by ReeceKenney** [Picovoice/picovoice#474]
Hello,

I have a rather large Rhino YML file consisting of almost 2,000 lines. ~315 expression lines, ~1,500 lines of slots and ~150 lines of macros. Recently I've noticed that when building the rhino file from the console (so that I can test it from the browser) I'm seeing the error "Error retrieving Rhino model: Internal server error". There's no additional diagnostic information but from my very uneducated guess, it seems like it's a timeout. When I remove a chunk of expressions, it builds fine. I've also tried removing different chunks expressions over multiple builds to hopefully rule out the issue being with any _specific_ expressions. 

Does this seem likely/possible that it's a timeout? If so, what can be done to work around this (if anything)? I'm aware Rhino YML files probably aren't usually this large, but I read in the [Rhino FAQ](https://picovoice.ai/docs/faq/rhino/) that _"There is no technical limit on the number of commands (expressions) or slot values Rhino can understand"_ so I figured that it was fine. 

When I tried to train the rhino file, I also saw this error.

**Edit:**
I don't know if this helps at all, but the following error appears in the browser console when the internal server error ocurs:

All the best,
<img width="749" alt="Screenshot 2023-01-08 at 4 10 33 pm" src="https://user-images.githubusercontent.com/5323490/211207060-fa1f0683-1f1e-4bc6-9840-b0c853aadcc0.png">

<img width="990" alt="Screenshot 2023-01-08 at 4 08 56 pm" src="https://user-images.githubusercontent.com/5323490/211207092-bbdd5fdc-a125-47f2-88a4-8aa3abba2fee.png">

<img width="300" alt="Screenshot 2023-01-08 at 3 52 55 pm" src="https://user-images.githubusercontent.com/5323490/211206725-9620258a-86e7-4879-91a1-ef06c0f68d7c.png">

**Comment by ErisMik** [comment]
Thank you for the report. I can confirm that this is indeed a timeout issue that is seen on some very large contexts. The issue has been identified and fixed internally but unfortunately will need to wait for the next release to go live as the changes are backwards incompatible. There isn't exact date for the next release, but I will leave this issue open and comment/close it when the fix is in.

For now, reducing the number of optionals `()`  in your expressions should help. This was most likely done implicitly when you removed some of your expressions, but the number of expressions can still remain the same.

**Comment by ReeceKenney** [comment]
Thank you for the quick response! That's very helpful. Is there any sort of rough ball park of how long it usually is between releases? Is it something that happens every few weeks, months, quarterly etc.?

**Comment by ErisMik** [comment]
There is no set schedule at this time, but this specific next release will be within the next couple of months.

**Comment by kenarsa** [comment]
@ReeceKenney, this issue should be resolved now. Can you please give it a try? I am closing, but if you still experience the problem, kindly re-open it, and we will investigate it ASAP.
