### ISSUE TITLE
React Native custom keyword and context files invalid

### ISSUE THREAD

**Issue by VolkerLieber** [Picovoice/picovoice#48]
I downloaded your clock example for React Native and it works without problems, but then I use my custom keyword and context files built for android with german voice input, the app crashed with this error:
[Error: ai.picovoice.porcupine.PorcupineException: java.lang.IllegalArgumentException: Initialization failed.]

### Expected behaviour
Starts normal

### Actual behaviour
[Error: ai.picovoice.porcupine.PorcupineException: java.lang.IllegalArgumentException: Initialization failed.]

### Steps to reproduce the behaviour
Download pico clock demo for React Native.
Use these files.
[clock_android.zip](https://github.com/Picovoice/picovoice/files/6131173/clock_android.zip)

**Comment by VolkerLieber** [comment]
That seems to be an oversight on my side as well. Sorry for the inconvenice regarding this matter and thanks for your quick reply - but I still can't get the demo to work. If I manually provide the english files, everything works. With the german files it sadly does not.

**Comment by laves** [comment]
I was able to reproduce with the wake word file you provided. It seems the file is being rejected for either being for being from another platform or from another version of Porcupine. This might be our issue, but I just want to make sure - was this wake word trained for Android and exported through the console recently?

**Comment by VolkerLieber** [comment]
![model](https://user-images.githubusercontent.com/42102008/110992549-5b88be80-8376-11eb-9aaa-a47f2646eae1.png)
![wakeword](https://user-images.githubusercontent.com/42102008/110992555-5c215500-8376-11eb-8140-2a60bf5d20cc.PNG)

**Comment by laves** [comment]
Okay, we'll look into this and get back to you. Thanks for reporting.

**Comment by laves** [comment]
@VolkerLieber if you rename the model files or uninstall and reinstall the clock demo from your dev device it should work. I think what's happening is - since your files have the same name as the english ones, the german ones are not overwriting the old english ones that are still on the device. The react-native-fs package used in the demo claims it overwrites files that already exist, but that does not seem to be the case.

**Comment by VolkerLieber** [comment]
Yes, that seems to be the problem. Thanks again for your excellent help
