### ISSUE TITLE
Picovoice Android Studio res file

### ISSUE THREAD

**Issue by jasonmp2345** [Picovoice/picovoice#487]
Hello, I cloned the repo for the android project and everything was seemingly working fine until I noticed the read only file available from the external library is giving me issues. 

![image](https://user-images.githubusercontent.com/113390475/214208006-cdd441dd-3a82-4177-bb55-e719a3fc1f7f.png)

It is not recognizing the coinciding res file that come with the external library. I have followed all the rules for Android and I am stumped. Is there something required for me to get this to work?

Thank you

**Comment by ErisMik** [comment]
Could you please provide some additional details:
- Is this the SDK or Demo project?
- Is this a build/compile time error or a runtime error?
- What is the error message?

**Comment by jasonmp2345** [comment]
To answer specific questions:

- This problem has occurred in both SDK projects and the demo project every time I try and import the picovoice dependency
- This is a runtime error 
- The error message is 'cannot resolve symbol R'

I can see the Res folder under external libraries but the class does not seem to pick it up

![image](https://user-images.githubusercontent.com/113390475/214401285-532b9326-97c8-46dc-95df-a02930e6b286.png)

**Comment by jasonmp2345** [comment]
Above is a picture of the external library and where the Porcupine.java class is attempting to get the resource files. For some reason, the res folder (R) is not being resolved by the IDE

**Comment by ErisMik** [comment]
I am able to do a clean build of the demo projects without any issue. Once the project is open in Android Studio, have you pressed the "Sync Project with Gradle Files" button?

**Comment by jasonmp2345** [comment]
Yes. I have cleared cache as well. I do not believe it is a problem within the project but something wrong with my IDE? I am not sure why the res file is not being found by Porcupine.java. I will continue to troubleshoot. Thank you

**Comment by ErisMik** [comment]
Yes, I believe the issue is something wrong with your IDE / setup. Another thing to note that you may have missed is that if you are building the binding/sdk manually there might be a `copy.sh` script that needs to be run before the project can be built.  The `picovoice` sdk itself does **not** have one but `porcupine` does.

**Comment by jasonmp2345** [comment]
Where would one find this copy.sh file? In the repo?

**Comment by ErisMik** [comment]
It would be in the project folder if it's needed for that project. 
Which specific project are you using? Does this error occur when you open `picovoice/demo/android/Activity` in Android Studio from a clean repo clone?

**Comment by jasonmp2345** [comment]
I ran that file and still nothing. Yes this happens when I open that path from a repo clone. Have not touched a thing from that repo. The demo app runs fine until it hits the PorcupineMangager.build function which uses one of the resources that I do not have access to. This causes the app to crash.

**Comment by jasonmp2345** [comment]
Could you send a picture of your Porcupine.java class in either Android Studio or IntelliJ? I have tried both, have not changed anything on my end and have redownloaded both applications plenty of times. I do not think it is a setup/ide problem I believe it to be a bug for these IDEs.

**Comment by ErisMik** [comment]
If your app is running into the `PorcupineManager` class then you are not using the `Picovoice` demo from this repository. If you think this is an issue with those IDEs then I would suggest bringing it up on their respective forums.
