### ISSUE TITLE
wPicovoice Console Issue: wake word

### ISSUE THREAD

**Issue by marwen22462** [Picovoice/picovoice#499]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced independently.)

**Comment by mrrostam** [comment]
@marwen22462 it seems that you forgot to mention the issue you are facing. Without any information, it's impossible for us to help you. I'm gonna close the issue, but feel free to open it again and explain the problem with enough details.
