### ISSUE TITLE
Picovoice Console Issue: Error when using a German Rhino model

### ISSUE THREAD

**Issue by petreni** [Picovoice/picovoice#50]
I'm currently testing Picovoice for the development of a Flutter app.

I created a Rhino model in English and loaded it into my test app. That worked perfectly - the commands are all recognized correctly.
Then I created a new model in German and tried to load it. When the PicovoiveManager is initialized ('PicovoiceManager.create' function), the following error is thrown:

_Keyword files (.ppn) and model file (.pv) should belong to the same language. Keyword files belongs to 'de' while model file belongs to 'en'_

or (depending on whether I use a German or an English keyword file)

_context file belongs to 'de' while model file belongs to 'en'_

I can't generate the model file (.pv) in German via the console ???

**Comment by Gummi-Ente** [comment]
I have the very same issue #49 on python.

**Comment by kenarsa** [comment]
The `.PV` files are available on GitHub. For non-English languages, you need to provide them as input arguments to the constructor.

Porcupine DE model: https://github.com/Picovoice/porcupine/blob/master/lib/common/porcupine_params_de.pv
Rhino DE model: https://github.com/Picovoice/rhino/blob/master/lib/common/rhino_params_de.pv

**Comment by petreni** [comment]
Thanks a lot - I'll try it...

**Comment by petreni** [comment]
Hi Alireza,

thanks a lot – I was successful 😊

One additional question – in an English model I can use the built-in slots for an intent (i.e. $pv.TwoDigitInteger) – if I try the same in an German model I get an error message. Is there an equivalent for the other languages available? 

I can create an own slot with the digits – but in this case I get the slot result as a string – with the built-in slot I get an integer… 

Regards

Nikolaus

Von: Alireza Kenarsari
Gesendet: Samstag, 13. März 2021 17:22
An: Picovoice/picovoice
Cc: petreni; Author
Betreff: Re: [Picovoice/picovoice] Picovoice Console Issue: Error when using aGerman Rhino model (#50)

The .PV files are available on GitHub. For non-English languages, you need to provide them as input arguments to the constructor.
Porcupine DE model: https://github.com/Picovoice/porcupine/blob/master/lib/common/porcupine_params_de.pv
Rhino DE model: https://github.com/Picovoice/rhino/blob/master/lib/common/rhino_params_de.pv

**Comment by Tschukedi** [comment]
How do I give the input argument with rustc for Porcupine DE & Rhino DE model?

**Comment by Tschukedi** [comment]
Still I am a little clueless how to implement that in Rust. 

`
    let mut picovoice = PicovoiceBuilder::new(
        access_key,
        keyword_path,
        wake_word_callback,
        context_path,
        inference_callback,
        //porcupine_model_path,
    ).init().expect("Failed to create picovoice");

}
`

The compiler tells me that 5 arguments are needed but 6 were given. When I look up the lib.rs that was mentioned after trying to compile I changed it to something like that!

`
    pub fn new<S: Into<String>, P: Into<PathBuf>>(
        access_key: S,
        keyword_path: P,
        wake_word_callback: W,
        context_path: P,
        inference_callback: I,
        porcupine_model_path: P,
    ) -> Self {
        Self {
            access_key: access_key.into(),
            keyword_path: keyword_path.into(),
            wake_word_callback,
            context_path: context_path.into(),
            inference_callback,
            porcupine_library_path: None,
            porcupine_model_path: porcupine_model_path.into(),
            porcupine_sensitivity: None,
            rhino_library_path: None,
            rhino_model_path: None,
            rhino_sensitivity: None,
            rhino_endpoint_duration_sec: None,
            rhino_require_endpoint: true,
        }
    }
`

My goal is give a path to the "porcupine_params_de.pv". With my current knowledge I can not solve it!
