### ISSUE TITLE
Error in React demo: 'pv_porcupine_init' failed with status INVALID_ARGUMENT\nDetails

### ISSUE THREAD

**Issue by contigen** [Picovoice/picovoice#501]
Hi! As the docs instructed, I cloned the repo and started the react demo, upon inputting my **AccessKey**, I got this error:

![porcupine-error](https://user-images.githubusercontent.com/69436315/219869069-12d8cd4c-cc91-4a06-b3c1-0238368f6650.png)
Is there something I missed?

**Comment by ksyeo1010** [comment]
make sure you enter the correct access key, it seems the access key you provided was incorrect.

**Comment by contigen** [comment]
Hello @ksyeo1010 don't mind me, I indeed made a mistake with the access key.
Thank you!
