### ISSUE TITLE
Short-term Authentication Token

### ISSUE THREAD

**Issue by prescod** [Picovoice/picovoice#502]
**Is your feature request related to a problem? Please describe.**

I do not want to embed my AccessKey in the app or web page that I deliver to the user. They can steal it and make API calls as me. Typically this is handled by allowing me to generate 30-minute Authentication Tokens.

**Describe the solution you'd like**

From a similar product vendor: "Your API key can be used to generate an authentication token which will be used to authenticate all your requests to the API. Authentication tokens have a validity of 30 minutes and new tokens have to be created after that timeframe. Requests that don't contain the authentication token will be unsuccessful."

**Describe alternatives you've considered**

Obfuscation, but security through obscurity is poor.

**Comment by kenarsa** [comment]
Thanks, @prescod, for the suggestion. This solution can work in environments that have constant connectivity. But we want our SDKs to work in environments with possibly intermittent connectivity. e.g. automotive. We understand your concern and are open to tracking it for now.

**Comment by kenarsa** [comment]
I am closing as this has not made it to our immediate roadmap.

**Comment by jtdLab** [comment]
@kenarsa  What is the recommended way to limit usage through the api key?

Could an opt-in approach be suitable? Where users on mobile or web may enable time-based access others stick to the current approach.
