### ISSUE TITLE
Picovoice Console Issue: Rhino not saving/updating properly

### ISSUE THREAD

**Issue by tempo-riz** [Picovoice/picovoice#503]
### Expected behaviour
After updating my context and saving it, i download the .rfn file and the context is updated with my previous changes

### Actual behaviour
After updating my context and saving it, i download the .rfn file BUT the context isn't updated with my previous changes
I noticed it with the inference result. (the slots still had old names)

I tried twice in a pretty short time, making sure the context was properly saved will retry later, maybe there is a delay issue

**Comment by ksyeo1010** [comment]
Hi, thanks for reporting the issue, I tried reproducing it on my end and it seems to be updating fine.

Can you start with an empty document and try if can you get the same issue? If you get the issue, can you provide step-by-step instructions so that we can reproduce it?

**Comment by tempo-riz** [comment]
My bad it seemed I had some caching issues and was using wrong model !
