### ISSUE TITLE
Picovoice Shepherd bug on Windows-10-AMD64-AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD

### ISSUE THREAD

**Issue by Dharshni3366** [Picovoice/picovoice#507]
"The board is not connected to the system" error window appears whenever I try to connect my STM32F407 board to Picovoice Shepherd platform.  How to resolve this issue?

**Comment by mrrostam** [comment]
Thanks for reporting the issue. It is probably a driver issue; to check that, can you please get the latest driver from the [STSW-LINK009](https://www.st.com/en/embedded-software/stsw-link009.html) page and install it by executing `dpinst_amd64.exe`?

**Comment by Dharshni3366** [comment]
Still the same old error

**Comment by mrrostam** [comment]
I ran Shepherd on a newly installed Windows 10 machine, and it worked fine after installing the driver. So in your case, either the driver is not installed correctly, or there are some hardware issues. I would suggest you try the following:

1. Reinstall the driver by running `stlink_winusb_install.bat` in administrator mode, before connecting the board to the PC (as mentioned in the README).
2. Connect the board, open `Device Manager`, and check if there is a device named `STMicroelectronics/ST-LINK *` under `Universal Serial Bus controllers`.
 
If the device is not listed, then it is probably a hardware issue.
