### ISSUE TITLE
Issue with stm32f407 demo

### ISSUE THREAD

**Issue by kabilan18** [Picovoice/picovoice#511]
Hi there,
I have tried running the picovoice example code on stm32f407-disc1 on Cube IDE but the board is not listening to the wake word instead it is just printing the uuid. 
I have also tried using PV SHEPHERD platform after the firmware upgrade the platform is not responding to the wake word the application crashes

**Comment by mrrostam** [comment]
Hi there,

I grabbed the demo project and tried it myself, but everything seems fine as you can see below. 

```
UID:  2c 00 55 00 13 51 37 34 34 37 33 32
[wake word]
{
    is_understood : 'true',
    intent : 'changeLightState',
    slots : {
        'state' : 'on',
    }
}
```

You might find the last part of [this walkthrough](https://youtu.be/ibDY1PKRQZU?t=652) useful (even though it's for STM32F411, but the process is the same for STM32F407).

Regarding the Shepherd problem, since you already opened another issue for it, I'll address it over there.

**Comment by kabilan18** [comment]
Followed the same but same error arises

**Comment by kabilan18** [comment]
tried porcupine demo file and got the following error
make -j2 all 
arm-none-eabi-gcc "../Src/main.c" -mcpu=cortex-m4 -std=gnu99 -D__PV_LANGUAGE_ENGLISH__ -DSTM32 -DSTM32F407xx -DSTM32F407G_DISC1 -DUSE_STM32F4_DISCO -DUSE_HAL_DRIVER -DSTM32F4 -DSTM32F407VGTx -DDEBUG -c -I../Inc -I../../../../../include -I../Middlewares/ST/STM32_Audio/Addons/PDM/Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/BSP/STM32F4-Discovery -O2 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Src/main.d" -MT"Src/main.o" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "Src/main.o"
arm-none-eabi-gcc -o "stm32f407g-disc1-demo.elf" @"objects.list"  -lpv_porcupine -lPDMFilter_CM4_GCC_wc32 -mcpu=cortex-m4 -T"C:\Users\kabil\Desktop\mcu\stm32f407\stm32f407g-disc1\STM32F407VGTX_FLASH.ld" --specs=nosys.specs -Wl,-Map="stm32f407g-disc1-demo.map" -Wl,--gc-sections -static -L../../../../../lib/mcu/stm32f407/en -L../Middlewares/ST/STM32_Audio/Addons/PDM/Lib/ --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -Wl,--start-group -lc -lm -Wl,--end-group
c:\st\stm32cubeide_1.11.0\stm32cubeide\plugins\com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.win32_1.0.200.202301161003\tools\arm-none-eabi\bin\ld.exe: cannot find -lpv_porcupine
collect2.exe: error: ld returned 1 exit status
make: *** [makefile:67: stm32f407g-disc1-demo.elf] Error 1
"make -j2 all" terminated with exit code 2. Build might be incomplete.

15:08:02 Build Failed. 2 errors, 0 warnings. (took 2s.506ms)

**Comment by kabilan18** [comment]
Hi there,
I have tried uploading demo code of picovoice and procupine model the code gets uploads to the dev board and prints uuid. The same problem arises when i tried calling the wake word there is no response.

**Comment by kabilan18** [comment]
HI, 
I have replaced  the access key in both the files and the same problem arises for both picovoice and porcupine demo files. 
Kindly help me with it

**Comment by mrrostam** [comment]
After testing both demos, our team has found that they are functioning as intended. Therefore, if you have followed the instructions in the readme file correctly and are still encountering issues, it is possible that there may be a hardware problem with your board.

**Comment by kabilan18** [comment]
I have changed the access key place holder,
//static const char *ACCESS_KEY = "pbPx1Gs***Rq6iW*******YPelIhkY**********************";//
Could you please share a demo file for testing the onboard microphone on STM32F407G-DISC1 development board. It would be more helpful for testing the development board.

**Comment by mrrostam** [comment]
Unfortunately, we do not have a dedicated demo for mic testing purposes. However, you may find some relevant samples from ST that could serve this function.
