### ISSUE TITLE
did you replace `${ACCESS_KEY}`, which is only a placeholder, with your AccessKey inside `main.c`/`main_multi.c`?

### ISSUE THREAD

**Issue by kabilan18** [Picovoice/picovoice#514]
did you replace `${ACCESS_KEY}`, which is only a placeholder, with your AccessKey inside `main.c`/`main_multi.c`?

_Originally posted by @mrrostam in https://github.com/Picovoice/picovoice/issues/511#issuecomment-1478534505_
            
HI,
I have replaced the access key in both the files and the same problem arises for both picovoice and porcupine demo files.
Kindly help me with it

**Comment by mrrostam** [comment]
Kindly refrain from creating duplicate issues for the same problem. I will be closing this duplicate issue and responding to you on the original thread.
