### ISSUE TITLE
Does picovoice wake-up word support NVIDIA Jetson Xavier NX? 

### ISSUE THREAD

**Issue by suzhidong** [Picovoice/picovoice#525]
From the document, I can see that the picovoice wake-up word support NVIDIA Jetson Nano. But I have an NVIDIA Jetson Xavier NX and I wanted to use the wake-up word in it. When I tried to run the Python code in NVIDIA NX, it gave me an error showing that: NotImplementedError: Unsupported CPU: '0x004'.

I think it means that Nvidia NX is not supported right now, am I right? If yes, may I ask if you are planing to support this kind of device?

Thank you!

**Comment by ErisMik** [comment]
That is correct, it that means the Nvidia NX is not supported. 

Unfortunately our immediate roadmap does not include adding support for the NVIDIA Jetson Xavier NX, but if you are developing a commercial product and are willing to engage formally, you can reach out to our sales team to inquire about obtaining this support through an enterprise package.
