### ISSUE TITLE
Picovoice Flutter for Web/Windows/Mac

### ISSUE THREAD

**Issue by pelaezcarlos** [Picovoice/picovoice#545]
Is compatibility with web, windows, and mac apps planned in the integration with flutter?

**Comment by laves** [comment]
We aren't currently planning on adding desktop/web support for Flutter, but I can leave this issue open and if there's enough traction from the community we may consider adding it to the roadmap.

**Comment by pelaezcarlos** [comment]
Thanks for your answer.
We are building a cross-platform app in Flutter and PicoVoice is important in our workflow, maybe we can have a meeting to review possibilities for collaboration.

**Comment by laves** [comment]
@pelaezcarlos - the engineering team is unable to help you with business inquiries. Feel free to reach out via our [website contact](https://picovoice.ai/contact/) with your project details.

**Comment by kenarsa** [comment]
Unfortunately, we can't prioritize these at this time.

(1) You are welcome to submit a PR and unblock yourself.
(2) If you are engaged commercially with Picovoice, you can contact your account manager for enterprise support.
