### ISSUE TITLE
Add UUID To Comment At Top of Context/Keyword Files

### ISSUE THREAD

**Issue by nelsonii** [Picovoice/picovoice#549]
It would be helpful if the UUID used to generate a model (either custom Keyword or Context set) were included at the top of the generated .h file. 

Adding the library version associated (ex. 2.2.x) as a comment in the file would be handy, too (Realizing that the version is part of the filename -- I'm introducing a level of laziness on my part, I admit.)

**Comment by mrrostam** [comment]
I appreciate your suggestion. I'll keep this issue open and forward the idea to our Picovoice Console team to assess its priority.

**Comment by mrrostam** [comment]
Hello @nelsonii,

I wanted to inform you that the requested feature has been added quite some time ago, and you can now access it in the models downloaded from the Picovoice Console.
