### ISSUE TITLE
[ERROR] failed to parse AccessKey '${accessKey}'

### ISSUE THREAD

**Issue by zbeb** [Picovoice/picovoice#551]
I created my picovoice account and copied the access key, followed the documentation but when I try to run the program here is the error it gives:
`[ERROR] failed to parse AccessKey '${Key}'
Traceback (most recent call last):
  File "c:\Users\zbeb\Documents\GitHub\Programming\Python\Voice Assistant\main.py", line 101, in <module>
    main()
  File "c:\Users\zbeb\Documents\GitHub\Programming\Python\Voice Assistant\main.py", line 72, in main
    porcupine = pvporcupine.create(access_key=accessKey, keyword_paths=keywordPath)
  File "C:\Users\zbeb\AppData\Local\Programs\Python\Python310\lib\site-packages\pvporcupine\_factory.py", line 69, in create
    return Porcupine(
  File "C:\Users\zbeb\AppData\Local\Programs\Python\Python310\lib\site-packages\pvporcupine\_porcupine.py", line 164, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine._porcupine.PorcupineInvalidArgumentError` 

And here is the code:
`accessKey='${Key}'
        keywordPath=['C:\\Users\\zbeb\\Documents\\GitHub\\Programming\\Python\\Voice Assistant\\Hey-echo_en_windows_v2_2_0.ppn']
        porcupine = pvporcupine.create(access_key=accessKey, keyword_paths=keywordPath)`

----------------------------------------------
If it is of any help, here is the full code:
```
import os
import speech_recognition as sr
import pyttsx3
import pvporcupine
import pyaudio
import struct
import time

wakeWord = ["hey echo"]
user = "engineer"

# Initialize text-to-speech engine
engine = pyttsx3.init()

# Initialize speech recognition engine
r = sr.Recognizer()

def speak(text):
    """
    Function to convert text to speech
    """
    engine.say(text)
    engine.runAndWait()


def listen():
    """
    Function to listen for user command
    """
    with sr.Microphone() as source:
        print("listening...")
        audio = r.adjust_for_ambient_noise(source)
        audio = r.listen(source)
        try:
            text = r.recognize_google(audio)
            return text.lower()
        except Exception as e:
            return f"Exeption: {str(e)}"
        

def ConversationFlow():
    """
    Function to handle conversation flow
    """
    while True:
        # Check for specific keywords and respond accordingly
        command = listen()
        words = command.split()
        print(f"User said: {command}")

        if "hello" in command:
            speak("Hello")
        if "bye" in command:
            speak("Goodbye")
        if "how are you" in command:
            speak("I am doing good")


def main():
    """
    Main function
    """
    porcupine = None
    pa = None
    audioStream = None

    print(f"E.C.H.O version 1.0 - Ready and awaiting your command {user}")

    try:
        accessKey='${Key}'
        keywordPath=['C:\\Users\\zbeb\\Documents\\GitHub\\Programming\\Python\\Voice Assistant\\Hey-echo_en_windows_v2_2_0.ppn']
        porcupine = pvporcupine.create(access_key=accessKey, keyword_paths=keywordPath)
        pa = pyaudio.PyAudio()
        audioStream = pa.open(
            rate=porcupine.sample_rate, 
            channels=1, 
            format=pyaudio.paInt16,
            input=True,
            frames_per_buffer=porcupine.frame_length)
        
        while True:
            pcm = audio_stream.read(porcupine.frame_length)
            pcm = struct.unpack_from("h" * porcupine.frame_length, pcm)

            keyword_index = porcupine.process(pcm)
            if keyword_index >= 0:
                print("Wakeup word detected")
                ConversationFlow()
                print(f"E.C.H.O awaiting your command {user}")
    finally:
        if porcupine is not None:
            porcupine.delete()

        if audioStream is not None:
            audioStream.close()

        if pa is not None:
            pa.terminate()


main()
```

**Comment by zbeb** [comment]
> 
I have this
`accessKey='${Key}'`
and instead of "Key" I just pasted what I copied from the console without anything else

**Comment by mrrostam** [comment]
Aha! Remove ${} and only leave your AccessKey string inside the quote marks
