### ISSUE TITLE
Undefined reference to taabe576

### ISSUE THREAD

**Issue by jossebv** [Picovoice/picovoice#554]
Hello, I have a project based on the picovoice demo (Version 2.1) running at the stm32f411 board (I just adapted it to avoid using the STM32Cube). This project was working fine, but I wanted to update it so I can use custom models. The problem is that after replacing the old library with the new one I get an error when compiling saying: 

-> #"in function `taabe772': (.text.taabe772+0xdc): undefined reference to `taabe576'". 

I am not sure if this problem is related with my compiler or the new version of the library since it works perfectly with the previous version.

**Comment by ksyeo1010** [comment]
Which language and compiler are you using?

**Comment by jossebv** [comment]
I'm using C and the gcc-arm-none-eabi compiler

**Comment by jossebv** [comment]
It worked on the STM32Cube and from there I realised that adding the garbage collector it compiles perfectly. Thanks for the help!
