### ISSUE TITLE
Picovoice Issue: Failed to execute hotword detection program in python 

### ISSUE THREAD

**Issue by rohitkuyadav2003** [Picovoice/picovoice#557]
![Screenshot (5)](https://github.com/Picovoice/picovoice/assets/114132335/42612506-e61e-4b9b-a12e-5d4c7d6594b4)

facing the following issue

**Comment by ksyeo1010** [comment]
This seems to be an issue how you are using pyaudio. Re-open issue or open new one if you have an issue using our official [demo](https://github.com/Picovoice/porcupine/tree/master/demo/python).
