### ISSUE TITLE
Picovoice Documentation Issue

### ISSUE THREAD

**Issue by WADVahag** [Picovoice/picovoice#583]
### What is the URL of the doc?
https://picovoice.ai/docs/quick-start/porcupine-react/#custom-keywords

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
1 : Nothing about what to do if the words are not recognized by the console
2 : How to make your own wake word after giving it a mp3 file , basically for example we want to set a password word as a wake word for gate opening and we cannot do that because of that issue and no information about how to achieve it

**Comment by kenarsa** [comment]
Duplicate issue of [this](https://github.com/Picovoice/picovoice/issues/568). Closing. If you need help, please feel free to comment on the already-created issue, and we can re-open it if required.

**Comment by WADVahag** [comment]
yes please close this one and open theat ine if needed i will add the same comment there
