### ISSUE TITLE
Need new Wake Words on Russian Vocabulary for LOL Heroes names there are missing 

### ISSUE THREAD

**Issue by WADVahag** [Picovoice/picovoice#584]
**Is your feature request related to a problem? Please describe.**
Hello dear Picovoice Team we need to have in Russian vocabulary all he names recognized from the LOL games we are planning to make many applications for heroes on multiple device platforms and are struggling because most  of the names are missing , right now we are working on the Anny project and need her wake word that is unfortunately missing . Here is additional information about the words we need to be recognized 

**Describe the solution you'd like**
We need to ba able to train the model of wake word with missing words from rusian vocabulary , we need names of LOL heroes there Our first hero is Anny  next will be Darius  because we plan to make next step as a male character app

**Describe alternatives you've considered**
For now critical is only one wake word in Russian vocabulary we need the name Anny , we got the working on English that is Hello Anny , now we need the same for the Russian vocabulary but on there greeting that is Privet Anny so in Russian it is written like this " Привет Энни" .

**Additional context**
Additionally and not so Critical for now is that our next  Hero we plan to add will be Darius so will need the same with him only this time it will be Hello Darius on English  and Привет Дариус on Russian Vocabulary

**Comment by WADVahag** [comment]
HEre is hte Google translate for the proove and also you can get teh voice from there etc for the recoingiton 
https://translate.google.am/?hl=hy&sl=ru&tl=en&text=Привет%20Энни&op=translate](https://translate.google.am/?hl=hy&sl=ru&tl=en&text=%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D1%82%20%D0%AD%D0%BD%D0%BD%D0%B8&op=translate)

**Comment by kenarsa** [comment]
Thanks for reporting this. Unfortunately, this is not a task we can prioritize in our roadmap at the moment due to other urgent tasks.
