### ISSUE TITLE
Picovoice Documentation Issue (/docs/quick-start/eagle-python/)

### ISSUE THREAD

**Issue by Coranath** [Picovoice/picovoice#589]
### What is the URL of the doc?

https://picovoice.ai/docs/quick-start/eagle-python/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)

Right near the beginning of the Python Quick Start guide there is a reference to pvkoala that I believe should be a reference to pveagle. The link does point to pvkoala. Not pveagle!

![pveagleDocBadLink](https://github.com/Picovoice/picovoice/assets/34037243/28904ec5-185c-4128-8f52-ecfef223126b)

**Comment by mrrostam** [comment]
Thank you for bringing this to our attention. We have addressed the mistake and updated the doc.
