### ISSUE TITLE
Running Picovoice inside a docker container

### ISSUE THREAD

**Issue by williamp0044** [Picovoice/picovoice#590]
I've been working on building a containerized tts system similar to rhassbian but your system is reading the docker container as multiple users.

appuser@4e43b0224410:/app$ python main.py
Traceback (most recent call last):
  File "/app/main.py", line 18, in <module>
    porcupine = pvporcupine.create(
  File "/home/appuser/.local/lib/python3.10/site-packages/pvporcupine/_factory.py", line 69, in create
    return Porcupine(
  File "/home/appuser/.local/lib/python3.10/site-packages/pvporcupine/_porcupine.py", line 164, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine._porcupine.PorcupineActivationLimitError

my bash history:
 231  docker compose up -d --build
  232  docker ps -a
  233  docker logs      arti_speech-myapp-1
  234  nano app/.env
  235  docker compose down
  236  docker compose up -d --build
  237*
  238  docker compose down
  239  docker compose up -d --build
  240*
  241  docker compose down
  242  docker compose up -d --build
  243  docker logs      arti_speech-myapp-1
  244  docker compose down
  245  docker compose up -d --build
  246  id -u
  247  lsusb
  248  lsusb -v
  249  nano entrypoint.sh
  250  docker compose down
  251  docker compose up -d --build
  252  docker logs      arti_speech-myapp-1
  253  docker compose down
  254  docker compose up -d --build
  255  docker logs      arti_speech-myapp-1
  256  docker compose down
  257  docker compose up -d --build
  258  docker logs      arti_speech-myapp-1
  259  docker compose down
  260  docker compose up -d --build
  261  docker logs      arti_speech-myapp-1
  262  docker ps -a
  263  docker exec -it arti_speech-myapp-1 bash
  264  docker run -it arti_speech-myapp-1
  265  docker run -it arti_speech-myapp-1 bash
  266  docker build -it .
  267  docker build .
  268  docker run -it arti_speech-myapp-1 bash
  269  docker build -t arti_speech-myapp .
  270  docker run -it arti_speech-myapp-1 bash
  271  docker run -it arti_speech-myapp bash
  272  docker build -t arti_speech-myapp .
  273  docker run -it arti_speech-myapp bash
  274  ls
  275  less Dockerfile
  276  docker run -it --device /dev/snd:/dev/snd arti_speech-myapp bash
  277  docker build -t arti_speech-myapp .
  278  docker run -it --device /dev/snd:/dev/snd arti_speech-myapp bash
  279  docker build -t arti_speech-myapp .
  280  docker run -it --device /dev/snd:/dev/snd arti_speech-myapp bash
  281  docker run -it --device /dev/snd:/dev/snd -v /run/user/$(id -u)/pulse:/run/user/$(id -u)/pulse arti_speech-myapp bash
  282  docker run -it --device /dev/snd:/dev/snd --group-add audio -v /run/user/$(id -u)/pulse:/run/user/$(id -u)/pulse arti_speech-myapp bash
  283  docker run -it --device /dev/snd:/dev/snd --group-add audio -v /run/user/$(id -u)/pulse:/run/user/$(id -u)/pulse -e ALSA_CARD=S330 arti_speech-myapp bash
  284  docker build -t arti_speech-myapp .
  285  ls
  286  ls app/
  287  docker build -t arti_speech-myapp .
  288  docker run -d arti_speech-myapp bash
  289  docker ps -a
  290  docker prune -af
  291  docker system prune -af
  292  docker ps -a
  293  docker run -it arti_speech-myapp bash
  294  docker build -t arti_speech-myapp .
  295  docker run -it arti_speech-myapp bash
  296  history

**Comment by mrrostam** [comment]
This question has been asked on #552. Unfortunately, there's nothing we can do at the moment.

**Comment by williamp0044** [comment]
Thats wild. So will it reset at the end of the month or will i have to make
a myriad of temp emails. Which seems like it will just clutter your db.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
07/05/23,
03:13:24 PM

**Comment by mrrostam** [comment]
That's correct! As it is based on "Monthly Active Users," the count will reset every month. In regards to creating multiple accounts, it violates our "Terms of Service," and those accounts will be blocked.
