### ISSUE TITLE
i.MX RT1060 support

### ISSUE THREAD

**Issue by B4dWeather** [Picovoice/picovoice#61]
Is there any plan to expand the support to other NXP boards?

In particular I'm interested in the 1060, which has very similar specs to the 1050, already supported.

**Comment by kenarsa** [comment]
Not at the moment. Let's keep this open and see what kind of traction we get from the community.

If this is a commercial application you can contact Picovoice directly and they might be willing to add the support as part of the engagement.

**Comment by kenarsa** [comment]
closing due to insufficient traction
