### ISSUE TITLE
Picovoice Issue: Unable to get Porcupine to Work on Web

### ISSUE THREAD

**Issue by ThomasPinella** [Picovoice/picovoice#611]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
Porcupine should start up on web and listen for its wake word.

### Actual behaviour
Getting this error in my browser console:
```
[ERROR] Model file version is '2.1.0' but library version is '2.2.0'
[ERROR] loading parameters failed with `INVALID_ARGUMENT`

Uncaught (in promise) 'pv_porcupine_init' failed with status INVALID_ARGUMENT
```
According to github, the model I downloaded should be v2.2.0, and it looks like 2.1.0 is deprecated so I'm unable to revert to the older library version.

### Steps to reproduce the behaviour
I followed the quickstart directions for web and downloaded the porcupine model from https://github.com/Picovoice/porcupine/blob/master/lib/common/porcupine_params.pv

The command to get the base64 did not work on the .pv model I downloaded from github, it only worked on .ppn files (which I obtained from creating my custom wake word through the Picovoice console).

I tried passing into `PorcupineWorker.create()` a public path to the .pv model. I also tried passing in a public path to the custom .ppn model. And tried using the base64 of the custom wake word. For all these separate attempts, I got the same error pasted above.

**Comment by ksyeo1010** [comment]
https://github.com/Picovoice/porcupine/tree/master/binding/web#porcupine-model make sure you pass the forceWrite option to your model options

**Comment by ThomasPinella** [comment]
Sorry, forgot to specify, I did try passing the forceWrite option, and I still got the same error.

**Comment by ThomasPinella** [comment]
The demo works fine for me. However I continue to get the same error when I try running it in my own project.

**Comment by ksyeo1010** [comment]
Can't help you much as this forum is for issues for the demo/binding. You should re-download the model file and keyword file from the console and make sure they are the latest version and write `forceWrite: true` to both model and keyword parameters in the init function.

**Comment by yalin01** [comment]
did you solve the issue? if so, how did you fix it?

**Comment by ThomasPinella** [comment]
Nope, never solved it unfortunately.
