### ISSUE TITLE
Disable a picovoice user

### ISSUE THREAD

**Issue by sriramasharmaa** [Picovoice/picovoice#633]
**Is your feature request related to a problem? Please describe.**
Currently an user can be deleted but cannot be disabled

**Describe the solution you'd like**
I have a list of users for whom access key is procured from pico voice and distributed in their desktop. 
If I have to disable the user and redistribute the key to some other user, this is not possible using current solution.

**Describe alternatives you've considered**
In the cloud , I should have finer controls to block a user temporarily

**Additional context**

**Comment by kenarsa** [comment]
What do you mean you have a list of users for whom the AccessKey is procured from Picovoice?

**Comment by sriramasharmaa** [comment]
I represent Wipro Ltd. We are having a list of customer for whom we want to give picovoice license  each.

**Comment by kenarsa** [comment]
We treat everyone the same regardless of their workplace here. If you are already commercially engaged, reach out to your account manager.

What you are presenting is not doable, as it is against our terms of use.
