### ISSUE TITLE
Picovoice Issue: account or password error

### ISSUE THREAD

**Issue by leikaiwei** [Picovoice/picovoice#634]
Hello, my account is [443947595@qq.com]. I just registered on the platform to use the speech recognition feature. However, today when I tried to log in, it says "account or password error," and I can't reset the password either. Can you please help me with this?

**Comment by laves** [comment]
@leikaiwei - thank you for the report, we did find a bug in our website login. Can you try again?

**Comment by leikaiwei** [comment]
> @leikaiwei - thank you for the report, we did find a bug in our website login. Can you try again?

@laves Thank you. I tried to log in to the website again, but now it says my account has been deleted. T T

The access key in my account is already in use by my robot, and it's functioning properly.

What should I do now?

![image](https://github.com/Picovoice/picovoice/assets/13110826/03589f05-54ba-49c4-a6b7-9eeec7cd994b)

**Comment by laves** [comment]
Picovoice Audit System can delete accounts in case of [Picovoice Terms of Use](https://picovoice.ai/docs/terms-of-use/) violations, such as suspicious activities, creating multiple accounts, providing false or inaccurate information.

If you think there is a mistake, please send an email to [hello@picovoice.ai](mailto:hello@picovoice.ai) with your name, surname, country, city and project details. We’ll investigate it further.
