### ISSUE TITLE
Picovoice Documentation Issue

### ISSUE THREAD

**Issue by rukirde** [Picovoice/picovoice#635]
### What is the URL of the doc?
https://picovoice.ai/docs/api/picovoice-web/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
For IOS & Andriod, They have low level API where process returns the keywordIndex, Why doesn't Web has the same?
I want to process the audio frame right away when the wake word is detected, Web it is not syncronous
````
func getNextAudioFrame() -> [Int16] {
    // .. get audioFrame
    return audioFrame;
}

while true {
    do {
        let keywordIndex = try porcupine.process(getNextAudioFrame())
        if keywordIndex >= 0 {
            // .. detection made!
        }
    } catch { }
}
```

**Comment by laves** [comment]
@rukirde - thank you for the suggestion. We may be reworking the Web APIs in the near future and this is one of the changes we are considering. For now, the callback API is unfortunately the only means of using Porcupine on Web.
