### ISSUE TITLE
Activation limit reached from trying different SDKs

### ISSUE THREAD

**Issue by aa365** [Picovoice/picovoice#636]
Hello, I'm trying out the different SDKs for picovoice (specifically react, vue and plain js), but I'm now getting ACTIVATION_LIMIT_REACHED errors. I'm testing in different browsers but they're on the same machine. Does each browser count as an active user? How about each SDK?

**Comment by laves** [comment]
Different browsers are likely the cause of hitting the limit in this case. Changing SDKs should not cause your users to increase.

**Comment by aa365** [comment]
Thank you for the response. I still get the error even when I use the browsers where it was previously tested and working. As they were already counted as active users, I would have thought they would continue to work.

We are evaluating different options for STT, and whilst I very much like your product, this hard limit makes it difficult to do extensive testing. Can anything be done to reset the limit, even as a one off?

**Comment by kenarsa** [comment]
If you have not cleared your browser cache, then it should work. Otherwise, you can wait 30 days, and your allowance will be reset. Alternatively, you can purchase the [Developer Plan](https://picovoice.ai/pricing/).
