### ISSUE TITLE
Picovoice Issue:  not activating on iOS (React Native)

### ISSUE THREAD

**Issue by johnbowdenatfacet** [Picovoice/picovoice#64]
### Expected behaviour
Wakeword/intents should capture during video/audio play back on Android/iOS.

### Actual behaviour
Wakeword/intent not captured until no audio/video playing.

### Steps to reproduce the behaviour
Include video player/audio in app and listen for wakeword/intent

**Comment by laves** [comment]
Can you share a private repo with me with the issue isolated? It's hard to say whether this is a limitation of our audio recorder or a native Android issue.

**Comment by johnbowdenatfacet** [comment]
Hi @laves i've added a repo that is private.  when playing the second video, all ok until the video is paused then wakewords are not being detected'

**Comment by johnbowdenatfacet** [comment]
> Can you share a private repo with me with the issue isolated? It's hard to say whether this is a limitation of our audio recorder or a native Android issue.

I have this working on Android now, the problem is a physical device for iOS

**Comment by johnbowdenatfacet** [comment]
After converting to a function component and hooks, moving back to a class component and some refactoring appears to be behaving.
