### ISSUE TITLE
Invalid inputs in Unity SDK

### ISSUE THREAD

**Issue by Hyunjik-GCWW** [Picovoice/picovoice#641]
How can I reproduce the tutorial guide with Korean language support?

I am doing as [the tutorial guide](https://picovoice.ai/docs/quick-start/picovoice-unity/) says.

This works ok, but I want to use for Korean language.
```
        _picovoiceManager = PicovoiceManager.Create(ACCESS_KEY, _keywordPath, OnWakeWordDetected, _contextPath,
            OnInferenceResult, processErrorCallback: ErrorCallback);
```

For Korean language support, I copied `porcupine_params_ko.pv` and `rhino_params_ko.pv` to `Assets\StreamingAssets` directory following [the guide](https://picovoice.ai/docs/quick-start/picovoice-unity/). This does not work ok, showing "Porcupine init fiailed. Make sure your access key xxxxxx is a valid access key." No access key change is made.
```
        _picovoiceManager = PicovoiceManager.Create(ACCESS_KEY, _keywordPath, OnWakeWordDetected, _contextPath,
            OnInferenceResult, processErrorCallback: ErrorCallback,
            porcupineModelPath: @"C:\${BLAHBLAH}\Assets\StreamingAssets\porcupine_params_ko.pv",
            rhinoModelPath: @"C:\${BLAHBLAH}\Assets\StreamingAssets\rhino_params_ko.pv");
```

If the pv file name is incorrect, "Couldn't find model file at xxxxxx.pv" is shown. 

What am I missing?

**Comment by mrrostam** [comment]
@Hyunjik-GCWW We've identified an issue in our Unity documentation that will be fixed soon. The right way to tackle this is by using the path combine feature with the streamingAssetsPath. Simply insert something like Path.Combine(Application.streamingAssetsPath, "relative_path") and it should work.

**Comment by mrrostam** [comment]
Additionally, don't forget that you need keyword and context models trained for the Korean language. The error you encountered, regarding the 'incorrect access key,' is a generic error indicating that **some input arguments** are incorrect.
