### ISSUE TITLE
Picovoice Issue: cant put cheetah on pi zero w

### ISSUE THREAD

**Issue by ifsfs** [Picovoice/picovoice#643]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
Cheetah working fine

### Actual behaviour

Not working
### Steps to reproduce the behaviour

I followed the docs, downloaded the demo package but, when i tried to run the demo it says unsupported cpu architecture ‘armv61’

(Include enough details so that the issue can be reproduced independently.)

**Comment by mrrostam** [comment]
You've posted the issue in the wrong repository. Please submit it in the appropriate repository, [Cheetah](https://github.com/Picovoice/cheetah), in the future.

Regarding the error you're encountering, Cheetah is designed to work only on Raspberry Pi 3 and 4, as clearly stated in the [official doc](https://picovoice.ai/docs/quick-start/cheetah-python/) and an error is expected if you're attempting to run it on a different board.
