### ISSUE TITLE
Picovoice+Console+Issue:+

### ISSUE THREAD

**Issue by DiWa2194** [Picovoice/picovoice#647]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
Account to stay active 

### Actual behaviour
My previous two accounts have been deleted and I do not know why. Have I done anything wrong?

I am a hobbyist and want to build a speech assistant for private use.

### Steps to reproduce the behaviour
I do hope this account stays active as I have no other account. Thank you very much!
(Include enough details so that the issue can be reproduced independently.)

**Comment by ErisMik** [comment]
Picovoice Audit System can delete accounts in case of [Picovoice Terms of Use](https://picovoice.ai/docs/terms-of-use/) violations, such as suspicious activities, creating multiple accounts, providing false or inaccurate information.

If you think there is a mistake, please send an email to [hello@picovoice.ai](mailto:hello@picovoice.ai) with your name, surname, country, city and project details. We’ll investigate it further.
