### ISSUE TITLE
Picovoice Licensing on Microcontroller Question

### ISSUE THREAD

**Issue by ros-gy** [Picovoice/picovoice#654]
Hello, we are pursuing initial testing and development for an industrial application using Picovoice, specifically on a microcontroller platform. 

I need clarity around licensing. In the pricing section for Developers License, it says "up to 100 active users/month." How is this monitored, when the embedded microcontrollers are offline? I need to understand this, because in this application, the microcontrollers, once deployed to a customer, will not have internet access. Perhaps it is that we can only deploy 100 UUID's per month?

**Comment by ksyeo1010** [comment]
This repository is only for technical issues. I can't help you with licensing questions.
