### ISSUE TITLE
Picovoice Documentation Issue (/docs/faq/general/)

### ISSUE THREAD

**Issue by asktimfisher** [Picovoice/picovoice#655]
### What is the URL of the doc?

https://picovoice.ai/docs/faq/general/

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)

The "How do you calculate active users in the last 30 days?" section could use some more clarification. For example: it's currently unclear (to me at least):

- If a single developer has incorporated a single project on a single server with a single client device but uses Porcupine, Rhino, **and** Cobra in it, does "Monthly Active Users" = 3?
- If a single developer has incorporated a single project on a single server using only Porcupine but with **10** client devices (maybe a local AI assistant project in a large home with 10 wall-mount tablets), is that 1 active user or 10?

I am legit curious about the two above situations but generally speaking: I think some more examples might be helpful.

Thanks!

**Comment by ErisMik** [comment]
Hi, thanks for reporting. We are planning to change our activation system soon, and some of these details will change, but at the moment what I have written below is correct. The upcoming changes should come as an advantage for you as a free-teir user, and as you've suggested I'll ask that we add additional clarification/examples to the docs as part of the update.

> If a single developer has incorporated a single project on a single server with a single client device but uses Porcupine, Rhino, and Cobra in it, does "Monthly Active Users" = 3?

This would count as "Monthly Active Users" = 1. The activation system counts a "Monthly Active User" as the device the engines are running on (or browser in case of WASM based SDKs). All engines share the same device activation. For example, once say Porcupine registers that device, Rhino and Cobra will then use that same activation.

> If a single developer has incorporated a single project on a single server using only Porcupine but with 10 client devices (maybe a local AI assistant project in a large home with 10 wall-mount tablets), is that 1 active user or 10?

This depends on the setup of your project. Specifically, it matters where the engines are running. If the engines are running on the "server" side, then as above, this will only count as 1 device. If the engines are running on the "client" side, then this will count as 10 device activation. As above, The activations are independent of the number of engines running on each "device".

Hopefully this clears some things up, let me know if you have additional questions.

**Comment by asktimfisher** [comment]
Very much looking forward to hearing about the upcoming activation system changes!

So for example: if I'm using WASM, it might count as 10. But if I was using the NodeJS SDK, it might be 1?

**Comment by ErisMik** [comment]
> Very much looking forward to hearing about the upcoming activation system changes!
> 
> So for example: if I'm using WASM, it might count as 10. But if I was using the NodeJS SDK, it might be 1?

Assuming WASM would be running in the frontend, and NodeJS running as your server backend, then yes that would be correct.

**Comment by asktimfisher** [comment]
Perfect. Any chance I can get my MAU reset after making this noob mistake? 🙏 Totally understand if not - I'll just have to wait to 30 days for things to clear.

**Comment by ErisMik** [comment]
Sorry, unfortunately as per policy I cannot reset your activations, you'll have to wait the 30 days.

I'm closing this issue as resolved, if you run into any other issues or have questions please feel free to re-open or create another issue.
