### ISSUE TITLE
Picovoice Console Issue: 

### ISSUE THREAD

**Issue by ThreepE0** [Picovoice/picovoice#656]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
cheetah model download link works after training

### Actual behaviour
leopard model is available for download, but cheetah model link says "temporarily unavailable"

### Steps to reproduce the behaviour
create new cheetah model and define boost words, then save model.  Try to download and you'll see the "temporarily unavailable" message.

(Include enough details so that the issue can be reproduced independently.)

**Comment by ErisMik** [comment]
This is correct, Cheetah custom models are currently disabled. See https://github.com/Picovoice/cheetah/issues/193.
