### ISSUE TITLE
Picovoice Issue: Password recovery broken

### ISSUE THREAD

**Issue by jhughesbiot** [Picovoice/picovoice#659]
Password recovery is broken.

### Expected behaviour
Email reset code should be sent.

### Actual behaviour
AWS throws error indicating user not found:

X-Amzn-Errormessage:
Username/client id combination not found.
X-Amzn-Errortype:
UserNotFoundException:

User exists confirmed by trying to login via google and getting a user already created with that email error.

### Steps to reproduce the behaviour
Try to reset a password on an existing user.

**Comment by albho** [comment]
Hey @jhughesbiot,

Did you originally sign up using email and password, or through Google?

**Comment by jhughesbiot** [comment]
email and password

**Comment by albho** [comment]
Please send an email to hello@picovoice.ai with the email you used to sign up and we'll investigate this further.

**Comment by jhughesbiot** [comment]
Done

**Comment by albho** [comment]
So it looks like you signed up using all uppercased characters, could you try resetting your password again with your email all uppercased?

**Comment by jhughesbiot** [comment]
I tried both before opening this issue but it is irrelevant.  The payload sent to aws for the password reset is forced to all lower case.  I have responded to that email with a clear example showing the issue with requiring case sensitivity with emails.

**Comment by kenarsa** [comment]
@jhughesbiot, we will help you out over email with this. I will close this issue for now.
