### ISSUE TITLE
Usage without hotword

### ISSUE THREAD

**Issue by Vincz** [Picovoice/picovoice#66]
**Is your feature request related to a problem? Please describe.**
Ability to use without hotword

**Describe the solution you'd like**
Would it be possible to use picovoice without hotword? So, it would be listening continuously for intents? I added picovoice to a react-native project, all is fine, but I would like to get ride of the hotword.

Is it already possible?

**Comment by kenarsa** [comment]
Depends on what you are trying to solve. If you need multiple static voice commands that are always listening then use multiple PPNs. If you need complex commands (with slots) then you need to use Rhino but this more complex.
