### ISSUE TITLE
ACTIVATION_LIMIT_REACHED from testing  app on different devices

### ISSUE THREAD

**Issue by mikeglopez** [Picovoice/picovoice#662]
I am developing an app on one device that will be run on a second device. I decided to test the app on the second device and was having issues getting porcupine to initialize on the second device, so I tried to run it in a private browser, and then also tried it on a third device to see if the issue was on the second device and I'm then I was seeing ACTIVATION_LIMIT_REACHED.

I came across this similar issue:
https://github.com/Picovoice/picovoice/issues/636

And @kenarsa reply:
https://github.com/Picovoice/picovoice/issues/636#issuecomment-1666529804

and I think I misunderstood what they were saying about clearing the browser cache. I tried clearing my browser cache on all the devices because I thought @kenarsa was saying to clear the browser cache to release the activation from the device, so now I am unable to access porcupine on any device. Is this able to be reset in any way? It would be nice to be able to manage the activated devices and remove access from unwanted devices.

**Comment by kenarsa** [comment]
There is no way to reset or clear. You must wait for your allowance to reset or move up your plan to get more allowances.
