### ISSUE TITLE
Picovoice Issue: 

### ISSUE THREAD

**Issue by silverdesignerdeveloper** [Picovoice/picovoice#67]
although I have been trying to build the demo for days by doing git clone and following all the steps, I still haven't been able to start the app. It always gives me error both on xcode and in the react-native project doing yarn run-ios
![Schermata 2021-04-18 alle 18 16 11](https://user-images.githubusercontent.com/22931590/115152710-72f05100-a072-11eb-88ca-033451f8d791.png)

**Comment by silverdesignerdeveloper** [comment]
![Schermata 2021-04-18 alle 18 23 19](https://user-images.githubusercontent.com/22931590/115152846-35d88e80-a073-11eb-8e28-23ae9d52d861.png)
I checked this section and the file was already there

**Comment by kenarsa** [comment]
@silverdesignerdeveloper You already have an [open issue](https://github.com/Picovoice/picovoice/issues/65) and we will get to it when we can. If this is not good enough you should find an alternative solution. But I want to assure you that opening multiple issues pointing to the same problem is not going to help accelerate this at all. It is not professional and not helpful.
