### ISSUE TITLE
Picovoice Monthly Users Console Issue: 

### ISSUE THREAD

**Issue by Resacky** [Picovoice/picovoice#670]
Hello,

I am writing to report a bug, I am capped out of my monthly use for your Porcupine model and cannot continue development unless I remove the other two users. But I can't seem to remove them. There doesn't seem to be an option to. Does this mean that whenever I compile my code and run it on a new device, it's considered a new user? What happens if I compile my code on the same device? Is that also considered another user?

Does this mean I cannot continue development until I wait for the month and have my users reset?

**Comment by Resacky** [comment]
I want to mention that I'm exploring your library across various devices. Having the flexibility to reset my user access key and seamlessly switch between my test devices would greatly encourage me to invest in a dedicated development plan, so I can better showcase my product using your code.

Suppose I have to wait a month before I can continue development. That would not be productive..

**Comment by laves** [comment]
Unfortunately yes, you get three active users per 30 days on the free tier and it is not possible to reset them. They will reset automatically after 30 days. Testing on the same device should not count as multiple active users, though web has some exceptions to that.
