### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Mark2013Toronto** [Picovoice/picovoice#69]
Hello, I'm trying to make a voice activated IR remote control that will run on an STM32F469-DISCO for now.

I've created the Rhino model which looks like this:

context:
  expressions:
    pushButton:
      - activate $buttonState:state
      - select   $buttonState:state
      - $buttonState:state
  slots:
    buttonState:
      - stop
      - play
      - record
      - fast forward
      - channel up
      - channel down
      - increase volume
      - decrease volume
      - OFF

On the serial port of the target, if I say "select stop"   I'll see this:

{
  intent: "pushButton",
  slots: {
    state: "stop"
  }
}

and if I say "select OFF" I'll see this:

{
  intent: "pushButton",
  slots: {
    state: "OFF"
  }
}

What I want to do is execute a case statement based on what phrase is spoken so in the example above, I'd like to see 11 different values returned.    I know that I can just write a function to compare the returned string to an array of strings and get an index returned back, but I'm thinking that's not needed as the info should already available.

I had thought that the value of "i" in the function below would be what I want but it's always 0

![image](https://user-images.githubusercontent.com/3650010/115497553-e2646d00-a239-11eb-9904-3ea3a53eb207.png)

**Comment by mrrostam** [comment]
If I understand the issue correctly, you want to execute some commands based on the "value" of the state slot. right?
For this, you need to compare the returned value of the slot stored in inference->values[i] with the list of slots, something like:
```
if (strcmp(inference->values[i], "play") == 0) {
  // do something
} else if (strcmp(inference->values[i], "record") == 0) {
  // do something else
} ...
```
As for the variable "i", all expressions defined in the context have only one slot, which is $buttonState:state. For this reason, in the mentioned for loop "i" is always 0, which means there is only one slot for that expression.
