### ISSUE TITLE
Picovoice Console Issue: 

### ISSUE THREAD

**Issue by heia-hexagon** [Picovoice/picovoice#70]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
An email with confirmation code is sent when signing up to Picovoice Enterprise Console.

### Actual behaviour
No email with confirmation code is received when trying to sign up to Picovoice Enterprise Console (also checked junk email folder). The sign up is attempted with a previously created free-trial enterprise account. Clicking "re-send confirmation code" did not help.

### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced independently.)

**Comment by dbartle** [comment]
Can you please send an email (from the email address you signed up with) to `hello@picovoice.ai`, with a link to this issue? We can look up your email and see what's up. I'm not seeing any suspicious bounces from Picovoice Console recently.

**Comment by dbartle** [comment]
Issue due to Console emails being quarantined by receiving mail server. Some changes were made to help avoid such filters, but ultimately out of our control as far as whether they reach a user's inbox once the mail has been delivered to the MTA.
