### ISSUE TITLE
Support for Jetson NX USB sound card

### ISSUE THREAD

**Issue by danielP1S** [Picovoice/picovoice#71]
I have followed the clone and pip instructions on the web for Picovoice.
I needed to make some changes to util.py to get past the unsupported platform.

    elif '0x004' == cpu_part:
        return 'cortex-a72' + arch_info

that works and now I can run:
 python3 porcupine_demo_mic.py  --keywords alexa

from the ~/picovoice/resources/porcupine/demo/python directory and it listens:

Listening {
  alexa (0.50)

However I cannot get the mic and speakers to switch from device index 0 to device 32. IE

dan@Am1:~/picovoice/resources/porcupine/demo/python$ python3 porcupine_demo_mic.py  --audio_device_index 32 --keywords alexa 
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.tegra-hda-xnx.pcm.front.0:CARD=0'

'cards.tegra-hda-xnx.pcm.front.0:CARD=0' is the device at index 0.

In addition I have updated my asound.conf file to default to the USB device.
asound sound.wav for example plays fine.

Any help would be appreciated...

**Comment by mrrostam** [comment]
As for the unsupported platform, you should be fine if you are using the latest version (1.1.3) of the Picovoice pip package as we added a generic model for all arm-based CPUs. Could you check and let me know the version of the package you have installed on your Jetson device.

Regarding the mic issue, you do not need to specify the audio device using "audio_device_index" if the .asoundrc file is configured correctly. Please send the output of the following command here:
```
arecord -L; cat ~/.asoundrc
```

**Comment by danielP1S** [comment]
Hi,I pip uninstalled  both pvporcupinedemo and picovoicedemo.Pip installed picovoicedemo.
Now I get:dan@Am1:~$ picovoice_demo_mic --keyword_path ~/picovoice/resources/porcupine/resources/keyword_files/jetson/porcupine_jetson.ppn --context_path ~/picovoice/resources/rhino/resources/contexts/jetson/smart_lighting_jetson.rhn[ERROR] keyword file has incorrect format or belongs to a different platform[ERROR] loading keyword file at '/home/dan/picovoice/resources/porcupine/resources/keyword_files/jetson/porcupine_jetson.ppn' failed with 'INVALID_ARGUMENT'Traceback (most recent call last):  File "/usr/local/bin/picovoice_demo_mic", line 8, in <module>    sys.exit(main())  File "/usr/local/lib/python3.6/dist-packages/picovoicedemo/picovoice_demo_mic.py", line 181, in main    output_path=os.path.expanduser(args.output_path) if args.output_path is not None else None).run()  File "/usr/local/lib/python3.6/dist-packages/picovoicedemo/picovoice_demo_mic.py", line 48, in __init__    rhino_sensitivity=rhino_sensitivity)  File "/usr/local/lib/python3.6/dist-packages/picovoice/picovoice.py", line 104, in __init__   sensitivities=[porcupine_sensitivity])  File "/home/dan/.local/lib/python3.6/site-packages/pvporcupine/__init__.py", line 68, in create    sensitivities=sensitivities)  File "/home/dan/.local/lib/python3.6/site-packages/pvporcupine/porcupine.py", line 94, in __init__    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()ValueError

Listed below are the outputs you asked for.


dan@Am1:~/Downloads$ arecord -Lnull    Discard all samples (playback) or generate zero samples (capture)pulse    PulseAudio Sound Servermusicdemixervoiceaux_plugmusic_and_voicedefault    Playback/recording through the PulseAudio sound servermicspeakersysdefault:CARD=jetsonxaviernxa    jetson-xaviernx-ape,     Default Audio Devicefront:CARD=jetsonxaviernxa,DEV=0    jetson-xaviernx-ape,     Front speakersdmix:CARD=jetsonxaviernxa,DEV=0    jetson-xaviernx-ape,     Direct sample mixing devicedmix:CARD=jetsonxaviernxa,DEV=1    jetson-xaviernx-ape,     Direct sample mixing devicedmix:CARD=jetsonxaviernxa,DEV=2    jetson-xaviernx-ape,     Direct sample mixing devicedmix:CARD=jetsonxaviernxa,DEV=3    jetson-xaviernx-ape,     Direct sample mixing devicedmix:CARD=jetsonxaviernxa,DEV=4    jetson-xaviernx-ape,     Direct sample mixing devicedmix:CARD=jetsonxaviernxa,DEV=5    jetson-xaviernx-ape,     Direct sample mixing devicedmix:CARD=jetsonxaviernxa,DEV=6    jetson-xaviernx-ape,     Direct sample mixing devicedmix:CARD=jetsonxaviernxa,DEV=7    jetson-xaviernx-ape,     Direct sample mixing devicedmix:CARD=jetsonxaviernxa,DEV=8    jetson-xaviernx-ape,     Direct sample mixing devicedmix:CARD=jetsonxaviernxa,DEV=9    jetson-xaviernx-ape,     Direct sample mixing devicedmix:CARD=jetsonxaviernxa,DEV=10    jetson-xaviernx-ape,     Direct sample mixing devicedmix:CARD=jetsonxaviernxa,DEV=11    jetson-xaviernx-ape,     Direct sample mixing devicedmix:CARD=jetsonxaviernxa,DEV=12    jetson-xaviernx-ape,     Direct sample mixing devicedmix:CARD=jetsonxaviernxa,DEV=13    jetson-xaviernx-ape,     Direct sample mixing devicedmix:CARD=jetsonxaviernxa,DEV=14    jetson-xaviernx-ape,     Direct sample mixing devicedmix:CARD=jetsonxaviernxa,DEV=15    jetson-xaviernx-ape,     Direct sample mixing devicedmix:CARD=jetsonxaviernxa,DEV=16    jetson-xaviernx-ape,     Direct sample mixing devicedmix:CARD=jetsonxaviernxa,DEV=17    jetson-xaviernx-ape,     Direct sample mixing devicedmix:CARD=jetsonxaviernxa,DEV=18    jetson-xaviernx-ape,     Direct sample mixing devicedmix:CARD=jetsonxaviernxa,DEV=19    jetson-xaviernx-ape,     Direct sample mixing devicedsnoop:CARD=jetsonxaviernxa,DEV=0    jetson-xaviernx-ape,     Direct sample snooping devicedsnoop:CARD=jetsonxaviernxa,DEV=1    jetson-xaviernx-ape,     Direct sample snooping devicedsnoop:CARD=jetsonxaviernxa,DEV=2    jetson-xaviernx-ape,     Direct sample snooping devicedsnoop:CARD=jetsonxaviernxa,DEV=3    jetson-xaviernx-ape,     Direct sample snooping devicedsnoop:CARD=jetsonxaviernxa,DEV=4    jetson-xaviernx-ape,     Direct sample snooping devicedsnoop:CARD=jetsonxaviernxa,DEV=5    jetson-xaviernx-ape,     Direct sample snooping devicedsnoop:CARD=jetsonxaviernxa,DEV=6    jetson-xaviernx-ape,     Direct sample snooping devicedsnoop:CARD=jetsonxaviernxa,DEV=7    jetson-xaviernx-ape,     Direct sample snooping devicedsnoop:CARD=jetsonxaviernxa,DEV=8    jetson-xaviernx-ape,     Direct sample snooping devicedsnoop:CARD=jetsonxaviernxa,DEV=9    jetson-xaviernx-ape,     Direct sample snooping devicedsnoop:CARD=jetsonxaviernxa,DEV=10    jetson-xaviernx-ape,     Direct sample snooping devicedsnoop:CARD=jetsonxaviernxa,DEV=11    jetson-xaviernx-ape,     Direct sample snooping devicedsnoop:CARD=jetsonxaviernxa,DEV=12    jetson-xaviernx-ape,     Direct sample snooping devicedsnoop:CARD=jetsonxaviernxa,DEV=13    jetson-xaviernx-ape,     Direct sample snooping devicedsnoop:CARD=jetsonxaviernxa,DEV=14    jetson-xaviernx-ape,     Direct sample snooping devicedsnoop:CARD=jetsonxaviernxa,DEV=15    jetson-xaviernx-ape,     Direct sample snooping devicedsnoop:CARD=jetsonxaviernxa,DEV=16    jetson-xaviernx-ape,     Direct sample snooping devicedsnoop:CARD=jetsonxaviernxa,DEV=17    jetson-xaviernx-ape,     Direct sample snooping devicedsnoop:CARD=jetsonxaviernxa,DEV=18    jetson-xaviernx-ape,     Direct sample snooping devicedsnoop:CARD=jetsonxaviernxa,DEV=19    jetson-xaviernx-ape,     Direct sample snooping devicehw:CARD=jetsonxaviernxa,DEV=0    jetson-xaviernx-ape,     Direct hardware device without any conversionshw:CARD=jetsonxaviernxa,DEV=1    jetson-xaviernx-ape,     Direct hardware device without any conversionshw:CARD=jetsonxaviernxa,DEV=2    jetson-xaviernx-ape,     Direct hardware device without any conversionshw:CARD=jetsonxaviernxa,DEV=3    jetson-xaviernx-ape,     Direct hardware device without any conversionshw:CARD=jetsonxaviernxa,DEV=4    jetson-xaviernx-ape,     Direct hardware device without any conversionshw:CARD=jetsonxaviernxa,DEV=5    jetson-xaviernx-ape,     Direct hardware device without any conversionshw:CARD=jetsonxaviernxa,DEV=6    jetson-xaviernx-ape,     Direct hardware device without any conversionshw:CARD=jetsonxaviernxa,DEV=7    jetson-xaviernx-ape,     Direct hardware device without any conversionshw:CARD=jetsonxaviernxa,DEV=8    jetson-xaviernx-ape,     Direct hardware device without any conversionshw:CARD=jetsonxaviernxa,DEV=9    jetson-xaviernx-ape,     Direct hardware device without any conversionshw:CARD=jetsonxaviernxa,DEV=10    jetson-xaviernx-ape,     Direct hardware device without any conversionshw:CARD=jetsonxaviernxa,DEV=11    jetson-xaviernx-ape,     Direct hardware device without any conversionshw:CARD=jetsonxaviernxa,DEV=12    jetson-xaviernx-ape,     Direct hardware device without any conversionshw:CARD=jetsonxaviernxa,DEV=13    jetson-xaviernx-ape,     Direct hardware device without any conversionshw:CARD=jetsonxaviernxa,DEV=14    jetson-xaviernx-ape,     Direct hardware device without any conversionshw:CARD=jetsonxaviernxa,DEV=15    jetson-xaviernx-ape,     Direct hardware device without any conversionshw:CARD=jetsonxaviernxa,DEV=16    jetson-xaviernx-ape,     Direct hardware device without any conversionshw:CARD=jetsonxaviernxa,DEV=17    jetson-xaviernx-ape,     Direct hardware device without any conversionshw:CARD=jetsonxaviernxa,DEV=18    jetson-xaviernx-ape,     Direct hardware device without any conversionshw:CARD=jetsonxaviernxa,DEV=19    jetson-xaviernx-ape,     Direct hardware device without any conversionsplughw:CARD=jetsonxaviernxa,DEV=0    jetson-xaviernx-ape,     Hardware device with all software conversionsplughw:CARD=jetsonxaviernxa,DEV=1    jetson-xaviernx-ape,     Hardware device with all software conversionsplughw:CARD=jetsonxaviernxa,DEV=2    jetson-xaviernx-ape,     Hardware device with all software conversionsplughw:CARD=jetsonxaviernxa,DEV=3    jetson-xaviernx-ape,     Hardware device with all software conversionsplughw:CARD=jetsonxaviernxa,DEV=4    jetson-xaviernx-ape,     Hardware device with all software conversionsplughw:CARD=jetsonxaviernxa,DEV=5    jetson-xaviernx-ape,     Hardware device with all software conversionsplughw:CARD=jetsonxaviernxa,DEV=6    jetson-xaviernx-ape,     Hardware device with all software conversionsplughw:CARD=jetsonxaviernxa,DEV=7    jetson-xaviernx-ape,     Hardware device with all software conversionsplughw:CARD=jetsonxaviernxa,DEV=8    jetson-xaviernx-ape,     Hardware device with all software conversionsplughw:CARD=jetsonxaviernxa,DEV=9    jetson-xaviernx-ape,     Hardware device with all software conversionsplughw:CARD=jetsonxaviernxa,DEV=10    jetson-xaviernx-ape,     Hardware device with all software conversionsplughw:CARD=jetsonxaviernxa,DEV=11    jetson-xaviernx-ape,     Hardware device with all software conversionsplughw:CARD=jetsonxaviernxa,DEV=12    jetson-xaviernx-ape,     Hardware device with all software conversionsplughw:CARD=jetsonxaviernxa,DEV=13    jetson-xaviernx-ape,     Hardware device with all software conversionsplughw:CARD=jetsonxaviernxa,DEV=14    jetson-xaviernx-ape,     Hardware device with all software conversionsplughw:CARD=jetsonxaviernxa,DEV=15    jetson-xaviernx-ape,     Hardware device with all software conversionsplughw:CARD=jetsonxaviernxa,DEV=16    jetson-xaviernx-ape,     Hardware device with all software conversionsplughw:CARD=jetsonxaviernxa,DEV=17    jetson-xaviernx-ape,     Hardware device with all software conversionsplughw:CARD=jetsonxaviernxa,DEV=18    jetson-xaviernx-ape,     Hardware device with all software conversionsplughw:CARD=jetsonxaviernxa,DEV=19    jetson-xaviernx-ape,     Hardware device with all software conversionssysdefault:CARD=Device    USB PnP Sound Device, USB Audio    Default Audio Devicefront:CARD=Device,DEV=0    USB PnP Sound Device, USB Audio    Front speakerssurround21:CARD=Device,DEV=0    USB PnP Sound Device, USB Audio    2.1 Surround output to Front and Subwoofer speakerssurround40:CARD=Device,DEV=0    USB PnP Sound Device, USB Audio    4.0 Surround output to Front and Rear speakerssurround41:CARD=Device,DEV=0    USB PnP Sound Device, USB Audio    4.1 Surround output to Front, Rear and Subwoofer speakerssurround50:CARD=Device,DEV=0    USB PnP Sound Device, USB Audio    5.0 Surround output to Front, Center and Rear speakerssurround51:CARD=Device,DEV=0    USB PnP Sound Device, USB Audio    5.1 Surround output to Front, Center, Rear and Subwoofer speakerssurround71:CARD=Device,DEV=0    USB PnP Sound Device, USB Audio    7.1 Surround output to Front, Center, Side, Rear and Woofer speakersiec958:CARD=Device,DEV=0    USB PnP Sound Device, USB Audio    IEC958 (S/PDIF) Digital Audio Outputdmix:CARD=Device,DEV=0    USB PnP Sound Device, USB Audio    Direct sample mixing devicedsnoop:CARD=Device,DEV=0    USB PnP Sound Device, USB Audio    Direct sample snooping devicehw:CARD=Device,DEV=0    USB PnP Sound Device, USB Audio    Direct hardware device without any conversionsplughw:CARD=Device,DEV=0    USB PnP Sound Device, USB Audio    Hardware device with all software conversionsdan@Am1:~/Downloads$ cat ~/asoundcat: /home/dan/asound: No such file or directorydan@Am1:~/Downloads$ cat ~/asoundrccat: /home/dan/asoundrc: No such file or directorydan@Am1:~/Downloads$ cat ~/.\asoundrcpcm.!default {  type asym  capture.pcm "mic"  playback.pcm "speaker"}pcm.mic {  type plug  slave {    pcm "plughw:CARD=Device,DEV=0"  }}
pcm.speaker {  type plug  slave {    pcm "hw:2,0"  }}


-----Original Message-----

**Comment by mrrostam** [comment]
I should have mentioned that you need to use raspberry pi models for Porcupine and Rhino on unsupported platforms.

And from the output, everything seems fine; did you restart your device after setting up the `.asoundrc`? Could you also go to the system setting -> sound -> input and check if the os identifies the mic correctly? you should be able to see the input level going up and down as you speak.

**Comment by danielP1S** [comment]
Getting Better...still have errors but it runs and hears  "porcupine" wake word.
dan@Am1:~$ picovoice_demo_mic --keyword_path ~/picovoice/resources/porcupine/resources/keyword_files/raspberry-pi/porcupine_raspberry-pi.ppn --context_path ~/picovoice/resources/rhino/resources/contexts/raspberry-pi/smart_lighting_raspberry-pi.rhnALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.tegra-hda-xnx.pcm.front.0:CARD=0'ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directoryALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directoryALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM frontALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rearALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfeALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.sideALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.tegra-hda-xnx.pcm.surround51.0:CARD=0'ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directoryALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directoryALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.tegra-hda-xnx.pcm.surround51.0:CARD=0'ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directoryALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directoryALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.tegra-hda-xnx.pcm.surround40.0:CARD=0'ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directoryALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directoryALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround40ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.tegra-hda-xnx.pcm.surround51.0:CARD=0'ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directoryALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directoryALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround41ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.tegra-hda-xnx.pcm.surround51.0:CARD=0'ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directoryALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directoryALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround50ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.tegra-hda-xnx.pcm.surround51.0:CARD=0'ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directoryALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directoryALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround51ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.tegra-hda-xnx.pcm.surround71.0:CARD=0'ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directoryALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directoryALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround71ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.tegra-hda-xnx.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directoryALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directoryALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM iec958ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.tegra-hda-xnx.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directoryALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directoryALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdifALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.tegra-hda-xnx.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directoryALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directoryALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdifALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modemALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modemALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phonelineALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phonelineALSA lib pcm_dmix.c:990:(snd_pcm_dmix_open) The dmix plugin supports only playback streamALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slaveALSA lib pcm_params.c:2162:(snd1_pcm_hw_refine_slave) Slave PCM not usableALSA lib pcm_params.c:2162:(snd1_pcm_hw_refine_slave) Slave PCM not usableALSA lib pcm_params.c:2162:(snd1_pcm_hw_refine_slave) Slave PCM not usableALSA lib pcm_params.c:2162:(snd1_pcm_hw_refine_slave) Slave PCM not usableALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave[Listening ...][wake word]
Didn't understand the command.
[wake word]
Didn't understand the command.
[wake word]
Didn't understand the command.
[wake word]
Didn't understand the command.
[wake word]
Didn't understand the command.
[wake word]

**Comment by danielP1S** [comment]
PS. aplay 06.wav    plays a wav file via my speakers without issue. In addition Audacity sees the devices "speakers" and "mic" and can record and play back...I also ran an "arecord" test and it works too.

**Comment by mrrostam** [comment]
Good, so the mic is working. Those error/warnings are kind of expected as we have not not fully configured ALSA lib. You can get rid of them by adding `2>/dev/null`.

**Comment by mrrostam** [comment]
what is the command you are using that Rhino can not understand?

**Comment by danielP1S** [comment]
I am not having a problem with that. It is a state machine issue where you speak the wake-word as a command. I can fix that. Is there a reason why the program goes through every sound device in the machine and displays an error?  I just want it to use the default devices "mic" and "speaker". And thank you for your help.

**Comment by mrrostam** [comment]
Oh I see! if you want to only detect wake-word, you should use the [Porcupine package](https://pypi.org/project/pvporcupinedemo/) instead. 

For the sound device, it is related to the sound library and how it interacts with Linux. There is not much there that we can do.
