### ISSUE TITLE
Rhino - best practice recommendation

### ISSUE THREAD

**Issue by TzurV** [Picovoice/picovoice#716]
I need to implement the following intent options:

< main >: (< Tag > | < Toggle > | < P2P > | Contour | Snapshot | < Start > | Add | Menu | Close | Exit | < Delete > | < Follow > | Goto );

< Tag >: Tag | Tags;

< Toggle >: Toggle | Change;

< P2P >: point to point;

< Start >: Start  | Go;

< one2nine >: One | Two | Three | Four | Five | Six | Seven | Eight | Nine;

< Delete >: Delete (All | < one2nine >);

< Follow >: Follow (Me | Us);

What is the best Rhino practice in this case?
I'm failing to create a working definition supporting < one2nine >.

**Comment by ksyeo1010** [comment]
For single digit integers, you can use  `$pv.SingleDigitInteger` built in slot. More information is available: https://picovoice.ai/docs/tips/syntax-cheat-sheet/#built-in-slots.
