### ISSUE TITLE
"Tallinn" missing from Rhino word list

### ISSUE THREAD

**Issue by robtinkers** [Picovoice/picovoice#724]
I am unable to add "ytrewq" (a nonsense word) to Boost Words for a Leopard & Cheetah model because `Nonexistent word`.

I am able to successfully add "Tallinn" (capital of Estonia) to Boost Words for an English language Leopard & Cheetah model.

So far so good.

But I am unable to add "Tallinn" to an English-language Rhino intent because `Unknown pronunciation(s) for: 'Tallinn'`

As Leopard & Cheetah accept the world "Tallinn", I would also expect Rhino to accept the same word.

While I understand that there has to be a cut-off line somewhere, Tallinn _is_ a capital city, Rhino already accepts the names of smaller cities, and word list inconsistencies seem to break the principle of least surprise.

Unfortunately, it doesn't seem possible to add custom vocabulary to a Rhino model, so no workaround is possible.

(Bratislava seems to have a similar problem.)

**Comment by kenarsa** [comment]
You can add  "ytrewq" to `Custom Vocabulary` and then add it to `Boost Words.` 

You are right; the word must be added to the Rhino's vocabulary. I will keep the issue open to address it as an improvement in subsequent releases, but I cannot commit to a timeline.

**Comment by ErisMik** [comment]
Sorry, this feature didn't make it onto our roadmap.
