### ISSUE TITLE
Picovoice Issue: can't save in console, error "Rhino could not validate context within the given timeout"

### ISSUE THREAD

**Issue by HarmoNick777** [Picovoice/picovoice#745]
Hello, when I edit my Rhino in the console to add new intents and such, it tries to load but after some time I'm being given an error of type "Rhino could not validate context within the given timeout".

No result on searching for that error here and the closest thing I could find to a solution is the FAQ saying: _There is no technical limit on the number of slot values. However, on platforms with limited memory (particularly MCUs), the total number will be dictated by the available amount of memory. Roughly speaking, for every 100 unique words/phrases, you should allocate around 50 KB of additional memory._

I'm not sure this is the problem here though, as this is the console giving an error when I input "too many" intents.
Any help on how I can turnaround that problem would be greatly appreciated.

**Comment by mrrostam** [comment]
Identifying the main reason for this behavior is hard without knowing the context. Would it be possible for you to share the yml file containing your context? If you prefer not to share it here, you can also email it to hello@picovoice.ai.

**Comment by mrrostam** [comment]
Thank you for sharing the YAML file.

It seems that the timeout issue is a result of the complexity of the context. If possible, try simplifying it.

If this concerns a commercial product and you require it as is, consider consulting an expert [here](https://picovoice.ai/consulting/#consult-an-expert) to resolve the issue."
