### ISSUE TITLE
Picovoice Documentation Issue (/docs/tips/syntax-cheat-sheet/)

### ISSUE THREAD

**Issue by sim0wastaken** [Picovoice/picovoice#746]
I am unable to find information on whether or not the Rhino Speech-to-Intent model allows to have a "throwaway" parameter to use in case I want to have undefined variables inside the sentence (such as the name of a city, or the name of a person) but I don't want the model to not recognize the command because I told him "Call a waiter for Simone" insted of "Call a waiter for"

**Comment by kenarsa** [comment]
Rhino doesn't have this feature, currently.
