### ISSUE TITLE
Picovoice Issue: 

### ISSUE THREAD

**Issue by AbRehman0346** [Picovoice/picovoice#749]
I can't get the demo/flutter_clock project run. It has a assets folder missing.
thorws error: No file or variants found for asset: assets/android/pico%20clock_android.ppn.

**Comment by laves** [comment]
Did you run the `copy` script before building the demo as mentioned in the [readme](https://github.com/Picovoice/picovoice/tree/master/demo/flutter-clock#picoclock)?

**Comment by laves** [comment]
Closed due to inactivity
