### ISSUE TITLE
Add "Jarvis" to French lexicon

### ISSUE THREAD

**Issue by M4TH1EU** [Picovoice/picovoice#75]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
Train my wake word

### Actual behaviour
Show me this error : Error creating wake word draft: Missing pronunciation(s): ['jarvis']

### Steps to reproduce the behaviour
Log to console and try to train new wake-word

So I was trying to train the word 'Jarvis' with the french language because the built-in doesn't always pick up with a french pronunciation...
But on the console, I'm stuck with this error...

Could you please improve french recognition for the Jarvis or tell me how to fix this error ?

Thanks you really much.
Have a nice weekend.

Mathieu B.

**Comment by kenarsa** [comment]
@M4TH1EU thank you! not a bug. the French dictionary just doesn't have this word in it. we can add it in the future release of French models but nothing we can do immediately. I reflected this in the title. thanks for reporting.

**Comment by M4TH1EU** [comment]
Okay, thank you.
You have any idea when the new release will be ready ? I see the last release if from december 2020, kinda worried I'm gonna have to wait a long time :(

During my research, I've seen this post https://github.com/Picovoice/Porcupine/issues/44#issuecomment-403566356 does the mail part still apply?

Have a nice day.

**Comment by M4TH1EU** [comment]
up

**Comment by kenarsa** [comment]
Can't commit to a timeline at this time. You need to wait for the release

**Comment by M4TH1EU** [comment]
Hey, it's been 2 months, any news about this release ?

**Comment by M4TH1EU** [comment]
Hi,

I don't know if this can help, I searched for a dictionnary with Jarvis in it but didn't find one in French.
The english pronunciation kinda starts with a D like Djarvis.
In french it's something like JArvisse 

Have a look on this site for an example : https://www.pronouncekiwi.com/JARVIS
![image](https://user-images.githubusercontent.com/41210834/129319290-d93f1fad-13d6-4811-90fb-09d506d2d051.png)
It's the one with 1 votes in french in the first table.

Another one here : https://fr.howtopronounce.com/french/jarvis-joey
There's a "joey" after jarvis but the jarvis prononciation is correct aswell.

Hope you can add this as soon as possible or give us a custom ppn file (for linux) here, it would be amazing :)

Thanks, have a nice day.

**Comment by M4TH1EU** [comment]
Could I have any updates on this ?

**Comment by M4TH1EU** [comment]
@kenarsa any news ?

**Comment by kenarsa** [comment]
this didn't make it to our new release and doesn't seem that we are going to be able to prioritize it in the coming months. the `en` model is the best we can provide at this time.
