### ISSUE TITLE
我的账户被删除了，我不清楚我违反了什么条款

### ISSUE THREAD

**Issue by sailikas** [Picovoice/picovoice#750]
昨天我按照文档使用自定义唤醒词功能，并把他集成到我的python程序中用于语音唤醒打开led灯。
我是picovoice免费用户
第二天我的账户无法登录，我按照提示发送了邮件到hello@picovoice.ai，不过我仅仅收到了自动回复。
于是我来这里提出疑问。
希望有人能帮帮我。谢谢

**Comment by sailikas** [comment]
我的账户邮箱是3265625613@qq.com

**Comment by laves** [comment]
Apologies, but at this time we are unable to offer multilingual support via GitHub.
