### ISSUE TITLE
how do I change account Email 

### ISSUE THREAD

**Issue by TzurV** [Picovoice/picovoice#751]
How can I change my Picovoice account Email ?
Should I delete the existing one and open a new account ?

**Comment by laves** [comment]
It is not currently possible to change your Picovoice account email via the Picovoice Console. May I ask why you need to change your account?

**Comment by TzurV** [comment]
I'm loosing access to the registered email but still require access to the my Picovoice account to carry on a project I'm working on.

**Comment by laves** [comment]
Closing as we are unable to transfer accounts
