### ISSUE TITLE
Picovoice Console Issue: 

### ISSUE THREAD

**Issue by montesolid** [Picovoice/picovoice#752]
Hello - 
I have purchased a developers license. I have developed a web application that uses Cobra / Porcupine / Rhino.
It appears that each time I clear my browser cache and re-log into my application to use picovoice, another license gets claimed.
It does not appear to be counting concurrent users, obviously, and doesnt appear to be using info from the devices that are connecting, so how, exactly, do you count the number of licenses used?
Is there something in my application that I can use to remove a license once I exit the application? At this rate, the licenses will all be eaten up and I will have none left to test with.

**Comment by montesolid** [comment]
Note that I purchased the 100 user developer license. I am not operating on your free model. I have 5 separate devices that have accessed / used your product, however 37 licenses have been consumed.

**Comment by laves** [comment]
This is being addressed via email technical support.
