### ISSUE TITLE
Request for Future Turkish Language Support

### ISSUE THREAD

**Issue by EmbeddedMinds** [Picovoice/picovoice#753]
Hello,

I hope this message finds you well. I am interested in knowing if there are plans to introduce Turkish language support for Picovoice in the future. It would be greatly appreciated if you could provide information or a roadmap regarding the addition of Turkish language capabilities.

Thank you for your attention to this matter.

Best regards,

**Comment by laves** [comment]
@EmbeddedMinds - thank you for your interest. Your request has been noted. We continually review our language support so, while it is possible we may add Turkish language support in the future, we cannot commit to a timeline.
