### ISSUE TITLE
Picovoice Console Issue: Porcupine Wake Word

### ISSUE THREAD

**Issue by TzurV** [Picovoice/picovoice#754]
I want to try the word Luna as a wake-up word but get 'Phrase is too short to be an effective wake word'.

Is there a way to bypass this for testing purposes?

I know it is not recommended to use short words, but I still would like to test it as I have recordings with this word.

**Comment by laves** [comment]
@TzurV - unfortunately no, we cannot bypass this. We usually suggest adding a word like "Hey", "Hello" or "Okay" in front of a brand name to get it to the length requirement.
