### ISSUE TITLE
Console wierd behavior - Leopard custom voc / boost words

### ISSUE THREAD

**Issue by tempo-riz** [Picovoice/picovoice#762]
Hello, I am trying to train a leopard model with some keywords and boost words. I successfully imported my YAML file, but then I encountered an error stating 'nonexistent word.' Perhaps I am mistaken, but it would make sense to be able to boost the custom vocabulary I added to enhance the chances of accurate recognition.

Here is a minimal example demonstrating this:

```
new: 
    dragon dairain ancien: []
boost: 
  - no
  - yes
  - dragon dairain ancien
```

![image](https://github.com/Picovoice/picovoice/assets/64015162/dc6f2523-9351-439f-a3ee-f40512c9a82c)

**Comment by ksyeo1010** [comment]
Thanks for reporting, we are looking at it and let you know here when the fix is out.

**Comment by albho** [comment]
hey @tempo-riz, this issue has now been fixed!
