### ISSUE TITLE
picovoice not starting

### ISSUE THREAD

**Issue by Sayanbm** [Picovoice/picovoice#763]
so i recent started with picovoice with my raspberry pi ZERO 2w , after following the readme steps it looks something like this

![New Bitmap Image (2)](https://github.com/Picovoice/picovoice/assets/156459491/5ebee743-5d2e-4709-a551-06c86d6d600e)

and it says 

Usage : ./demo/respeaker-rpi0/picovoice_demo_mic -l LIBRARY_PATH -a ACCESS_KEY -k KEYWORD_PATH -c CONTEXT_PATH -p PPN_MODEL_PATH -r RHN_MODEL_PATH -i INPUT_AUDIO_DEVICE [--porcupine_sensitivity PPN_SENSITIVITY --rhino_sensitivity RHN_SENSITIVITY --require_endpoint "true"|"false" ]

as i am new to raspberry pi don't know much about it but i noticed after running the code it is not using microphone (my usb audio device blinks when i am using the microphone and i recoded some files to make sure it's working and it is)

**Comment by ksyeo1010** [comment]
The demo is not running at all, it is printing the usage which means your argument is wrong. Take a look at the readme https://github.com/Picovoice/picovoice/tree/master/demo/c and make sure arguments are correct.
