### ISSUE TITLE
Picovoice Console Issue: Download Button

### ISSUE THREAD

**Issue by Lars-L00t** [Picovoice/picovoice#77]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
Train wake word model and click on download to get it

### Actual behaviour
There is no download button

### Steps to reproduce the behaviour
I do not know. Can not Download on commercial nor an free trial enterprise account.

(Include enough details so that the issue can be reproduced independently.)

**Comment by dbartle** [comment]
The model is processing, and the instructions clearly state that it will not be ready immediately. You will also receive an email notification when training is complete.

**Comment by Lars-L00t** [comment]
Oh I am sorry my bad. Didnt see the status collumn. thought when I could do the browser test of the model the training would be done.
thanks very much
