### ISSUE TITLE
Help With STM32F407 Demo

### ISSUE THREAD

**Issue by GSkoumal** [Picovoice/picovoice#801]
Hello,
I am currently working with the STM32F407 Demo and trying to expand it some. I need to be able to use UART to interface with some other peripherals, but as the project does not use an .ioc file I am a little lost. Is there a way for me to include the HAL libraries for UART and enable UART4 on pins PA0 and PA1, while leaving the rest of the demo intact? 

I understand this might be a little out of scope for you guys but any help you can offer would be appreciated. Either way thanks for taking the time to read!

**Comment by mrrostam** [comment]
The demo is intended to demonstrate how to work with Picovoice in C on a microcontroller. Once you've determined how to record audio on your board properly, the rest should be straightforward as it's basically just a function call. So, you can start your own project with your config and then integrate Picovoice by linking against the Picovoice library. The steps are explained in detail [here](https://picovoice.ai/docs/quick-start/picovoice-microcontroller/)

**Comment by GSkoumal** [comment]
OK awesome, when it comes to the input audio stream. Does picovoice need a buffer filled with PDM data or PCM data? Also do you have any recommendations for where I could learn to record that audio? I see in the demo it uses a BSP library but that does not seem to exist in the current versions. Thanks for you help.

**Comment by mrrostam** [comment]
The requirement for the input PCM is explained in detail in the documentation, as well as the [header file](https://github.com/Picovoice/picovoice/blob/master/sdk/c/include/pv_picovoice.h). BSP is typically the best starting point, but there are often projects on GitHub that can assist you with this task. Also, I'm unable to assist you with the build issue.
