### ISSUE TITLE
Picovoice Leopard Implementation Issue 

### ISSUE THREAD

**Issue by kateottenwess** [Picovoice/picovoice#805]
I am attempting to implement the Leopard STT api into my project that is built using React Native and Expo Go. When calling  const leopard = await Leopard.create(accessKey, modelPath);, I get an error stating [Error: unexpected code: undefined, message: Cannot read property 'create' of null], despite me following all of the installation steps correctly and I am verified that my Leopard import is indeed functional (console.log(Leopard) prints [Function Leopard] prior to my create call). Are there compatibility issues with Leopard and Expo? I have also ensured that the accessKey and model path are being correctly passed.

**Comment by albho** [comment]
hey @kateottenwess, please open the issue in [Leopard's own repo](https://github.com/Picovoice/leopard).
