### ISSUE TITLE
Picovoice VAD COBRA 

### ISSUE THREAD

**Issue by kLkA** [Picovoice/picovoice#818]
Hi , where can I find benchmarks on cobra VAD performance? 
How well does it on multi-core platforms and how concurrency model works? 
Is there any latency benchmarks on higher load?

**Comment by ErisMik** [comment]
You can see a comparison to WebRTC here: https://github.com/Picovoice/voice-activity-benchmark
Cobra is single threaded. Cobra operates in real time: it can process audio faster than you can record live audio to it even on low-power boards such as a Raspberry PI. I don't have exact latency benchmarks for you, you'll have to make those tests yourself for your specific project.
