### ISSUE TITLE
Picovoice Console Issue: can't download wake word models

### ISSUE THREAD

**Issue by joeggg** [Picovoice/picovoice#823]
Hi,

I tried creating some custom wake words, but the download button didnt download anything and just closed the popup when I clicked it, possibly due to my ad blocker but I can't check as I ran out of models. Is there any way to recover them or download them? I don't see a menu option anywhere for something like that

**Comment by mrrostam** [comment]
Hello, unfortunately, we don't maintain a record of created models, so you'll need to wait until your allowance is renewed next month.
