### ISSUE TITLE
Picovoice Platform Issue: I got logged out from picvoice developer consol for no reason . 

### ISSUE THREAD

**Issue by Raiyan007-gb** [Picovoice/picovoice#826]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Platform docs
- [X] I have searched the existing issues for Picovoice Platform

### SDK

Python

### Picovoice package version

1.0.0

### Framework version

Python 3.9

### Platform

Raspberry Pi

### OS/Browser version

Windows

### Describe the bug

When i try to login back it says "An account registered with 'raiyan2025@gmail.com' has been deleted and cannot be reactivated. This may be due to a user request, inactivity, or Picovoice Terms of Use violations."

### Steps To Reproduce

1

### Expected Behavior

When i try to login back it says "An account registered with 'raiyan2025@gmail.com' has been deleted and cannot be reactivated. This may be due to a user request, inactivity, or Picovoice Terms of Use violations."

**Comment by Raiyan007-gb** [comment]
why is it happening

**Comment by laves** [comment]
The message you received from console is pretty self-explanatory
