### ISSUE TITLE
Picovoice Console Issue: 

### ISSUE THREAD

**Issue by IvanoSaratoga** [Picovoice/picovoice#829]
Hi all,
we are evaluating your service "porcupine wake word" but we experienced problems with authentication.
We are using just one app with account ivano.boscolo@saratogadental.it and we see in your portal the active users indicator to 1, so I suppose we didn't over using your free plan.<br>
We got the error: Activation error 136 randomically, but some times it works finally.

Can you please let us know what could be the problem, please?
Can you also explain better what is the active users meaning, please?

For example, we installed an app with the same access key in two different mobile phones and the active users in your portal is always showing 1 (I would expect 2....).

**Comment by mrrostam** [comment]
Hello,

To best address your Porcupine engine authentication issue, please report it using [this template on GitHub](https://github.com/Picovoice/porcupine/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=Porcupine+Issue%3A+). This will provide the necessary details for us to investigate and assist you effectively.

Regarding "active users", it generally refers to the number of registered users within the last month.

I'll be closing this current issue for now. Please submit your bug report through the link above, and we'll gladly help you resolve the problem.
