### ISSUE TITLE
unsupported CPU

### ISSUE THREAD

**Issue by kelshen1** [Picovoice/picovoice#837]
Hello, 

I want to run picovoice on a radxa zero3W , with python SDK.

however, i tried with linux and mac arm64 architecture but il faile to launch.

the board use a RK3566 Quad-core 64-bit Cortex-A55 processor.

i wonder if there is any chance one of the architecture available can fit this one ?

kind regards

**Comment by matt200-ok** [comment]
Hello @kelshen1, unfortunately we do not officially support the Radxa Zero3w. If this is for a commercial product you can reach out to your sales contact at Picovoice, or otherwise [contact us](https://picovoice.ai/pricing/) through sales to get the feature added.
