### ISSUE TITLE
Picovoice Platform Issue: The listerner not getting the voice from "External BLE devicess"

### ISSUE THREAD

**Issue by AMAL-KVS** [Picovoice/picovoice#838]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Platform docs
- [X] I have searched the existing issues for Picovoice Platform

### SDK

Android

### Picovoice package version

picovoice_flutter: ^3.0.3

### Framework version

latest

### Platform

Android

### OS/Browser version

latest

### Describe the bug

IN flutter The wakeup word not getting the data from external ble devicess. like : if i connect ear phones ,  still listern from mobile inbuild micro phones , not in the external devicess , my aim was need to achive the wake up word in through ble devicess

### Steps To Reproduce

i connected to ble , the wake up word not getting

### Expected Behavior

The wakeup word not getting the data from external ble devicess. like : if i connect ear phones ,  still listern from mobile inbuild micro phones , not in the external devicess , my aim was need to achive the wake up word in through ble devicess

**Comment by laves** [comment]
@AMAL-KVS - thanks for your interest in the Picovoice Flutter SDK. The Picovoice platform does not record audio, it only processes it for voice recognition. The package responsible for recording audio is [flutter-voice-processor](https://github.com/Picovoice/flutter-voice-processor), which may not support Bluetooth devices. I suggest integrating another recording library that does support Bluetooth to address your issue.
