### ISSUE TITLE
Flutter Support for Cobra

### ISSUE THREAD

**Issue by mhamdan91** [Picovoice/picovoice#842]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Platform docs
- [X] I have searched the existing issues for Picovoice Platform

### SDK

Flutter

### Picovoice package version

does not matter

### Framework version

does not matter

### Platform

Android

### OS/Browser version

does not matter

### Describe the bug

Is it possible to create a flutter package for COBRA?

### Steps To Reproduce

do not have to...

### Expected Behavior

Does not matter

**Comment by matt200-ok** [comment]
Hello @mhamdan91, unfortunately we do not support flutter for Cobra. If this is for a commercial product you can reach out to your sales contact at Picovoice, or otherwise contact us through sales to get the feature added.
