### ISSUE TITLE
Picovoice Console Issue: 

### ISSUE THREAD

**Issue by tmccaffr100** [Picovoice/picovoice#853]
I don't see why I have reached the user limit 3/users on my account but I am the only user. Is it because I have downloaded my access code multiple times? If that is the case can my account be reset and I will save the access code.

**Comment by albho** [comment]
Initializing engines on different devices will activate new users. Unfortunately, per our [Terms of Use](https://picovoice.ai/docs/terms-of-use/) your AccessKey cannot be reset. You'll need to wait 30 days for your limits to reset.

**Comment by tmccaffr100** [comment]
Thank you. Now I understand.
________________________________
