### ISSUE TITLE
Picovoice Console Issue: Missing Download button for .ppn wakeword

### ISSUE THREAD

**Issue by inOXcrm** [Picovoice/picovoice#86]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
Download Button as described in https://picovoice.ai/docs/quick-start/console-porcupine/

### Actual behaviour
 Missing Download button for .ppn wakeword

### Steps to reproduce the behaviour
https://console.picovoice.ai/ppn
(Include enough details so that the issue can be reproduced independently.)

**Comment by inOXcrm** [comment]
Resolved: Apperently you have to wait until Mail for Download is sent, in my case this took two hours. Then the download can be starated.

**Comment by dbartle** [comment]
The training button tells you that it will take 2-3 hours when you click it. When it's completed it sends the email. The GUI could use some improvements to make this more obvious but the information is all there.
