### ISSUE TITLE
Picovoice Platform Issue: CocoaPods is on the way out, please use Swift Package Manager for distributing your iOS packages

### ISSUE THREAD

**Issue by r-token** [Picovoice/picovoice#861]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Platform docs
- [X] I have searched the existing issues for Picovoice Platform

### SDK

iOS

### Picovoice package version

All

### Framework version

All Swift versions

### Platform

iOS

### OS/Browser version

All iOS versions

### Describe the bug

Per CocoaPods themselves, CocoaPods is going into [maintenance mode](https://blog.cocoapods.org/CocoaPods-Support-Plans/). Apple's own [Swift Package Manager](https://www.swift.org/documentation/package-manager/) has been around for 9 years and is rock solid.

CocoaPods has seen several significant security breaches recently, including [this one](https://www.evasec.io/blog/eva-discovered-supply-chain-vulnerabities-in-cocoapods) that exposed millions of iOS apps.

Please support Swift Package Manager for iOS package distribution across your libraries and deprecate the CocoaPods versions.

### Steps To Reproduce

Install via CocoaPods

### Expected Behavior

Install via Swift Package Manager

**Comment by ksyeo1010** [comment]
Thanks for letting us know. Will let the team know but won't really have an estimate when the change will be done.

**Comment by albho** [comment]
The latest Picovoice-iOS package (3.0.2) is now available on SPM (via `https://github.com/Picovoice/picovoice.git`).
