### ISSUE TITLE
Picovoice Console Issue: Porcupine Custom Wake Word Not Downloading File

### ISSUE THREAD

**Issue by denizulcay** [Picovoice/picovoice#862]
I tried using Porcupine on the console. It detected my wake word and I trained the model. But when I clicked download for MacOS on Chrome browser, it did not trigger a download. I attempted twice but no use.

**Comment by laves** [comment]
@denizulcay - we're not seeing issues downloading files on our end and our system hasn't alerted us to any failures related to this functionality. Is it possible you were at your Porcupine model download limit? Was something on your browser blocking downloads?

**Comment by laves** [comment]
closed due to inactivity
