### ISSUE TITLE
Picovoice iOS SDK issue

### ISSUE THREAD

**Issue by ashu1702** [Picovoice/picovoice#867]
Hey, I am trying to use your iOS SDK via Cocoapods and after following every step as given in the documentation, i can't seem to be able to fix the following errors. Could you please point me in the right direction : 

error: Sandbox: rsync.samba(2341) deny(1) file-write-create /Users/.../Library/Developer/Xcode/DerivedData/Picotest-abvmaeubnjimalajbsxkysmoyzrw/Build/Products/Debug-iphonesimulator/Picotest.app/Frameworks/Cheetah.framework/_CodeSignature (in target 'Picotest' from project 'Picotest')
error: Sandbox: rsync.samba(2342) deny(1) file-write-create /Users/.../Library/Developer/Xcode/DerivedData/Picotest-abvmaeubnjimalajbsxkysmoyzrw/Build/Products/Debug-iphonesimulator/Picotest.app/Frameworks/Cheetah.framework/.Cheetah.IaD43H (in target 'Picotest' from project 'Picotest')
error: Sandbox: rsync.samba(2342) deny(1) file-write-create  /Users/.../Library/Developer/Xcode/DerivedData/Picotest-abvmaeubnjimalajbsxkysmoyzrw/Build/Products/Debug-iphonesimulator/Picotest.app/Frameworks/Cheetah.framework/.Info.plist.Q1avvh (in target 'Picotest' from project 'Picotest')

I am using Xcode 15.4 and trying to first run it on my simulator.

Note: When i used your sample code, i was able to build it and run it using my access keys.

**Comment by matt200-ok** [comment]
Hello @ashu1702 , since the sample code works for you we are unable to debug the changes made to your code that causes it to no longer work.

**Comment by ashu1702** [comment]
@matt200-ok  In my project, there is nothing else but your sdk and it doesn't build due to the issues i shared above which clearly shows your sdk. The SDK version in the podfile within your sample code and what i get when i use the instructions from your documents is different. Also there might be some project settings that needs to be enabled/disabled to ensure your sdk works. Please let me know how should i go about fixing it. Thank you
