### ISSUE TITLE
Built in Slots in non-english versions 

### ISSUE THREAD

**Issue by giberlei** [Picovoice/picovoice#87]
I wonder if there is a way to use built in slots to build a model in the rhino console with non-english versions. I was searching in the documentation and googled it, but found no information regarding this problem.

**Comment by dbartle** [comment]
Only English Rhino supports built-in slots, currently. This is a natural feature to add to all languages, so I will keep the issue open for tracking and so that others can indicate their interest as well.

**Comment by dnknth** [comment]
What's the point of supporting non-English languages if numeric slots are not recognised?

**Comment by samueleguino97** [comment]
Im currently in dire need of this feature, I need to be able to use The numeric built in slots!

**Comment by ErisMik** [comment]
We now have support for non-en builtin slots in [Console](https://console.picovoice.ai/).
