### ISSUE TITLE
Picovoice Platform Issue: Not receiving audio from connected bluetooth devices on iOS

### ISSUE THREAD

**Issue by jacobmDAS** [Picovoice/picovoice#870]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Platform docs
- [X] I have searched the existing issues for Picovoice Platform

### SDK

Flutter

### Picovoice package version

3.0.3

### Framework version

3.22.2

### Platform

iOS

### OS/Browser version

17.4.1

### Describe the bug

PicoVoice's Flutter package is not receiving audio from bluetooth microphones when run on iOS devices. This has been tested on several iPhones and an iPad.

### Steps To Reproduce

1. Connect a bluetooth microphone to an iOS device
2. Open an app with PicoVoice on the device
3. Leave the room with the bluetooth microphone and close doors to block sound (but stay within bluetooth range) 
4. Speak into the microphone
5. Picovoice does not recognize wake words or intents

### Expected Behavior

PicoVoice should respond to audio from any connected audio source, including bluetooth microphones.

**Comment by albho** [comment]
Hey @jacobmDAS, apologies for the delayed response. The latest [picovoice_flutter](https://pub.dev/packages/picovoice_flutter) package (3.0.4) should no longer have this issue. I'll close this issue, but feel free to re-open if the issue persists.
