### ISSUE TITLE
Picovoice Console Issue: 

### ISSUE THREAD

**Issue by xNomadx1** [Picovoice/picovoice#876]
Hello, I'm pretty new to this. I'm having hard time finding my ppn. file to add to my resource folder in vs code. Is there a way to have new one sent to me? I have the access key just not the actual downloadable file. Thank you.

**Comment by albho** [comment]
You can choose built-in .ppn files from [here](https://github.com/Picovoice/porcupine/tree/master/resources/keyword_files) based on your platform. If you want to train a custom keyword, use [Picovoice Console](https://console.picovoice.ai/signup). (see [Porcupine Tutorial](https://www.youtube.com/watch?v=T6jxYRSyF2w))
