### ISSUE TITLE
Picovoice Console Issue: Inquiry About Recognizing Multiple Wake Words in Porcupine

### ISSUE THREAD

**Issue by Cesar-s16** [Picovoice/picovoice#888]
Hello Picovoice Support Team,

We are currently using Porcupine for wake word recognition in Spanish with the porcupine_params_es.pv model provided in your repository. At the moment, we have configured a wake word "asistente ayuda", which works well.

Our question is: Is it possible to configure Porcupine to recognize more than one distinct wake word within the same model? For example, we would like Porcupine to recognize both "asistente ayuda" and "estoy bien" without having to create a separate model for each wake word.

We appreciate your guidance on how to achieve this functionality efficiently.

Looking forward to your response.

Best regards,
César Sotillo
cesarsotillo16@gmail.com
Cesar-s16 (github)

**Comment by albho** [comment]
No, each wake word needs to be trained as an individual model. Please make an effort to follow the [documentation](https://picovoice.ai/docs/porcupine/) before opening issues.
