### ISSUE TITLE
Picovoice Issue: MIMXRT1050-EVKB Demo not working

### ISSUE THREAD

**Issue by jturnsek** [Picovoice/picovoice#93]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
Picovoice demo showing wake word and intent

### Actual behaviour
Picovoice demo showing only UUID and nothing more

### Steps to reproduce the behaviour
MCUXpresso IDE 11.3.1, MIMXRT1050 SDK 2.9.1 and running the demo. Notice the wait in LPI2C routines in the initialization phase (while loop).

(Include enough details so that the issue can be reproduced independently.)

**Comment by mrrostam** [comment]
I believe some old config and driver files cause this issue. 
We’re going to run a few more tests before we finalize and merge it, but all changes are available on a test branch: https://github.com/Picovoice/picovoice/pull/94
it would be so helpful if you also try it and let us know the result

**Comment by jturnsek** [comment]
It is a kind of working now, but I think MIC sensitivity is very bad. I must talk very close to the MIC in order to get the wake word and intent recognized and sometimes does not recognize it at all.

**Comment by mrrostam** [comment]
Great!, for the quality of the mic, you can use [Shepherd](https://picovoice.ai/docs/picovoice-shepherd/imxrt1050) to save the recorded audio and see if there is anything wrong with it
