### ISSUE TITLE
Android SDk -   java.io.IOException: Initialization failed. 

### ISSUE THREAD

**Issue by vinitagetaido** [Picovoice/picovoice#96]
Did not get params.pv file 
After saving .ppn file in android , app giving null pointer exception.

### Expected behaviour
Porcupine should run and able to detect custom wake word

### Actual behaviour
IO error and porcupine null pointer exception

### Steps to reproduce the behaviour
porcupineManager = new PorcupineManager.Builder()
                .setKeywordPath(keywordFilePath)
                 .build(getApplicationContext(),
                            new PorcupineManagerCallback() {
                                @Override
                                public void invoke(int keywordIndex) {
                                    }
                                    });
                                }
                            });
        } catch (PorcupineException e) {
            Log.i("exception ",e.toString());
        }

**Comment by dbartle** [comment]
1) Please format your code to be more legible. I don't see where you're actually setting the keyword path.

2) The keyword files generated with Picovoice Console are not permitted for distribution, so do not attach them.

3) Can you reproduce this issue using the Android demo? This will provide the most straightforward path to a resolution, as we support our demo code. We generally do not assist with 3rd party code.

4) The subject mentions a model .pv file, but the content of your message is talking about keyword (.ppn) file. Can you clarify why you mentioned the .pv file?

**Comment by vinitagetaido** [comment]
When I have created a custom wake word from an enterprise account, I got a .ppn file.
I have added that  ppn file in raw folder and given the path inside setKeywordPath(keywordFilePath).
Thats it . But every time I ran the app , it gives null pointer exception.
ai.picovoice.porcupine.PorcupineException: java.io.IOException: Initialization failed.

**Comment by dbartle** [comment]
You should be able to recreate this issue using the Android demo, and then provide us all of the relevant changes that you applied. You did not provide the information needed to help, so I am closing this issue.
